edpm_ansible/roles/edpm_ceph_client_files/defaults/main.yml
edpm_ansible/roles/edpm_ceph_client_files/handlers/main.yml
edpm_ansible/roles/edpm_ceph_client_files/meta/main.yml
edpm_ansible/roles/edpm_ceph_client_files/molecule/default/converge.yml
edpm_ansible/roles/edpm_ceph_client_files/molecule/default/molecule.yml
edpm_ansible/roles/edpm_ceph_client_files/molecule/default/prepare.yml
edpm_ansible/roles/edpm_ceph_client_files/tasks/main.yml
edpm_ansible/roles/edpm_ceph_client_files/vars/main.yml

This patch includes the `edpm_ceph_client_files` role to the list of the `edpm` roles.
It will be used to copy on the `external compute nodes` both `ceph.conf` and the
related `keyring`.
Signed-off-by: Francesco Pantano <fpantano@redhat.com>

Include EDPM Ceph client files to the list of roles

---

.github/workflows/check-pr.yaml
.github/workflows/codeql.yml

Some basic github actions for the repo. The CodeQL is derived from [openstack-ansibleee-operator](https://github.com/openstack-k8s-operators/openstack-ansibleee-operator/blob/main/.github/workflows/codeql.yml), while the check-pr relies on tox and pre-commit combination. 
Both are using ubuntu-22.04 nodes. 
Signed-off-by: Jiri Podivin <jpodivin@redhat.com>

Adding stub github actions

---

edpm_ansible/roles/edpm_kernel/molecule/kernelargs-hugepages-adding/test_vars.yml
edpm_ansible/roles/edpm_kernel/molecule/kernelargs-hugepages-modify-existing-kernelargs/test_vars.yml
edpm_ansible/roles/edpm_kernel/molecule/kernelargs-hugepages-modify-idempotency-change/test_vars.yml
edpm_ansible/roles/edpm_kernel/molecule/kernelargs-hugepages-modify-idempotency-nochange/test_vars.yml
edpm_ansible/roles/edpm_kernel/molecule/kernelargs-hugepages-modify-integer/test_vars.yml
edpm_ansible/roles/edpm_kernel/molecule/kernelargs-hugepages-modify-remove/test_vars.yml
edpm_ansible/roles/edpm_kernel/molecule/kernelargs-hugepages-modify/test_vars.yml
edpm_ansible/roles/edpm_kernel/molecule/kernelargs-hugepages-nochange-remove/test_vars.yml
edpm_ansible/roles/edpm_kernel/molecule/kernelargs-hugepages-nochange/test_vars.yml
edpm_ansible/roles/edpm_kernel/molecule/kernelargs-update/converge.yml
edpm_ansible/roles/edpm_kernel/molecule/kernelargs-update/verify.yml
edpm_ansible/roles/edpm_kernel/molecule/kernelargs/test_vars.yml
edpm_ansible/roles/edpm_kernel/tasks/kernelargs.yml
edpm_ansible/roles/edpm_kernel/tasks/upgrade_tasks.yml

Because we no longer use heat, the current variable name no longer makes sense.

edpm_kernel: Remove HEAT_TEMPLATE from variable name

---

.ansible-lint
.yamllint
requirements.txt
tox.ini

I've removed bulk of the tox configuration that wasn't directly involved in the style checking, while porting over files we need for linting ansible and yaml files.
I didn't include the documentation and release notes environments because it may be better to start from scratch there.
Openstack constraints file isn't compatible with required version of tenacity, so it's not being considered for now. 
Signed-off-by: Jiri Podivin <jpodivin@redhat.com>

Adding minimal tox setup to keep style parity with tripleo-ansible

---

.pre-commit-config.yaml
edpm_ansible/ansible_plugins/filter/helpers.py
edpm_ansible/ansible_plugins/modules/container_config_data.py
edpm_ansible/ansible_plugins/modules/container_puppet_config.py
edpm_ansible/ansible_plugins/modules/edpm_container_image_prepare.py
edpm_ansible/ansible_plugins/modules/edpm_container_manage.py
edpm_ansible/ansible_plugins/modules/edpm_os_net_config_mappings.py
edpm_ansible/ansible_plugins/strategy/edpm_base.py
edpm_ansible/roles/edpm_nova_compute/files/tests/test_nova_statedir_ownership.py
edpm_ansible/roles/edpm_ssh_known_hosts/molecule/default/tests/test_default.py
edpm_ansible/roles/edpm_ssh_known_hosts/molecule/no_networks/tests/test_no_networks.py
tests/conftest.py
tests/test_molecule.py

Most of the previously ignored style violations have been resolved. This includes unused imports and variables, as well as less intrusive style deficiencies.
Since we are starting essentially from scratch here I believe we should avoid perpetuating some of the issues that plagued our codebase before. Appropriate baseline is essential for this, as it prevents reintroduction of previously resolved problems. 
Any further code ported from tripleo-ansible will possibly require some changes to comply. But since it isn't going to be done in one go it should be manageable, while also offering an opportunity to look over some other cases inviting possible refactor. 
Signed-off-by: Jiri Podivin <jpodivin@redhat.com>

Raising the bar on code compliance

---

tox.ini

These environment variables are not used because we have not yet imported the molecule tests. These should be added when we import the molecule tests with the modified name (not current one prefixed with TRIPLEO_).
Signed-off-by: Takashi Kajinami <tkajinam@redhat.com>

tox: Remove unused environment variables for moulecule tests

---

edpm_ansible/roles/edpm_bootstrap/molecule/default/tests/test_default.py

This removes the leftover of the puppet package, which was missed in e5f38797e18ff5639692027e62549870921773f4 .

Remove remaining reference to puppet package

---

edpm_ansible/roles/edpm_kernel/defaults/main.yml
edpm_ansible/roles/edpm_kernel/tasks/kernelargs.yml
edpm_ansible/roles/edpm_ovn/files/neutron-cleanup

The path was used in TripleO but it no longer makes sense because we'll not use puppet to generate config files.

Get rid of reference to /var/lib/config/puppet-generated

---

edpm_ansible/roles/edpm_bootstrap/tasks/bootstrap.yml

This directory was used in TripleO but should no longer be used in EDPM which does not use heat.

Stop creating /var/lib/heat-config

---

edpm_ansible/roles/edpm_network_config/defaults/main.yml
edpm_ansible/roles/edpm_network_config/templates/2_linux_bonds_vlans/2_linux_bonds_vlans.j2
edpm_ansible/roles/edpm_network_config/templates/2_linux_bonds_vlans/2_linux_bonds_vlans_dpdk.j2
edpm_ansible/roles/edpm_network_config/templates/bonds_vlans/bonds_vlans.j2
edpm_ansible/roles/edpm_network_config/templates/bonds_vlans/bonds_vlans_dpdk.j2
edpm_ansible/roles/edpm_network_config/templates/bonds_vlans/bonds_vlans_storage.j2
edpm_ansible/roles/edpm_network_config/templates/bonds_vlans/controller_no_external.j2
edpm_ansible/roles/edpm_network_config/templates/ci/public_bond.j2
edpm_ansible/roles/edpm_network_config/templates/net_config_bond.j2

There is currently no default defined for bond_interface_ovs_options. This change adds a default for the option to avoid Ansible issues if the variable isn't defined. This default was determined using the defaults were using in TripleO.
Additionally, this change is also bringing the name of the variable in-line with the standard variable naming convention used in the module by pre-pending edpm_ to the start of the name.

Consistent naming of bond_interface_ovs_options variable

---

edpm_ansible/ansible_plugins/modules/container_config_hash.py
edpm_ansible/roles/edpm_container_manage/defaults/main.yml
edpm_ansible/roles/edpm_container_manage/tasks/main.yml

- added `_create_checksum` function in `container_config_hash` ansible module, to generate hashes for given folders of configuration files. This function was performed in a bash script called `container-puppet.sh`
- removed debug and step parameters from `container_config_hash` ansible module
- changed `edpm_container_manage_update_config_hash` boolean variable to true in edpm_container_manage role in order to enable hashes updates.

Trigger the container restart when configuration change

---

openstack_ansibleee/Dockerfile

Currently while building openstack-ansible-runner image in Zuul CI, it got hit by following error
```
Unknown error when attempting to call Galaxy at
'https://gal\naxy.ansible.com/api/v2/collections/community/general/versions/?page_size=100
```
While looking over following issue
https://github.com/ansible/galaxy/issues/2302
adding timeout to 120 to ansible galaxy install seems to be one of the solution.
It will help to mitigate unwanted failure of the job.

Added timeout 120 to ansible-galaxy install command

---

.github/workflows/openstack-ansibleee-runner.yaml
openstack_ansibleee/Dockerfile

To customize the image using the github action, use the already cloned repo in the job and copy the content when building the openstack-ansibleee-runner container image.
Depends-On: https://review.rdoproject.org/r/c/rdo-jobs/+/47269

Use already cloned git repo in Dockerfile instead of git clone

---

OWNERS
OWNERS_ALIASES

Propose OWNERS file for `edpm-ansible`.
PR in `release` project: https://github.com/openshift/release/pull/36549

Add OWNERS file to edpm-ansible

---

openstack_ansibleee/edpm_entrypoint.sh

The contents of the $RUNNER_CMDLINE env var will be written to
/runner/env/cmdline, which will be passed to the ansible execution. This
will allow further configuration of the execution to set things such as
--tags.

Add support for /runner/env/cmdline

---

openstack_ansibleee/edpm_entrypoint.sh

/runner/env/cmdline is not a YAML file, therefore the leading "---" is
not needed.

Cmdline setting fix

---

Makefile
README.rst

A local change to edpm-ansible may need to be tested within a custom
openstack-ansibleee-runner image. Makefile targets are added to simplify
building and pushing the image.

Add Makefile targets for building and pushing the ansible-runner image

---

edpm_ansible/roles/edpm_nova_libvirt/defaults/main.yml
edpm_ansible/roles/edpm_ovn/tasks/configure.yml

It modifies following roles to use existing container image variables:
- In edpm_nova_libvirt role
- use edpm_nova_libvirt_container_image as edpm_nova_libvirt_container_config_image
- In edpm_ovn
- use edpm_ovn_metadata_agent_image instead of hardcoding it.

Reuse container images variable in EDPM role

---

edpm_ansible/roles/edpm_container_standalone/tasks/main.yml

Some containers might have credentials in their environments, and dumping the whole definition can reveal the secrets. This ensures the definition is not dumped in logs. Note that users can still review the generated files to review the data.

Do not dump container definitions

---

edpm_ansible/ansible_plugins/filter/helpers.py

cmp function was removed, as it essentially just wraps normal condition check.
Explicit inheritance from object was removed.
Retrieval of default value from dictionary was simplified.
I've also slightly expanded the docstrings so they would be more accurate,
and reorganized conditional on line 108 to short circuit the evaluation.
Comparing two dictionaries is relatively expansive compared to plain boolean value.

Refactoring helpers module to be somewhat more pythonic

---

edpm_ansible/roles/edpm_iscsid/defaults/main.yml
edpm_ansible/roles/edpm_logrotate_crond/defaults/main.yml
edpm_ansible/roles/edpm_nova_compute/defaults/main.yml
edpm_ansible/roles/edpm_nova_libvirt/defaults/main.yml
edpm_ansible/roles/edpm_nova_libvirt/molecule/run_virtqemud/test_vars.yml
edpm_ansible/roles/edpm_ovn/defaults/main.yml

This change updates the contianer images in the role defaults
to use stable/zed to align with the current images used in the
operators.
Closes: #68

use stable/zed images by default

---

zuul.d/playbooks/directories.yml
zuul.d/playbooks/pre.yml

I had already commented those tasks in the past, but they can be safely removed since [this](https://review.opendev.org/c/openstack/tripleo-quickstart/+/877386) has been merged.

Removed containers-common downgrade workaround

---

Makefile

This change should allow for a test setup if the there isn't a defined path to the `ci-framework` repo. 
Issue: #72

Changing default ci-framework repo path to fix conditional

---

Makefile

This should allow to run Molecule wihtout any issue. Note that the related commit[1] is also needed in order to make it fully usable.
[1] https://github.com/openstack-k8s-operators/ci-framework/pull/71

Correct how molecule is launched from within a container

---

Makefile

This patch bypasses the ci-framework "molecule_nodeps" target and directly calls the script.
It also bind-mount the ci-framework repository elsewhere in the tree in order to avoid potential issues with ansible auto-discovery capabilities.
This patch was tested with a non-modified ci-framework repository, and was successful with an existing container image as well as with a brand new built image (from that very same Makefile).

Correct how molecule is launched

---

.pre-commit-config.yaml

This PR aim to upgrade the `pre-commit` hooks since they were imported from the parent project and they were rather old.
* pre-commit from version 3.4.0 to 4.4.0
* flake8 from version 3.9.0 to version 5.0.4 (version 6.0.0 is failing with an error, see comments)
* ansible-lint from 5.3.2 to 6.14.2 (old version requires ansible < 2.12 and we're using ansible 2.14)
* bashate from version 2.0.0 to version 2.1.1

updated pre-commit tests

---

Makefile
README.rst

The rule is effectivelly duplicating `execute_molecule' target. There is no need to have them both and such arrangement would be potentially confusing. README was adjusted to reflect the change.

Removing existing 'execute_molecule_tests' target

---

roles/edpm_hosts_entries/molecule/default/molecule.yml
roles/edpm_hosts_entries/tasks/main.yml

```
TASK [osp.edpm.edpm_hosts_entries : Prepare new /etc/hosts] ********************
fatal: [edpm-compute-0]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'plan' is undefined. 'plan' is undefined\n\nThe error appears to be in '/usr/share/ansible/collections/ansible_collections/osp/edpm/roles/edpm_hosts_entries/tasks/main.yml': line 50, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Prepare new /etc/hosts\n  ^ here\n"}
```
https://github.com/openstack-k8s-operators/dataplane-operator/pull/116#discussion_r1145298940

Remove plan and edpm_stack_name 

---

Makefile

Verbosity of the molecule tests in ci-framwork has been opened[0] to external control.
With this patch we will take up the argument and set default verbosity to triple `v`.
[0]https://github.com/openstack-k8s-operators/ci-framework/pull/76

Setting default verbosity of molecule tests

---

edpm_ansible/roles/edpm_growvols/defaults/main.yml
edpm_ansible/roles/edpm_growvols/meta/main.yml
edpm_ansible/roles/edpm_growvols/molecule/default/converge.yml
edpm_ansible/roles/edpm_growvols/molecule/default/molecule.yml
edpm_ansible/roles/edpm_growvols/molecule/default/prepare.yml
edpm_ansible/roles/edpm_growvols/tasks/main.yml
edpm_ansible/roles/edpm_growvols/vars/redhat.yml

When the target host has the LVM based whole disk layout, running growvols will grow each volume by the amount specified in the growvols_args variable.
The intent is that this role is invoked by a playbook after deploy-edpm-facts.yml and before deploy-edpm-pre-network.yml. If the target host has the growvols script installed, it will be run, otherwise the role is a noop.

Add a growvols role and playbook

---

.ansible-lint

Some of the directives for ansible lint are no longer necessary, as they were carried over from tripleo-ansible, and can be dropped.

Removing obsolete settings from ansible-lint config

---

roles/edpm_iscsid/templates/iscsid.yaml.j2
roles/edpm_logrotate_crond/templates/logrotate_crond.yaml.j2
roles/edpm_ovn/templates/ovn_controller.yaml.j2
roles/edpm_ovn/templates/ovn_metadata_agent.yaml.j2

... because we removed all healthcheck scripts from container images.

Get rid of container healthchecks

---

roles/edpm_ceph_client_files/defaults/main.yml
roles/edpm_ceph_client_files/tasks/main.yml

Remove task to fail role if edpm_ceph_client_files_source is empty/undefined. Default edpm_ceph_client_files_source and edpm_ceph_client_files_config_home to /etc/ceph.
If edpm_ceph_client_files_source does not exist on Ansible host (e.g. stat returns "No such file or directory"), task will warn ("Unable to find '/etc/ceph' in expected paths") but not fail.
The dataplane-operator will invoke this role only when the extraMounts has an extraVolType of Ceph. In that case it is expected that /etc/ceph is mounted in the AEE pod as it is for other pods which use Ceph (e.g. Cinder or Glance). This role will then copy files in that directory to the EDPM node.
This change makes it easier for users since they don't need to override the variables edpm_ceph_client_files_config_home and …

Default edpm_ceph_client_files_source to /etc/ceph

---

openstack_ansibleee/Dockerfile

This ensures dnf/yum cache are cleared after package installation, to minimize container image size.

Clean dnf/yum cache

---

roles/edpm_ovn/defaults/main.yml

Added variables with default:
```
edpm_ovn_chassis_mac_mapping_prefixes:
datacentre: "0e:01"  # {'physnet': 'mac_prefix'}
edpm_ovn_chassis_mac_mapping_seed: "{{ ansible_machine_id }}"
```
The `edpm_ovn_chassis_mac_mapping_seed` should be something machine specific - machine-id by default, but inventory_hostname, an IPv4 or IPv6 address fact etc can be used.
Example:
```
edpm_ovn_bridge_mappings:
- "datacentre:br-ex"
- "providernet:br-provider"
- "baremetal:br-baremetal"
edpm_ovn_chassis_mac_mapping_prefixes:
datacentre: "0e:01"
providernet: "0e:02"
baremetal: "0e:03"
```
When configuringing ovn generate a mac address using by combining the per-physnet MAC-prefix and a random generated MAC using the machine-id as the seed.

edpm_ovn: external_ids ovn-chassis-mac-mappings

---

Makefile
scripts/test_roles.py

Tests for all roles can now be executed locally, using make target execute_molecule_local. The script picks up all roles in the dir, runs their respective molecule tests in sequence.
Local machine needs to have a molecule runtime properly installed.

Run molecule tests locally in sequence

---

.github/workflows/documentation.yaml
docs/build-docs.sh

The file has been empty since tenacity removal in dc26e33a9a8004b7b1c3714027253e8b2b931908 If it is ever needed again we can create it again, but since this is not a standard python package we can continue without it.

Removing the requirements.txt

---

ansible-requirements.txt
galaxy.yml
zuul.d/playbooks/pre.yml

This file is not really a requirements file but a upper-constraints file but the current content does not define any constraints so can be removed.
We probably need this later when we pin ansible to a specific version but the file can be re-added at that time.

Remove ansible-requirements.txt

---

.github/workflows/build-collection.yaml

This action will first build and then attempt to install edpm-ansible collection.
It is meant to serve as precursor to a potential, yet unrealized, build-and-publish action, which could be run after creation of a new tag, as part of our CI.

Adding collection build and installation action

---

roles/edpm_ovn_bgp_agent/defaults/main.yml

The default value has been increased at the agent [1]
[1] https://review.opendev.org/c/openstack/ovn-bgp-agent/+/881171

Update resync default value for the agent

---

roles/edpm_ssh_known_hosts/molecule/default/converge.yml
roles/edpm_ssh_known_hosts/molecule/default/molecule.yml
roles/edpm_ssh_known_hosts/molecule/default/prepare.yml
roles/edpm_ssh_known_hosts/molecule/default/tests/test_default.py

Slight adjustment was made to the name of provisioned host, in order to align with other refactored tests.
#108

molecule tests for edpm_ssh_knonw_hosts

---

playbooks/deploy_edpm_os_install.yml
playbooks/deploy_edpm_pre_network.yml

edpm_growvols has been added to pre_network playbook and also moves tripleo_kernel/tripeo_tuned tasks to pre_network as they need to be done before network configuration for NFV usecases.

Add edpm_growvols role to deploy_edpm_pre_network playbook

---

scripts/molecule_venv.sh

Molecule doesn't have to be installed separately, because it already is listed in the 'molecule-requirements.txt' file.

Removing unnecessary step in the venv script

---

roles/edpm_ovn/defaults/main.yml

Automatically generate the first tow octets for the MAC address pefixes.
First octet:
Pick random from configurable list of first octets,
defaults to` ["0e", "1e", "2e", "3e"]` but the user can
extend this if ridicules amount of bridges is required.
Second octet:
Uses the bridge mapping + loop index as seed for a random
number between 0 and 255 converted to hex value.
Iterate between 0, 255 for each bridge until the bridge is in `seen_bridges`. 256 possible iterations is a lot, the loop will in practice only do a couple of iterations before breaking - made the number big in case massive number of bridges ...
Use `seen_bridges` because break/continue loop control is not available in Jinja2--
Jira: [OSP-22680](https://issues.redhat.com//browse/OSP-22680)

Automate OVN chassis MAC addres prefixes

---

roles/edpm_ssh_known_hosts/molecule/no_networks/molecule.yml
roles/edpm_ssh_known_hosts/molecule/no_networks/tests/test_no_networks.py

Provisioned host now has the same name in both scenarios. Tests were adjusted accordingly.

fixing no_networks scenario of edpm_ssh_known_hosts

---

molecule-requirements.txt
roles/edpm_iscsid/defaults/main.yml
roles/edpm_logrotate_crond/defaults/main.yml
roles/edpm_nova_compute/defaults/main.yml
roles/edpm_nova_libvirt/defaults/main.yml
roles/edpm_nova_libvirt/molecule/run_virtqemud/test_vars.yml
roles/edpm_ovn/defaults/main.yml

We imported container build tools from TripleO as TCIB[1]. Now we are retiring TripleO and should complete the migration.
[1] https://github.com/openstack-k8s-operators/tcib

Replace TripleO images by TCIB images

---

.github/playbooks/molecule-run.yml
.github/workflows/molecule.yaml

This change explicitly defines host and connection to be used by molecule test playbook. 
Furthermore, a superfluous task was removed from the playbook, as the podman is already installed during the previous action stages.

Setting molecule playbook to target localhost explictly

---

roles/edpm_iscsid/tasks/configure.yml
roles/edpm_tuned/tasks/configure.yml

We need root privileges for some of the configuration tasks.

Escalate privileges for edpdm_iscsid and edpm_tuned tasks

---

README.md

The README.rst file isn't included in docs we are building, so there is no need to keep the rst syntax.
Move to markdown will also allow us to include badges showing current CI status etc. as in #136

Turning README.rst into README.md

---

docs/source/conf.py

Eventually we will have to move away from ansible-autodoc, as it is no longer maintained and issues like this will only pile on. However this should enable us to build docs for the time being.

Mocking imported module to avoid ansible-autodoc import error

---

roles/edpm_chrony/tasks/sync.yml
roles/edpm_timezone/tasks/run.yml

Can't be run without sudo. Also does the same for some edpm_timezone role tasks that would require it.

chronyc makestep requires privilege escalation

---

roles/edpm_ovn/defaults/main.yml

when creating the ovs-vsctl set command, the bridge mappings should be a list without spaces, otherwise if you have more than one bridge mapping, the command will fail

Ensure bridge mappings do not have spaces

---

.pre-commit-config.yaml

check-byte-order-marker hook has been deprecated [0] in favor of the fix-byte-order-marker hook which fixes the issue in addtion to highlighting it.
[0] https://github.com/pre-commit/pre-commit-hooks/blob/main/CHANGELOG.md#330---2020-10-20w

Replacing check-byte-order-marker with fix-byte-order-marker hook

---

roles/edpm_bootstrap/meta/argument_specs.yml
roles/edpm_ceph_client_files/meta/argument_specs.yml
roles/edpm_chrony/meta/argument_specs.yml
roles/edpm_container_manage/meta/argument_specs.yml
roles/edpm_container_rm/meta/argument_specs.yml
roles/edpm_container_standalone/meta/argument_specs.yml
roles/edpm_frr/meta/argument_specs.yml
roles/edpm_growvols/meta/argument_specs.yml
roles/edpm_hosts_entries/meta/argument_specs.yml
roles/edpm_iscsid/meta/argument_specs.yml
roles/edpm_kernel/meta/argument_specs.yml
roles/edpm_logrotate_crond/meta/argument_specs.yml
roles/edpm_module_load/meta/argument_specs.yml
roles/edpm_network_config/meta/argument_specs.yml
roles/edpm_nftables/meta/argument_specs.yml
roles/edpm_nodes_validation/meta/argument_specs.yml
roles/edpm_nova_compute/meta/argument_specs.yml
roles/edpm_nova_libvirt/meta/argument_specs.yml
roles/edpm_nvdimm/meta/argument_specs.yml
roles/edpm_ovn/meta/argument_specs.yml
roles/edpm_ovn_bgp_agent/meta/argument_specs.yml
roles/edpm_podman/meta/argument_specs.yml
roles/edpm_ssh_known_hosts/meta/argument_specs.yml
roles/edpm_sshd/meta/argument_specs.yml
roles/edpm_timezone/meta/argument_specs.yml
roles/edpm_tuned/meta/argument_specs.yml
roles/env_data/meta/argument_specs.yml
roles/test_deps/meta/argument_specs.yml

Basic argument specs for our roles. In most cases they are left to be filled out later, although they are still possible to verify. In long run this should simplify maintenance, as we will, in effect, have a well defined interface for our roles.
Practical impact at this point is mostly with enabling antsibull-docs functionality.

Argspecs for edpm-ansible roles

---

plugins/filter/dict_to_list.yml
plugins/filter/haskey.yml
plugins/filter/needs_delete.yml

Our filter plugins don't have ansible compliant docs yet. That complicates things during the doc build process using antsibull-docs. These files will stand in for module attributes usually leveraged to define documentation of ansible plugins. 
This practice is comparable to the one employed by ansible core plugins[0].
[0] https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/to_json.yml

Basic documentation for our filters

---

roles/edpm_ovn_bgp_agent/templates/ovn-bgp-agent.conf.j2

There is a new driver for ovn-bgp-agent that uses NB instead of SB OVN DBs, thus it needs extra information/configuration to connect to NB in case of TLS being setup

Add NB DB certs config for ovn-bgp-agent NB driver

---

roles/edpm_module_load/meta/argument_specs.yml
roles/edpm_module_load/molecule/default/converge.yml
roles/edpm_module_load/molecule/remove_module/converge.yml
zuul.d/jobs.yaml
zuul.d/projects.yaml

Considering the divergent use in molecule and existing invocations of the role, I have settled on the `modules` being the only parameter of the role. The molecule tests will now be executed in zuul.
Closes: #104

`edpm_module_load` argspec definition and molecule tests

---

README.md

The guidelines offered by README.md for building and pushing an image were referring to environment variable IMG_BASE_TAG, which is not considered by the Makefile or the related scripts.
Following the guide would lead to unauthorized access exception upon push, since the default value of the IMAGE_TAG_BASE would be used instead.

Replacing IMG_BASE_TAG with IMAGE_TAG_BASE in README.md

---

zuul.d/jobs.yaml
zuul.d/projects.yaml

Zuul will now take care of molecule tests for the `edpm_kernel` role.
Closes: #103

Adding zuul job for `edpm_kernel` molecule tests

---

contribute/_skeleton_role_/meta/argument_specs.yml.j2

Minimal template for role argument specification [0]. By defining role interface we can cut down bugs caused by incorrect parameters. Furthermore, roles with args are easier to automatically document.
[0]https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#specification-format

Adding argument spec template to skeleton role

---

.github/workflows/molecule.yaml

Exceedingly minor change, but it should probably get in for future reference.

Explaining lack of tests for edpm_nova_libvirt role

---

roles/edpm_ovn/defaults/main.yml
roles/edpm_ovn/tasks/cleanup.yml
roles/edpm_ovn/tasks/configure.yml

The enable-chassis-as-gw is to enable the nodes to host ovn router gateway ports, not to enable/disable DVR [1].
This patch renames the option so that it is clear that is for making compute nodes able to host gw ports
[1] https://github.com/openstack-k8s-operators/neutron-operator/pull/153

Correct the enable-chassis-as-gw logic

---

roles/env_data/meta/argument_specs.yml
roles/env_data/meta/main.yml
roles/env_data/tasks/main.yml

env_data now has a proper meta/main.yml file.
Printing of repository and package information was split. Rather than using inline shell script the role now uses ansible module to obtain information about installed packages.
As an added value, the packages installed are now registered as a fact.
The new output of the installed packages section would be:
```
{'name': 'libgcc', 'version': '11.3.1', 'release': '2.1.el9', 'epoch': None, 'arch': 'x86_64', 'source': 'rpm'}
{'name': 'crypto-policies', 'version': '20220815', 'release': '1.git0fbe86f.el9', 'epoch': None, 'arch': 'noarch', 'source': 'rpm'}
{'name': 'tzdata', 'version': '2023c', 'release': '1.el9', 'epoch': None, 'arch': 'noarch', 'source': 'rpm'}
{'name': 'subscription-manager-rhsm-certificates', 'version': '20220623', 'release': …
```

Improving versatility of the env_data role

---

roles/edpm_bootstrap/defaults/main.yml
roles/edpm_bootstrap/molecule/default/converge.yml
roles/edpm_bootstrap/molecule/default/molecule.yml
roles/edpm_bootstrap/molecule/default/verify.yml
roles/edpm_bootstrap/tasks/bootstrap.yml

edpm_bootstrap_command is a variable for a shell command that will be
run early in the edpm_boostrap role tasks, before any package installs.
It can be used to register systems in order to enable package
repositories.

Add edpm_bootstrap_command

---

molecule/common/Containerfile.j2

The tripleo-repos are now installed in container generally, in contrary with the test_deps role. Template was generated and successfully tested in local CentOS9 container, and the installation of required repos was successfull.

Add tripleo-repos package to Containerfile.j2 template

---

.gitignore
requirements.yml
roles/edpm_bootstrap/defaults/main.yml
roles/edpm_network_config/defaults/main.yml
roles/edpm_network_config/molecule/nmstate/collections.yml
roles/edpm_network_config/molecule/nmstate/converge.yml
roles/edpm_network_config/molecule/nmstate/molecule.yml
roles/edpm_network_config/molecule/nmstate/prepare.yml
roles/edpm_network_config/tasks/main.yml
roles/edpm_network_config/tasks/network_config.yml
roles/edpm_network_config/tasks/os_net_config.yml

In the `edpm_config_network` role we have added the `edpm_network_config_role` variable that control the way how networking should be configured on edpm compute nodes.
The default value, `os-net-config`, will continue to configure the network with `os-net-config`.
Setting the value to `nmstate` the `network` role from linux-system-roles/rhel-system-roles will be used. This allow to configure interfaces using `nmstate` as its backend. See the [examples](https://nmstate.io/) on nmstate website to learn how to configure interfaces.
A short example is provided in molecule/nmstate scenario.

Refactored `edpm_config_network` role to support `linux-system-role.network` in place of `os-net-config`

---

roles/edpm_network_config/tasks/main.yml

The restart task is needed to avoid the error: 
```libnmstate.error.NmstateDependencyError: Manager(MissingPlugin):NetworkManager plugin for 'ovs-bridge' unavailable"```
despite the plugin is already installed.
The `systemrolename` fact gathering has been improved since an if/else conditional was redundant.

Added task to restart NM after plugin installation and improved `systemrolename` gathering

---

roles/edpm_bootstrap/defaults/main.yml
roles/edpm_bootstrap/tasks/bootstrap.yml

When nmstate is used, resolv.conf should be updated by NetworkManager.
Using this variable allows us to control this behaviour.

Add a boolean variable to control if NetworkManager should control resolv.conf update

---

roles/edpm_network_config/tasks/main.yml

It's not necessary and potentially dangerous to restart NetworkManager if it's not needed, so we will check the state of the dnf task to monitor if it's changed.
Also, the task name now explains what is going to be installed.

Restart NetworkManager only when needed and renamed task

---

ci/playbooks/build_runner_image.yaml

https://github.com/openstack-k8s-operators/install_yamls/pull/320 sets the openstack_runner_img for baremetal edpm deployment.
edpm-ansible baremetal edpm job builds the runner image. we can reuse the built runner image via make_edpm_compute_baremetal var.
It will help to test proper code in the CI.

Set make_edpm_compute_baremetal var

---

roles/edpm_nftables/tasks/configure.yml
roles/edpm_nftables/tasks/run.yml

Also:
* add owner/group/mode for each created file to improve security
* perform rules validation using privilege escalation otherwise ruleset files couldn't be read from standard user
This fix is needed since we are now executing `bootstrap`, `configure` and `run` steps in different ansible executions, so the variables (`nft_ruleset` in this case) aren't passed to next steps.

Added sentinel file to check if rules are changed so they can be applied

---

roles/edpm_bootstrap/defaults/main.yml
roles/edpm_bootstrap/molecule/default/prepare.yml
roles/edpm_bootstrap/tasks/bootstrap.yml
roles/edpm_bootstrap/tasks/swap.yml

Add swap partition management into the bootstrap role
The swap file/partition management logic is carried over from the existing EDPM pre-adoption implementation, but moved out of the nova compute specific scope into generic tasks for EDPM.
Depends-On: https://review.rdoproject.org/r/c/rdo-jobs/+/48683
Closes: [OSPRH-133](https://issues.redhat.com//browse/OSPRH-133)

Manage swap partition as a hard requirement

---

molecule-requirements.txt

Probably most of them were residues from the initial import.
The only packages required now are:
* `ansible-core` pinned to the version that we are using both on upstream and downstream
* `molecule` (last version compatibile with ansible version)
* `molecule-plugins` (last version compatible with molecule version)
* `jmespath` (required by molecule tests)
* `pytest-testinfra` (required by molecule tests)

Optimized the dependencies needed by molecule

---

scripts/test_roles.py

Several roles were added to the local test script skip list as their successful testing in local environment couldn't be guaranteed.

Multiple roles were added to the local test skip list

---

roles/edpm_bootstrap/defaults/main.yml
roles/edpm_bootstrap/tasks/swap.yml

* "swap" playbook has been refactored to avoid shell/command tasks when/if possible
* Swapfile default size has been reduced to 1Gb

Refactored swap Playbook in ansible style and changed swapfile default size

---

ci/playbooks/build_runner_image.yaml

With this commit, we set ansible runner image var for edpm_prepare role, so that in edpm_prepare we can Patch openstack-ansibleee-operator CSV with the correct image which we build in job.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/339
Depends-On: https://github.com/openstack-k8s-operators/edpm-ansible/pull/203
Depends-On: https://github.com/openstack-k8s-operators/dataplane-operator/pull/232

Set ansible runner image var for edpm_prepare role

---

scripts/molecule_venv.sh

Collection was built with python 3.9 in mind, however it is possible that when molecule tests are executed on a local machine other python versions may be used to create the venv.
This patch introduces a mechanism, which checks if the appropriate python version is present on the system, and if not prints a warning indicating that the default will be used instead.

Check if we have required python version available before running tests

---

roles/edpm_tuned/meta/argument_specs.yml
roles/edpm_tuned/molecule/isolated/converge.yml

Also adjusting the molecule test to better represent the role usage.
This change will not only improve documentation of the project, but also introduce additional check on types of role input.

Documenting main endpoint of the edpm_tuned role

---

ci/playbooks/build_runner_image.yaml

https://github.com/openstack-k8s-operators/ci-framework/pull/319 adds a role to update the env variables in any service operator.
Let's use the same to update it.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/364

Update ee runner image var using set_openstack_containers role

---

roles/edpm_ovn/defaults/main.yml

I think it should be the nodeName[1] and not fqdn. 
$$echo $(oc get pod ovn-controller-6l7t2 -o "jsonpath={.spec.nodeName}")
crc-8cf2w-master-0
[1] https://github.com/openstack-k8s-operators/ovn-operator/blob/main/pkg/ovncontroller/configjob.go#L68

Use ansible_hostname rather than fqdn for hostname

---

roles/edpm_podman/defaults/main.yml
roles/edpm_podman/tasks/buildah_login.yml
roles/edpm_podman/tasks/install.yml
roles/edpm_podman/templates/registries.conf.j2

edpm_buildah_package and edpm_podman_package were transformed from list to string variables
edpm_podman_insecure_registries was merged with edpm_container_registry_insecure_registries
edpm_podman_purge_packages var was removed, as it wasn't used by the role at all

Consolidating edpm_podman arguments

---

roles/edpm_ceph_client_files/defaults/main.yml
roles/edpm_chrony/README.rst
roles/edpm_chrony/defaults/main.yml
roles/edpm_container_manage/defaults/main.yml
roles/edpm_container_manage/meta/argument_specs.yml
roles/edpm_container_manage/molecule/default/converge.yml
roles/edpm_container_manage/tasks/create.yml
roles/edpm_container_manage/tasks/delete_orphan.yml
roles/edpm_container_manage/tasks/main.yml
roles/edpm_container_standalone/defaults/main.yml
roles/edpm_hosts_entries/defaults/main.yml
roles/edpm_logrotate_crond/defaults/main.yml
roles/edpm_logrotate_crond/molecule/default/converge.yml
roles/edpm_nodes_validation/defaults/main.yml
roles/edpm_podman/defaults/main.yml
roles/edpm_telemetry/tasks/deploy_ceilometer.yml

Many of our roles have debug arguments with no effect on the role behavior. These arguments are often set by referring to the ansible runtime verbosity level. In cases when these arguments are not used anywhere else in edpm_ansible collection or in the wider codebase, I believe it's safe to remove them.

Removing ununsed debug args

---

roles/edpm_network_config/templates/ci/extracted_crc_nic2_vlans.j2

With the new CI layout, having a dedicated nodeset for CRC alongside a
dedicated Compute, we need to get a dedicated network template file in
order to consume the right interface - eth1, aka nic2.
That "nic2" interface is associated to a private, dedicated network in
order to allow network isolation to proceed, exactly like late OVB jobs
in TripleO CI ecosystem.
This patch therefore adds a new "ci" dedicated template we can then
consume from within the ci-framework, ensuring we're using the correct
interface.
Note: this is hopefully a temporary workaround - the ansibleVars we
should use is, for now, a string, and we can't edit it with kustomize.
There's a plan to change its type, allowing proper edition of the
mapping.
Signed-off-by: Cédric Jeanneret <cjeanner@redhat.com>

Add new network template

---

docs/docs-requirements.txt

[Regression ](https://github.com/yaml/pyyaml/issues/601) in the pyyaml build caused by switch to incompatible cythton can potentially cripple our doc build.
This PR excludes affected versions of the pyyaml library so they can't be loaded as n-th order dependencies
Regresssion: https://github.com/yaml/pyyaml/issues/601 
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/398

Limiting pyyaml use in documentation build to stable versions

---

scripts/test_roles.py

It's almost useless to execute this test:
* it needs linux-firmware package installed (we can install it in a container but still...)
* it needs to load that module (we can mock that, but, again...)
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/398

Exclude edpm_ddp_package molecule test from being executed locally

---

roles/edpm_network_config/defaults/main.yml
roles/edpm_network_config/molecule/default/converge.yml
roles/edpm_network_config/tasks/os_net_config.yml

Given the current method of interacting with the network_config role, this change moves to using edpm_network_config_override when it's not an empty string. This will allow users to provide jinja2 data instead of json data. If this variable isn't defined, we will fall back to using the default template.

Use edpm_network_config_override when defined

---

roles/edpm_nodes_validation/defaults/main.yml
roles/edpm_nodes_validation/meta/argument_specs.yml

Also removes `edpm_nodes_validation_edpm_role_name` variable, which wasn't used by the role at all.

Setting argspecs for edpm_nodes_validation role

---

roles/edpm_container_standalone/defaults/main.yml
roles/edpm_container_standalone/meta/argument_specs.yml

The `edpm_container_standalone_hide_sensitive_logs` variable was removed as it has no effect on the role function.

Argument specs for edpm_container_standalone role

---

roles/edpm_ceph_client_files/defaults/main.yml
roles/edpm_ceph_client_files/meta/argument_specs.yml

The `edpm_ceph_client_files_hide_sensitive_logs` variable was removed as it wasn't used for anything.

Argspecs for edpm_ceph_client_files

---

roles/edpm_iscsid/defaults/main.yml
roles/edpm_iscsid/meta/argument_specs.yml

Patch also removes unused `edpm_iscsid_hide_sensitive_logs` variable.
The PR also removes MD5 from the list of approved hash algorithms.

Argspec for edpm_iscsid role

---

roles/edpm_bootstrap/tasks/bootstrap.yml
roles/edpm_bootstrap/tasks/packages.yml

It's pointless to continue to use the `package` module (which itself rely on an action plugin to be executed) since edpm-ansible only supports EL 8/9 targets.

Replace package module with dnf module

---

docs/source/contributing_roles.rst

If someone follows our current docs to create a new role the `molecule test` command doesn't work the first time. After asking around for a working example I learned that The `edpm_timezone` role has a working `molecule.yaml` file and that I should pass `molecule-requirements.txt` to `pip install`. After I did that my hello_world skeleton role worked with molecule. I'm committing this docs patch to save the next person the trouble.

Update docs on testing roles with molecule

---

roles/edpm_libvirt/molecule/default/prepare.yml
roles/edpm_nova/molecule/default/prepare.yml

pr #171 moved the test_deps role to the top level
molecule dir but the new edpm_nova and edpm_libvirt role
merged in parallel
This change simply modifies the test_deps role path to
match the new location.

update usage of test_deps in nova and libvirt roles

---

roles/edpm_kernel/tasks/main.yml

the orginal commit of edpm_kernel used the ansible.posix.sysctl modules
to set extra sysctl options in a loop. later pr #157
added the extra sysctl arg to the template and too the loop.
By adding edpm_kernel_sysctl_extra_settings to the template, pr #157
removed the need for the loop and usage of the ansible.posix.sysctl
module entirely. This change simply removes it and relys on the
exisitng systemd service restart to pick up the cahnge when the file
is updated.
Depends-On: #269 
Closes: #254

remove O(n*m) loop from edpm_kernel

---

roles/edpm_ovn/defaults/main.yml
roles/edpm_ovn/meta/argument_specs.yml

It was originally changed from ansible_fqdn
to ansible_hostname as part of [1] but that caused issues in environments where a fqdn is set as hostname.
We need to keep the ovn chassis hostname in sync with how nova-compute "host" config is set.
Nova "host" defaults to socket.gethostname() and to sync with it we need to use ansible_nodename as
ansible_hostname strips out domain part.
[1] https://github.com/openstack-k8s-operators/edpm-ansible/pull/211

Use ansible_nodename for ovn chassis hostname

---

docs/source/roles/role-edpm_ceph_hci_pre.rst
playbooks/ceph_hci_pre.yaml
roles/edpm_ceph_hci_pre/defaults/main.yml
roles/edpm_ceph_hci_pre/handlers/main.yml
roles/edpm_ceph_hci_pre/meta/argument_specs.yml
roles/edpm_ceph_hci_pre/meta/main.yml
roles/edpm_ceph_hci_pre/molecule/default/converge.yml
roles/edpm_ceph_hci_pre/molecule/default/molecule.yml
roles/edpm_ceph_hci_pre/molecule/default/prepare.yml
roles/edpm_ceph_hci_pre/molecule/default/verify.yml
roles/edpm_ceph_hci_pre/tasks/firewall.yml
roles/edpm_ceph_hci_pre/tasks/main.yml
roles/edpm_ceph_hci_pre/templates/firewall.yaml.j2
roles/edpm_ceph_hci_pre/vars/main.yml

The edpm_ceph_hci_pre role configures EDPM hosts so that they are ready for Ceph to be installed. For now this includes opening the firewall ports but the role has been named so that any other prerequisite configuration could be done.
Jira: [OSP-25827](https://issues.redhat.com//browse/OSP-25827)

Introduce edpm_ceph_hci_pre role

---

molecule-requirements.txt

Should prevent https://github.com/ansible/molecule/issues/4011

Pinning molecule to avoid testinfra removal

---

zuul.d/jobs.yaml

The file affects only molecule job so we don't have to run the whole deployment scenario.

Skip edpm jobs when molecule-requirements.txt is modified

---

roles/edpm_bootstrap/defaults/main.yml
roles/edpm_bootstrap/meta/argument_specs.yml

The command allows us to capture qdisc drop counter, which is useful for debugging packet loss problems.

Add tc command

---

roles/edpm_ceph_hci_pre/defaults/main.yml
roles/edpm_ceph_hci_pre/meta/argument_specs.yml
roles/edpm_ceph_hci_pre/molecule/default/converge.yml
roles/edpm_ceph_hci_pre/molecule/default/prepare.yml
roles/edpm_ceph_hci_pre/molecule/default/verify.yml
roles/edpm_ceph_hci_pre/tasks/firewall.yml
roles/edpm_ceph_hci_pre/templates/firewall.yaml.j2

If variables matching edpm_ceph_hci_pre_*_ranges are set to an empty list, then do not specify a source address in the NFT rule. For example the rule will look like this:
```
tcp dport { 3300, 6789 } ...
```
If the source address is specified, then the rule will look like this:
```
ip saddr 172.18.0.0/24 tcp dport { 3300, 6789 } ...
```
Prior to this patch, if someone wanted to not pass a source address they would need to add 0.0.0.0/0 to the list which is unintuitive. It is better to handle when there is no source address by not creating a rule with a source address.
TripleO does not specify a source IP address when defining Ceph rules in iptables. A line from /etc/sysconfig/iptables in Wallaby TripleO CI is below.
```
-A INPUT -p tcp -m tcp --dport 3300 -m conntrack \
--ctstate NEW -m …
```

Do not require a source address for ceph_hci_pre firewall

---

plugins/modules/edpm_os_net_config.py
roles/edpm_network_config/defaults/main.yml
roles/edpm_network_config/meta/argument_specs.yml

Each variable now has a type, default value and basic info.
Several variables were removed, as they are not used by the role.
Namely:
- edpm_network_config_with_ansible
Typo in the edpm_os_net_config module was fixed.

Full documentation for edpm_network_config role endpoint

---

playbooks/run_ovn_bgp_agent.yaml

Ensure the tasks is defined and imports the run role, instead of defining a role as this fails with:
Validating arguments against arg spec 'main' - The main entry point for
the edpm_ovn_bgp_agent role.] ***

Fix run_ovn_bgp_agent playbook definition

---

roles/edpm_podman/molecule/login/prepare.yml

I noticed a failure to pull the ubuntu image in CI. I'm not sure why we need Ubuntu and especially such an old release. Someone feel free to advise why it's necessary. This change is replacing the Ubuntu image with Fedora.

Replace Ubuntu with Fedora

---

playbooks/configure_os.yaml
playbooks/install_os.yaml
playbooks/run_os.yaml

ovn setup was split as part of [1], but missed as
part of playbook migration
[1] https://github.com/openstack-k8s-operators/dataplane-operator/commit/125ee8a99e

Remove ovn role include from os setup

---

roles/edpm_ceph_client_files/defaults/main.yml
roles/edpm_ceph_client_files/meta/argument_specs.yml
roles/edpm_libvirt/tasks/post-install.yml

On EDPM nodes Ceph client files were being stored in /etc/ceph. In an HCI scenario /etc/ceph could also host Ceph server files. To prevent any possible conflict store the client files in /var/lib/openstack/config/ceph. Inside the continers the path will remain /etc/ceph even though it changed on the host.
Jira: [OSP-27777](https://issues.redhat.com//browse/OSP-27777)

Store Ceph client files in /var/lib/openstack/config/ceph

---

roles/edpm_libvirt/molecule/default/prepare.yml
roles/edpm_libvirt/tasks/post-install.yml
roles/edpm_nova/molecule/default/prepare.yml

The post-install tasks file was calling the configure tasks in the edpm_nftables role to update the rules file in the /etc/nftables/ directory, but was not calling the run tasks to make the firewall reload the ruleset. This caused the output of `nft list ruleset` to not include the VNC rule which the edpm_libivirt role adds. Fix this by calling the run tasks file.
Jira: [OSP-27573](https://issues.redhat.com//browse/OSP-27573)

edpm_libivirt should reload NFT ruleset after configuring it

---

roles/edpm_network_config/templates/ci/extracted_crc_nic2_vlans.j2

This patch will ensure the compute is still reachable in the CI
ecosystem, since the default route should be on the public interface and
not touched.
Note: once we're able to switch to the multinode layout, we will refine
the job and leverage the proper networkConfig.template, allowing to
remove this file. But we can't run too many rabbits at the same time.

Don't override the compute routing

---

Makefile
plugins/modules/container_config_hash.py

Enabling FIPs enforces md5 never being used, so this module currently fails with FIPs.

Switch to sha256 for config hash

---

zuul.d/jobs.yaml
zuul.d/projects.yaml

This pr removes the old content provider and edpm job and uses the new content provider and standalone crc based edpm job.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/379

Use new content provider and standalone crc based edpm job

---

roles/edpm_kernel/tasks/reboot.yaml

Reboot task may fail due to the remote user being an unprivileged user
(non root) which is not able to perform a reboot.
By escalating the permissions in the task, the reboot task should pass.

edpm_kernel: Fix Reboot Task

---

docs/source/testing_roles.rst

Update the testing roles documentation with complete steps to build a new CentOS9 stream VM which can run local molecule tests as resquired by the edpm_libvirt and edpm_nova roles.

Document building an ephemeral VM for local molecule testing

---

roles/edpm_libvirt/defaults/main.yml
roles/edpm_libvirt/molecule/default/prepare.yml
roles/edpm_libvirt/molecule/default/test-helpers/verify_ceph_secret.yaml
roles/edpm_libvirt/molecule/default/verify.yml
roles/edpm_libvirt/tasks/post-install.yml
roles/edpm_libvirt/tasks/virsh-secret.yml
roles/edpm_libvirt/templates/libvirt_virtqemud/secret.xml.j2

Replace shell script with Ansible tasks. The shell script creates data structures, has an XML template, and executes commands. Bulild data structures in Ansible, use the template module, add a validation on cephx key value but also run commands where necessary. Aim is to make the Ansible logs easier to debug in the field.
Update edpm_libvirt molecule to test the new Ansible tasks. This includes generating mock data during prepare and confirming libvirt outputs the correct data during verify. Also, add whitespace to prepare.yml for readability.
Jira: [OSP-27777](https://issues.redhat.com//browse/OSP-27777)

Refactor Ceph libvirt secret management code

---

roles/edpm_iscsid/defaults/main.yml
roles/edpm_iscsid/meta/argument_specs.yml

This reverts commit 6b75cd6c89e9661c039d141cd970eee1f4304d70.
It's true that MD5 is not compatible with FIPS, but MD5 is required in non-FIPS deployments with older storage hardware. Allowing MD5 by default is consistent with tripleo based deployments, and will give storage providers time to certify their product works in FIPS environments where MD5 is prohibited. In addition, removing MD5 by default will need to be coordinated with corresponding changes in the controlplane.

Revert "Removing MD5 from the list of approved algos"

---

roles/edpm_ceph_hci_pre/defaults/main.yml

When `Ceph` `HCI` is deployed and the `Ceph` firewall rules are applied, we need to make sure that if `RGW` is deployed by the `orchestrator`, both backends and the related frontend are able to communicate.
`RGW` can be deployed at `day1` or as part of `day2` operations, and eventually it can be updated to use `TLS`.
By adding `radosgw` among the `enabled_services` list by default, we can make sure to not hit firewall related issues.
In `CI` we use the `Storage` network to reserve a `VIP` for this service, however, in a production environment, an administrator can choose to expose `RGW` using a `public network`. 
For this reason both 'ceph_rgw' and 'ceph_rgw_frontend' are added to the default list.

Add ceph_rgw and ceph_rgw_frontend in te list of enabled_services

---

roles/edpm_nova/molecule/default/test-data/nova-cell1/01-nova.conf
roles/edpm_nova/molecule/default/test-data/nova-cell1/02-nova-log.conf
roles/edpm_nova/molecule/default/verify.yml
roles/edpm_nova/templates/config.json.j2

This change relaxes the shell glob used by kolla_set_configs
to match which files shoudl be copied to "/etc/nova/nova.conf.d".
The new pattern will match "*nova*.conf" instead of "*nova.conf".
The molecule tests are expanded to assert tht the expected files
are copied to verify this change.

relax nova config patteren

---

plugins/filter/helpers.py
plugins/filter/jump_chain_targets.yml
roles/edpm_nftables/templates/jump-chain.j2
roles/edpm_podman/templates/podman_network_config.j2
roles/env_data/tasks/main.yml

We aren't going to be shipping required package, so we need to work around this. In most cases the query wasn't necessary in the first place. The exception being the jump targets template, in which case it was replaced by a specialized filter.
Note that the filter isn't general, it can not be, otherwise we would have to reimplement json query, or get another dependency. Neither of which is something we need or should pursue. Therefore, if there comes a time when the template is adjusted, the filter will need some changes as well.

Removing json_query calls

---

roles/edpm_podman/molecule/login/prepare.yml

We are hitting dockerhub rate limit while pulling registry:2.7.0 image from dockerhub. In order to avoid that, we use the mirrored RDO quay registry:2 image[1] to avoid such issues.
[1]. quay.rdoproject.org/openstack-k8s-operators/registry:2

Use RDO quay registry:2 image in podman molecule job

---

zuul.d/jobs.yaml
zuul.d/projects.yaml

https://github.com/openstack-k8s-operators/ci-framework/pull/534 adds the Zuul Project template for running content provider and edpm/baremetal jobs.
It will allow devs to update the job at one place and test anywhere. edpm-ansible-crc-podified-edpm-baremetal is the similar job of ci-framework-crc-podified-edpm-baremetal but different name.
Depends-On: https://github.com/openstack-k8s-operators/edpm-ansible/pull/326

Run EDPM job from podified-multinode-edpm-pipeline job template

---

roles/edpm_ceph_hci_pre/tasks/firewall.yml

Add `become: true` to tasks in firewall.yml from the role edpm_ceph_hci_pre since the move to using cloud-admin [1] exposed that we were relying on the role being run as root. When run as cloud-admin without become these tasks failed: [Errno 13] Permission denied: b'/var/lib/edpm-config/firewall'
[1] https://github.com/openstack-k8s-operators/install_yamls/pull/531

Role edpm_ceph_hci_pre needs become to update firewall

---

OWNERS
OWNERS_ALIASES
roles/edpm_ovn/OWNERS

Also, add slawqo to edpm_ovn role approvers. (This is the first subdir OWNERS file in this repo, let's see if it works...)

Set network approvers for the repo

---

.github/workflows/molecule.yaml
playbooks/neutron_sriov.yaml
roles/edpm_neutron_sriov/OWNERS
roles/edpm_neutron_sriov/defaults/main.yml
roles/edpm_neutron_sriov/handlers/main.yml
roles/edpm_neutron_sriov/meta/argument_specs.yml
roles/edpm_neutron_sriov/meta/main.yml
roles/edpm_neutron_sriov/molecule/default/collections.yml
roles/edpm_neutron_sriov/molecule/default/converge.yml
roles/edpm_neutron_sriov/molecule/default/molecule.yml
roles/edpm_neutron_sriov/molecule/default/prepare.yml
roles/edpm_neutron_sriov/molecule/default/verify.yml
roles/edpm_neutron_sriov/tasks/configure.yml
roles/edpm_neutron_sriov/tasks/install.yml
roles/edpm_neutron_sriov/tasks/main.yml
roles/edpm_neutron_sriov/tasks/run.yml
roles/edpm_neutron_sriov/templates/kolla_config/neutron_sriov_agent.yaml.j2
roles/edpm_neutron_sriov/templates/neutron-sriov-agent.ini.j2
roles/edpm_neutron_sriov/templates/neutron.conf.j2
roles/edpm_neutron_sriov/templates/neutron_sriov_agent.yaml.j2
roles/edpm_neutron_sriov/templates/rootwrap.conf.j2
roles/edpm_neutron_sriov/vars/main.yml

This new roles deploys, configures and runs neutron-sriov-agent on the EDPM node if needed.

Add edpm role to deploy Neutron SRIOV agent

---

roles/edpm_ceph_hci_pre/defaults/main.yml

When `ceph-nfs` is deployed as part of `Ceph` with an associated `ingress` daemon, we should provide firewall rules to avoid unexpected behavior when the cluster is created and clients try to reach the `VIP` endpoint.
Required for https://github.com/openstack-k8s-operators/ci-framework/pull/557

Add firewall rules for ceph-nfs

---

roles/edpm_network_config/defaults/main.yml
roles/edpm_network_config/meta/argument_specs.yml
roles/edpm_network_config/molecule/default/converge.yml
roles/edpm_network_config/tasks/os_net_config.yml

This change repurposes the edpm_network_config_override variable to accept a Jinja2 formatted string that will be rendered. This change will enable us to eventually replace the edpm_network_config_template variable and remove this override one entirely.

Repurpose network_config_override variable

---

roles/edpm_download_cache/defaults/main.yml
roles/edpm_download_cache/meta/argument_specs.yml
roles/edpm_download_cache/tasks/container_images.yml
roles/edpm_download_cache/tasks/main.yml
roles/edpm_download_cache/tasks/packages.yml

* splitted packages and container images downloads in two different files
* added `edpm_download_cache_packages` and `edpm_download_cache_container_images` variables to enable/disable download of packages and container images
* enabled the installation of `podman` via `edpm_podman` role since it's a requirement for `podman_image` module
* added tags in the tasks

Refactored `edpm_download_cache` role

---

playbooks/configure_network.yaml
roles/edpm_bootstrap/tasks/bootstrap.yml
roles/edpm_nova_libvirt/defaults/main.yml
roles/edpm_nova_libvirt/meta/argument_specs.yml
roles/edpm_nova_libvirt/tasks/install.yml
roles/edpm_users/defaults/main.yml
roles/edpm_users/handlers/main.yml
roles/edpm_users/meta/argument_specs.yml
roles/edpm_users/meta/main.yml
roles/edpm_users/molecule/default/converge.yml
roles/edpm_users/molecule/default/molecule.yml
roles/edpm_users/molecule/default/verify.yml
roles/edpm_users/tasks/create_users_and_groups.yml
roles/edpm_users/tasks/main.yml
roles/edpm_users/vars/main.yml

This change factors out the code to create users/groups that must
map to the same uid/gid within or outside of a container.
This is required to supprot ovs-dpdk where the hugepage and
vhost user socket permission must align to enabel ovs-dpdk
running on the host to comunciate with qemu running in a container.
Thsi work enabled the future removal of the edpm_nova_compute
and edpm_nova_libvirt roles.

extract host user,group and dir creation to edpm_users role

---

roles/edpm_sshd/tasks/install.yml

This PR is a followup of https://github.com/openstack-k8s-operators/edpm-ansible/pull/331 since I missed `package` usage... :man_facepalming:

Replace `package` module with `dnf` in `edpm_sshd` role

---

roles/edpm_network_config/defaults/main.yml
roles/edpm_network_config/meta/argument_specs.yml
roles/edpm_network_config/molecule/default/converge.yml
roles/edpm_network_config/tasks/os_net_config.yml

In an effort to keep things backwards compatible, this change duplicates the edpm_network_config_override functionality using the edpm_network_config_template variable. This change is necessary to prepare for the removal of the edpm_network_config_override variable.
This change keeps things backwards compatible and allows time to fix all of the workflows relying on the `_override` variable. Once they have all been changed over to use the new format of the `_template` variable, we can go ahead and remove the `_override` one.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/581

Rework network_config_template to accept j2

---

playbooks/configure_os.yaml
playbooks/install_os.yaml
playbooks/run_os.yaml
roles/edpm_multipathd/defaults/main.yml
roles/edpm_multipathd/files/custom_multipath.conf
roles/edpm_multipathd/files/multipath.conf
roles/edpm_multipathd/meta/argument_specs.yml
roles/edpm_multipathd/meta/main.yml
roles/edpm_multipathd/molecule/custom_config/converge.yml
roles/edpm_multipathd/molecule/custom_config/molecule.yml
roles/edpm_multipathd/molecule/custom_config/prepare.yml
roles/edpm_multipathd/molecule/custom_config/verify.yml
roles/edpm_multipathd/molecule/default/converge.yml
roles/edpm_multipathd/molecule/default/molecule.yml
roles/edpm_multipathd/molecule/default/prepare.yml
roles/edpm_multipathd/molecule/default/verify.yml
roles/edpm_multipathd/molecule/preexisting_config/converge.yml
roles/edpm_multipathd/molecule/preexisting_config/molecule.yml
roles/edpm_multipathd/molecule/preexisting_config/prepare.yml
roles/edpm_multipathd/molecule/preexisting_config/verify.yml
roles/edpm_multipathd/tasks/configure.yml
roles/edpm_multipathd/tasks/install.yml
roles/edpm_multipathd/tasks/main.yml
roles/edpm_multipathd/tasks/run.yml
roles/edpm_multipathd/templates/kolla_multipathd.yaml.j2
roles/edpm_multipathd/templates/multipathd.yaml.j2
roles/edpm_nova/molecule/default/prepare.yml
roles/edpm_nova/tasks/configure.yml
roles/edpm_nova/templates/nova_compute.json.j2

Add edpm_multipathd role to install, configure and run the multipathd daemon. Also configure nova-compute with the necessary volume mounts in order to interact with the multipath subsystem.
Jira: [OSP-26557](https://issues.redhat.com//browse/OSP-26557)

Add edpm_multipathd role

---

roles/edpm_libvirt/tasks/virsh-secret.yml

It's valid for the key inside a ceph keyring file to be either quoted or not quoted. Before this patch, if the key was quoted, then it was not passed to the "virsh secret-set-value" command because it did not satisfy the regex check because of the quotes. This change strips the quotes from the key value before it is checked and passed to the virsh command.

edpm_libvirt role should handle quoted cephx keys

---

docs/source/roles/role-edpm_container_manage.rst
roles/edpm_container_manage/tasks/delete_orphan.yml

If an HCI EDPM node has Ceph containers, then they should not be be manged by the edpm_container_manage role. Add a new task to exclude Ceph containers from the list of containers built by the call to
containers.podman.podman_container_info.
Without this new task, the edpm_container_manage role delete_orphan.yml tasks file attempts to process Ceph containers but it cannot handle them so it fails with an AttributeError: 'NoneType' object has no attribute 'get'.

Do not attempt to manage collocated Ceph containers

---

roles/edpm_neutron_sriov/defaults/main.yml
roles/edpm_neutron_sriov/meta/argument_specs.yml

In Neutron default value for the 'report_interval' option is set to 30 seconds and this works well for the typical deployments, together with the 'agent_down_time' option set on the neutron server side to 75 seconds by default.
In the neutron_sriov role default for the report_interval was previously set to 300 seconds which was causing agent flapping UP/DOWN.
This patch sets default value for this config option to 30 seconds which is the same as is used in Neutron.

Set correct default for SRIOV agent report_interval

---

roles/edpm_network_config/defaults/main.yml
roles/edpm_network_config/meta/argument_specs.yml
roles/edpm_network_config/molecule/default/converge.yml
roles/edpm_network_config/tasks/os_net_config.yml

This change removes the edpm_network_config_override variable. This functionality is exclusively provided via edpm_network_config_template.

Remove network_config_override variable

---

plugins/modules/edpm_container_manage.py

If we pattern match the config file we should also use config_override as an regexp so we will match the config from the pattern.
Change-Id: I33a5b4d9b6335ae07f84c4f9f0c7629ed6bd6180

edpm_container_manage treat override as regex

---

openstack_ansibleee/Dockerfile

During the build of the AnsibleEE runner image, if the collections are already installed (as it happens on github runners) they are never upgraded.
If a specific version of a collection is needed, it should be pinned in the `requirements.yml` file in the root of the repository.

Upgrade collection requirements during ansibleee runner build

---

plugins/modules/edpm_os_net_config.py

The default provider still remains as 'ifcfg' and when its not specified, the SR-IOV PF configuration is skipped. Adding the changes to support the same.

SR-IOV is not configured when the provider is not set

---

roles/edpm_container_manage/tasks/delete_orphan.yml

Patch 0e6058cc47c5f147a2338b41f07d6f8dd8bac5de resulted in a lot of output in the Ansible logs which made a CI job for the following PR get stuck. The output is unnecessary so do not log it in an attempt to relieve IO pressure.
https://github.com/openstack-k8s-operators/data-plane-adoption/pull/171

Do not log exclude Ceph containers from podman container list

---

playbooks/neutron_dhcp.yaml
roles/edpm_download_cache/tasks/container_images.yml
roles/edpm_neutron_dhcp/OWNERS
roles/edpm_neutron_dhcp/defaults/main.yml
roles/edpm_neutron_dhcp/handlers/main.yml
roles/edpm_neutron_dhcp/meta/argument_specs.yml
roles/edpm_neutron_dhcp/meta/main.yml
roles/edpm_neutron_dhcp/molecule/default/collections.yml
roles/edpm_neutron_dhcp/molecule/default/converge.yml
roles/edpm_neutron_dhcp/molecule/default/molecule.yml
roles/edpm_neutron_dhcp/molecule/default/prepare.yml
roles/edpm_neutron_dhcp/molecule/default/test-data/10-neutron-dhcp.conf
roles/edpm_neutron_dhcp/molecule/default/verify.yml
roles/edpm_neutron_dhcp/tasks/configure.yml
roles/edpm_neutron_dhcp/tasks/download_cache.yml
roles/edpm_neutron_dhcp/tasks/install.yml
roles/edpm_neutron_dhcp/tasks/main.yml
roles/edpm_neutron_dhcp/tasks/run.yml
roles/edpm_neutron_dhcp/templates/kolla_config/neutron_dhcp_agent.yaml.j2
roles/edpm_neutron_dhcp/templates/neutron-dhcp-agent.conf.j2
roles/edpm_neutron_dhcp/templates/neutron.conf.j2
roles/edpm_neutron_dhcp/templates/neutron_dhcp_agent.yaml.j2
roles/edpm_neutron_dhcp/templates/rootwrap.conf.j2
roles/edpm_neutron_dhcp/vars/main.yml

This new roles deploys, configures and runs neutron-dhcp-agent on the EDPM node if needed.
Jira: [OSP-27538](https://issues.redhat.com//browse/OSP-27538)

Add edpm role to deploy Neutron DHCP agent

---

roles/edpm_bootstrap/defaults/main.yml
roles/edpm_bootstrap/meta/argument_specs.yml

systemd-container is required to allow libvirt to manage cgroups
for qemu instance across container restarts.
Without systemd-container libvirt falls back to a legacy code
path where it directly manages cgroups without registering
vms in systemd-machined. This is nolonger tested by libvirt team
downstream and is known to cause issues with podman.
We solve this requirement by installing the package in the bootstrap
role to ensure its always installed on edpm hosts.

install systemd-containerd on all edpm hosts as part of bootstrap

---

docs/source/testing_roles.rst

The repo is renamed from current-podified-dev to current-podified
Close: #410

[doc]Fix repo setup command

---

roles/edpm_kernel/handlers/main.yml
roles/edpm_kernel/tasks/kernelargs.yml
roles/edpm_kernel/tasks/main.yml

- Added `Sysctl reload` as handler removing a `when` clause as for ansible best practice
- Replaced a `command` task with `slurp` module to get remote file content and `set_fact` task to define the `cmdline` variable
- Fixed indentation and spacing for better readability
- Moved jinja templating at the end of a task name
- Added `changed_when` and `failed_when` in command tasks
- Added a debug task to whitelist
- Declared permissions as strings in `mode` parameter as for ansible best practices

Make `edpm_kernel` compliant with ansible-lint `production` profile

---

roles/edpm_bootstrap/handlers/main.yml

This PR fixed a regression in `edpm_bootstrap` role generated by [this](https://github.com/openstack-k8s-operators/edpm-ansible/pull/391) PR since the both handlers tasks weren't executed as root.

Added missing `become:true` in `edpm_bootstrap` handlers tasks

---

roles/edpm_ssh_known_hosts/molecule/default/converge.yml
roles/edpm_ssh_known_hosts/molecule/default/tests/test_default.py
roles/edpm_ssh_known_hosts/tasks/main.yml

Originally the role only copied the RSA host keys to the generated known_hosts file. However newer ssh version prefer ED25519 over RSA. This resulted that even though the known_hosts file was present in the EDPM nodes when an SSH connection is initiated between the nodes the user is got prompted to accept the host key. This is against the purpose of the role.
So this PR adds support for ED25519 and ECDSA host keys as well while keep supporting RSA as well.

[edpm_ssh_known_hosts]Support multiple host key types

---

roles/edpm_module_load/tasks/main.yml

- Removed useless `"` from task names
- Changed `mode` to be a string

Make `edpm_modules_load` compliant with ansible-lint `production` profile

---

roles/edpm_ssh_known_hosts/molecule/default/tests/test_default.py
roles/edpm_ssh_known_hosts/molecule/no_networks/tests/test_no_networks.py
roles/edpm_ssh_known_hosts/tasks/main.yml

Originally the role generated hostnames in the known_hosts file with the
following pattern:
[edpm-compute-0]*,...
This pattern does not work as it does not match with the edpm-compute-0
hostname:
```
[root@edpm-compute-0 ~]# ssh edpm-compute-0
The authenticity of host 'edpm-compute-0 (192.168.122.100)' can't be established.
ED25519 key fingerprint is SHA256:ba66xyWDSkO0qv/9EATAZWT4NHhgDnScka4U7FIreaY.
This host key is known by the following other names/addresses:
/etc/ssh/ssh_known_hosts:4: [edpm-compute-0]*
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```
According to the ssh docs * and ? can be used for globbing. However []
can only be used for defining hosts with non default ssh port in the form
of [hostname]:portnumber. Based on my testing on EDPM nodes. The …

[edpm_ssh_known_hosts]Fix hostname pattern

---

roles/edpm_neutron_dhcp/defaults/main.yml
roles/edpm_neutron_dhcp/handlers/main.yml
roles/edpm_neutron_dhcp/tasks/configure.yml
roles/edpm_neutron_dhcp/tasks/install.yml

- Fixed `false` values in `defaults/main.yml`
- Capitalized first letter of task names
- Fixed indentation issues
- Define `mode` parameter as a string

Make `edpm_neutron_dhcp` role compliant with ansible-lint `production` profile

---

roles/edpm_libvirt/molecule/default/prepare.yml
roles/edpm_libvirt/molecule/default/verify.yml
roles/edpm_libvirt/tasks/install.yml
roles/edpm_libvirt/templates/libvirt_virtqemud/libvirt_virtqemud.json.j2
roles/edpm_nova/molecule/default/prepare.yml
roles/edpm_nova/molecule/default/verify.yml
roles/edpm_nova/templates/nova_compute.json.j2

This change modifies the ceph dir that is mounted
to the libvirt qemu and nova comptute contaienr
from /etc/ceph  to /var/lib/openstack/config/ceph

use correct ceph host dir for libvirt and nova

---

roles/edpm_neutron_sriov/handlers/main.yml
roles/edpm_neutron_sriov/tasks/configure.yml
roles/edpm_neutron_sriov/tasks/install.yml

- Capitalized first letter of the task names
- Fixed spacing issues
- Changed `yes` to `true`
- Fixed indentation
- Changed `mode` parameter to be a string

Make `edpm_neutron_sriov` role compliant with ansible-lint `production` profile

---

roles/edpm_network_config/tasks/main.yml
roles/edpm_network_config/tasks/network_config.yml

- Fixed spacing in jinja templating
- Added missing FQCN
- Replaced `'` with `"` in `mode` parameter to be compliant with other roles
- Added a couple of "when: $foo.changed" conditions in the linter whitelist (`no-handler`), since we can't create handlers and flush them because the role is executed in a playbook that contains a lot of roles.

Make `edpm_network_config` role compliant with ansible-lint `production` profile

---

roles/edpm_logrotate_crond/files/logrotate_crond.yaml
roles/edpm_logrotate_crond/meta/argument_specs.yml
roles/edpm_logrotate_crond/tasks/configure.yml

- Fixed indentation in yaml file
- Changed `mode` parameter to be a string
- Fixed spacing issues

Make `edpm_logrotate_crond` role compliant with ansible-lint `production` profile

---

roles/edpm_nodes_validation/tasks/ping.yml

- Added `changed_when`/`failed_when` in `shell` task
- Fixed spacing issues
- Fixed task name avoiding templating inside it

Make `edpm_nodes_validation` role compliant with ansible-lint `production` profile

---

docs/source/testing_with_ansibleee.rst

With the switch from `OpenStackDataPlaneNode` to `OpenStackDataPlaneNodeSet`, the `nodeTemplate` entry for `extraMounts` is no longer under `roles` and now under `spec` so update the example accordingly.

Update testing_with_ansibleee example for OpenStackDataPlaneNodeSet

---

roles/edpm_neutron_dhcp/tasks/install.yml

This directory may be created by libvirt role or neutron_dhcp role and it had wrong owner set (root) when was created by edpm_neutron_dhcp role. Because of that edpm_libvirt role which was run after edpm_neutron_dhcp was failing due to permission error to access /var/lib/openstack/config/ directory.

Fix owner of the /var/lib/openstack created by the neutron_dhcp role

---

roles/edpm_multipathd/tasks/install.yml

- Changed `service` to `services` in when clause

Fixed typo while using `ansible.builtin.service_facts` in `edpm_multipathd` role

---

roles/edpm_ovn_bgp_agent/meta/argument_specs.yml
roles/edpm_ovn_bgp_agent/meta/main.yml
roles/edpm_ovn_bgp_agent/tasks/configure.yml

- Fixed yaml indentation issues
- Added `set -o pipefail` in `shell` task
- Added `changed_when`/`failed_when` in shell task
- Replaced `ignore_errors: true` with `failed_when: false`
- Changed `'` to `"` in `mode` parameter to be coherent with the rest of the repo
Signed-off-by: Roberto Alfieri <ralfieri@redhat.com>

Make `edpm_ovn_bgp_agent` role compliant with ansible-lint `production` profile

---

roles/edpm_ssh_known_hosts/molecule/default/tests/test_default.py
roles/edpm_ssh_known_hosts/molecule/no_networks/tests/test_no_networks.py
roles/edpm_ssh_known_hosts/tasks/main.yml

The #422 removed all the name globbing as it was in the wrong place. Now this PR adds back globbing for hostname to support the case when hostname is not and fqdn during deployment but later and fqdn is used to ssh between nodes.

[edpm_ssh_known_hosts] Add back hostname globbing

---

roles/edpm_ovn/defaults/main.yml
roles/edpm_ovn/meta/argument_specs.yml
roles/edpm_ovn/tasks/cleanup.yml
roles/edpm_ovn/tasks/configure.yml
roles/edpm_ovn/tasks/firewall.yml

- Fixed yaml indentation issues
- Added `changed_when`/`failed_when` in `shell` tasks
- Replaced `ignore_errors: true` with `failed_when: false`
- Added FQCN where needed

Make `edpm_ovn` compliant with ansible-lint `production` profile

---

roles/edpm_podman/handlers/main.yml
roles/edpm_podman/meta/argument_specs.yml
roles/edpm_podman/tasks/buildah_login.yml
roles/edpm_podman/tasks/configure.yml
roles/edpm_podman/tasks/install.yml
roles/edpm_podman/tasks/login.yml
roles/edpm_podman/tasks/purge.yml
roles/edpm_podman/tasks/rsyslog.yml
roles/edpm_podman/tasks/rsyslog_cleanup.yml

- Fixed YAML indentation and spacing
- Added `changed_when`/`failed_when` in `command` and `shell` tasks
- Replaced `'` with `"` in `mode` parameter for coherence with the rest of the repo
- Changed `Clean podman images` from a block of tasks since we don't need the rescue task anymore
- Replaced `ignore_errors: true` with `failed_when: false`
- Replaced a task with an (existing) handler task
- Added `become: true` in handler task

Make `edpm_podman` role compliant with ansible-lint `production` profile

---

roles/edpm_nftables/files/00-base-rules.yaml
roles/edpm_nftables/tasks/cleanup.yml
roles/edpm_nftables/tasks/configure.yml
roles/edpm_nftables/tasks/run.yml
roles/edpm_nftables/tasks/service-bootstrap.yml

- fixed linting issues in `files/00-base-rules.yaml` file
- added `changed_when`/`failed_when` in `command`/`shell` tasks
- replaced `'` with `"` in `mode` parameter for coherence with the rest of the repo
- added `set -o pipefail` in `shell` tasks where needed
- replaced `ignore_errors: true` with `failed_when`
- replaced `systemctl` usage in `command` tasks with `service_facts` and `systemd` modules

Make `edpm_nftables` role compliant with ansible-lint `production` profile`

---

roles/edpm_nftables/tasks/service-bootstrap.yml

If the task is executed in environment without those services, it raise an error:
```
TASK [osp.edpm.edpm_nftables : Ensure legacy iptables services are off] ********
Friday 13 October 2023  08:23:44 +0000 (0:00:03.253)       0:00:15.801 ******** 
failed: [edpm-compute-0] (item=iptables.service) => {"ansible_loop_var": "item", "changed": false, "item": "iptables.service", "msg": "Could not find the requested service iptables.service: host"}
failed: [edpm-compute-1] (item=iptables.service) => {"ansible_loop_var": "item", "changed": false, "item": "iptables.service", "msg": "Could not find the requested service iptables.service: host"}
failed: [edpm-compute-1] (item=ip6tables.service) => {"ansible_loop_var": "item", "changed": false, "item": "ip6tables.service", "msg": "Could not find the …
```

Execute `Ensure legacy iptables services are off` task only if iptables and ip6tables services are present

---

roles/edpm_telemetry/tasks/deploy_ceilometer.yml

- Fixed spacing issue
- Declared dicts in loop using long form to avoid line > 160 characters

Make `edpm_telemetry` role compliant with ansible-lint `production` profile

---

roles/edpm_ssh_known_hosts/tasks/main.yml

Unfortunately nova still uses the IP of the compute nodes to scp data during cold migration instead of the hypervisor_hostname which is the FQDN of the compute node. So we need to make sure the ctlplane_ip of the node is also in the known_hosts file.

[edpm_ssh_known_hosts]Ensure host IP is added

---

roles/edpm_users/meta/argument_specs.yml
roles/edpm_users/tasks/create_users_and_groups.yml
roles/edpm_users/tasks/main.yml

- Fixed indentation issues
- Capitalized first letter in the task names
- Moved templating to the end of task names

Make `edpm_users` role compliant with ansible-lint `production` profile

---

roles/edpm_nova/molecule/default/verify.yml
roles/edpm_nova/tasks/configure.yml

This user will be used by nova-compute to copy data between compute nodes during migration.

[nova]Add nova user to the EDPM host

---

roles/edpm_ssh_known_hosts/molecule/default/molecule.yml
roles/edpm_ssh_known_hosts/molecule/default/tests/test_default.py
roles/edpm_ssh_known_hosts/tasks/main.yml

The logic that collected the name and IP of the host was referring to variables that are not defined in the EDPM inventory today. Those are probably old tripleo variables. So this patch removes the dead code.

[edpm_ssh_known_hosts]Cleanup unused code paths

---

roles/edpm_chrony/meta/main.yml
roles/edpm_network_config/tasks/main.yml
roles/edpm_network_config/tasks/network_config.yml
roles/edpm_ovn_bgp_agent/defaults/main.yml
roles/edpm_sshd/tasks/install.yml

This patch is a followup of the patches submitted for these roles. It fixes few YAML errors:
- `yaml[comments]: Too few spaces before comment`
- `yaml[document-start]: Missing document start "---"`
- `yaml[comments-indentation]: Comment not indented like content`

Fix trivial YAML errors in several roles

---

roles/edpm_ssh_known_hosts/molecule/default/tests/test_default.py

By merging #448 after #449 caused that the molecule test is now failing on main. Separately the two PRs wer doing the correct thing. The github action doing the pre-merge testing does not do a rebase before running the test so it cannot detect if the merged in PR fails the test.
This PR fixing the molecule test.
[1] https://github.com/openstack-k8s-operators/edpm-ansible/pull/448/files#diff-654bc2164f880d6ff16c6009ecd64121cac7d59497ada186aab1ffded0a466b8

[molecule]Fix known_hosts molecule test

---

roles/edpm_ssh_known_hosts/tasks/main.yml

- Fixed indentation under `tags`
- Added `changed_when`/`failed_when` in `shell` task

Make `edpm_ssh_known_hosts` role compliant with ansible-lint `production` profile

---

roles/edpm_iscsid/handlers/main.yml
roles/edpm_iscsid/tasks/configure.yml
roles/edpm_iscsid/tasks/install.yml

- Fixed a couple of checks against boolean using a more "ansible" way
- Added "mode" in `file` and `copy` tasks to hardening security
- Replaced the use of `podman run` inside `command` tasks with `podman_container` module from `containers.podman` collection
- Implemented an handler task instead of a standard task with a `when: $foo.changed` condition as for ansible best practices
- Replaced `systemctl` usage inside a `command` module with `ansible.builtin.service_facts` module and adapted `when` conditions for systemd task
- Fixed the indentation of the tasks under `block`

Make `edpm_iscsid` role compliant with ansible-lint `production` profile

---

.ansible-lint

- Populated `exclude_path` to exclude path that shouldn't be checked by ansible-lint
- Added `command-instead-of-shell` rule to the `skip_list`
This PR need that all the roles and playbooks will be adapted to the `production` profile.

Enforce `production` profile in ansible-lint

---

.ansible-lint

Since we are on version 0.0.1, that check fails because it expects at least a `1.x.x` version despite in the official documentation [1] the only requirement is to be compliant with semantic versioning.
[1] https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

Add `galaxy[version-incorrect]` to ansible-lint skip-list

---

.pre-commit-config.yaml

- `ansible-lint` version bump to `v6.20.3` to enforce all the needed checks for "modern" ansible development
- `ansible-core` version pinned to version `>=2.14.0,<2.15.0` which is the version that we are using on our ansibleee runner
- changed the url of the ansible-lint tool since the old link was a redirect
Depends-On: https://github.com/openstack-k8s-operators/edpm-ansible/pull/459

Version bump `ansible-lint` to `v6.20.3` and enforce `ansible-core` version requirement

---

roles/edpm_nova/molecule/default/prepare.yml
roles/edpm_nova/molecule/default/test-data/migration-key/ssh-privatekey
roles/edpm_nova/molecule/default/test-data/migration-key/ssh-publickey
roles/edpm_nova/molecule/default/verify.yml
roles/edpm_nova/tasks/configure.yml
roles/edpm_nova/templates/config.json.j2
roles/edpm_nova/templates/nova_compute.json.j2
roles/edpm_nova/templates/ssh-config

The nova user needs to be able to copy files between the compute nodes.
The edpm_nova role now expects that a Secret is mounted to the AnsibleEE
CR containing an ssh keypair (ssh-privatekey and ssh-publickey). This
keypair is used to set up the auth for the nova user between the
compute nodes. On the EDPM host the nova user will have the public key
added as authorized_keys. While the nova user in the nova-compute
container will have the private key added as identity in
/var/lib/nova/.ssh. Also an ssh config file is added in the container to
ensure that this identity is used for all the outgoing ssh connection.
Depends-On: https://github.com/openstack-k8s-operators/dataplane-operator/pull/471

[nova]Set up ssh keys auth for the nova user 

---

.github/workflows/molecule.yaml
playbooks/neutron_ovn.yaml
roles/edpm_download_cache/tasks/container_images.yml
roles/edpm_neutron_ovn/OWNERS
roles/edpm_neutron_ovn/defaults/main.yml
roles/edpm_neutron_ovn/meta/argument_specs.yml
roles/edpm_neutron_ovn/meta/main.yml
roles/edpm_neutron_ovn/molecule/default/collections.yml
roles/edpm_neutron_ovn/molecule/default/converge.yml
roles/edpm_neutron_ovn/molecule/default/molecule.yml
roles/edpm_neutron_ovn/molecule/default/prepare.yml
roles/edpm_neutron_ovn/molecule/default/test-data/10-neutron-ovn.conf
roles/edpm_neutron_ovn/molecule/default/verify.yml
roles/edpm_neutron_ovn/tasks/bootstrap.yml
roles/edpm_neutron_ovn/tasks/configure.yml
roles/edpm_neutron_ovn/tasks/download_cache.yml
roles/edpm_neutron_ovn/tasks/install.yml
roles/edpm_neutron_ovn/tasks/main.yml
roles/edpm_neutron_ovn/tasks/run.yml
roles/edpm_neutron_ovn/templates/kolla_ovn_agent.yaml.j2
roles/edpm_neutron_ovn/templates/neutron-ovn-agent.conf.j2
roles/edpm_neutron_ovn/templates/ovn_agent.yaml.j2
roles/edpm_neutron_ovn/templates/rootwrap.conf.j2

This agent is used to provide QoS to hardware offloaded ports on the compute nodes.
Related-Issue: [OSP-26191](https://issues.redhat.com//browse/OSP-26191)

Add role to setup neutron ovn agent

---

roles/edpm_neutron_dhcp/tasks/install.yml

The `ansible_user` variable is not alway set to a sensible default, and may in fact be undefined. By running a lookup on the target host we can effectivelly avoid the problem.
Discovered during #472

Setting default value of the user

---

roles/edpm_libvirt/molecule/default/verify.yml
roles/edpm_libvirt/tasks/main.yml
roles/edpm_libvirt/tasks/user.yml

This is needed for two reasons:
1) to eventually add the nova user to the libvirt group on the host so
that the incoming live migration connections can access the libvirt
socket
2) to allow libvirt to be de-containerized in https://github.com/openstack-k8s-operators/edpm-ansible/pull/467 while keeping the ui and guid
of the libvirt user unchanged

[edpm_libvirt]Add libvirt user to the EDPM host

---

roles/edpm_nova/molecule/default/verify.yml
roles/edpm_nova/tasks/configure.yml

During live migration libvirt initiates an ssh connection from the
source compute to the dest compute with the nova user to pipe the guest
memory content to the destination node. So the nova user needs to have
access to the libvirt socket on the host.

[edpm_nova]Add nova user to libvirt group

---

roles/edpm_network_config/molecule/default/converge.yml

Since the molecule test will be executed in a container, we can't configure an ovs bridge on top of a dummy interface or a tap interface. 
The scope of this test isn't to provide a "working" EDPM scenario example, so we are going to provide a sample os-net-config configuration which works in a container on top of a dummy interface.
To add some context, at the moment the test will run successfully but it won't give the expected results. As you can see in the snippet below, os-net-config doesn't find an *active* interface to apply its configuration (nor the `tap0` interface or the created `dummy0` interface are available as ovs-bridge members), so the command run with rc 0, but it doesn't touch the network configuration, giving an unreliable result.
```
[root@instance /]# os-net-config …
```

Fix molecule `default` scenario for `edpm_network_config` role

---

roles/edpm_ovn/defaults/main.yml
roles/edpm_ovn/meta/argument_specs.yml
roles/edpm_ovn/tasks/configure.yml

ovn-controller does it automatically since 21.09.0 [1].
https://github.com/ovn-org/ovn/commit/7e2c892c380aeddc4bbc9ceb5e759ee9ac62176d

ovn: don't explicitly set vlan-limit=0

---

roles/edpm_neutron_dhcp/defaults/main.yml
roles/edpm_neutron_dhcp/meta/argument_specs.yml
roles/edpm_neutron_metadata/defaults/main.yml
roles/edpm_neutron_metadata/meta/argument_specs.yml

With [1] merged, it requires shared mount
between ovn_metadata_agent and haproxy containers.
Also use variable instead of hardcoded /var/lib/neutron in neutron_dhcp_agent role.
[1] https://github.com/openstack-k8s-operators/edpm-ansible/pull/394

[neutron_metadata] Add missing mount

---

roles/edpm_network_config/molecule/default/prepare.yml
roles/edpm_network_config/molecule/nmstate/converge.yml
roles/edpm_network_config/tasks/main.yml

* Fixed `nmstate` molecule scenario for `edpm_network_config` role

Add templating support for nmstate defined networking configuration

---

roles/edpm_neutron_dhcp/defaults/main.yml
roles/edpm_neutron_dhcp/meta/argument_specs.yml
roles/edpm_neutron_metadata/defaults/main.yml
roles/edpm_neutron_metadata/meta/argument_specs.yml
roles/edpm_neutron_ovn/defaults/main.yml
roles/edpm_neutron_ovn/meta/argument_specs.yml
roles/edpm_neutron_sriov/defaults/main.yml
roles/edpm_neutron_sriov/meta/argument_specs.yml

The directory doesn't exist, and we move the filter files under /usr/share/neutron/rootwrap in rpms. See:
https://github.com/rdo-packages/neutron-distgit/blob/antelope-rdo/openstack-neutron.spec#L499

ovn: remove rootwrap.d from the list of filters_path

---

roles/edpm_frr/molecule/default/prepare.yml
roles/edpm_neutron_dhcp/molecule/default/prepare.yml
roles/edpm_neutron_metadata/molecule/default/prepare.yml
roles/edpm_neutron_ovn/molecule/default/prepare.yml
roles/edpm_neutron_sriov/molecule/default/prepare.yml
roles/edpm_ovn/molecule/default/prepare.yml
roles/edpm_ovn/molecule/noconfig/prepare.yml

There's a regression in crun 1.11.1 (see https://github.com/containers/crun/issues/1338) that prevents podman to being executed on podman containers in some molecule scenario.
We are downgrade crun to last known version (1.10.1) until the new package will arrive in Centos 9 Stream.

Added downgrade of crun in molecule scenario where podman is needed

---

roles/edpm_nova/molecule/default/molecule.yml
roles/edpm_nova/molecule/default/verify.yml
roles/edpm_nova/tasks/configure.yml
roles/edpm_nova/templates/02-nova-host-specific.conf.j2

This is needed as nova-compute, if my_ip is not configured, tries to figure out its own IP address in complicated way and in a system with multiple network interfaces there is no guarantee that it selects the IP of the designated control plane interface.
The my_ip configuration is EDPM node specific so it cannot be generated globally for a cell in nova-operator. So this is generated by ansible now.
There is an upstream nova blueprint to eventually get rid of the need of this configuration: https://blueprints.launchpad.net/nova/+spec/libvirt-migrate-with-hostname-instead-of-ip

[edpm_nova]Configure my_ip to ctlplane_ip for nova-compute

---

roles/edpm_ovn/defaults/main.yml
roles/edpm_ovn/meta/argument_specs.yml

The knob is useless for unix socket connection to vswitchd.
It is now removed in OVN [1], which makes it even more useless.
[1] https://github.com/ovn-org/ovn/commit/c16e5da803838fa66129eb61d7930fc84d237f85

ovn: remove ovn-openflow-probe-interval knob

---

openstack_ansibleee/Dockerfile
playbooks/install_os.yml
roles/edpm_network_config/tasks/main.yml

In order to avoid the dynamic building of the system roles collection name based on the runner where is running (Fedora or RHEL), which is complicated and potentially slow, we define an environment variable during the container building so we can gather it with a lookup during the execution of playbooks.

Add `EDPM_SYSTEMROLES` env var in ansibleee runner image

---

scripts/molecule_venv.sh

- used versioned `python3` command instead of unversioned `python`
- added a check for the presence of the python development libraries and their installation in case of rpm based distro

Improved the robustness of `molecule_venv.sh` script

---

roles/edpm_bootstrap/defaults/main.yml
roles/edpm_bootstrap/meta/argument_specs.yml
roles/edpm_bootstrap/tasks/bootstrap.yml
roles/edpm_bootstrap/tasks/bootstrap_command.yml
roles/edpm_download_cache/tasks/install.yml

Since the registration of the EL nodes is performed during the `edpm_bootstrap_command` task in the `edpm_bootstrap` role, we moved that task into a new task file called `bootstrap_command.yml` so it can be called by the `edpm_download_cache` role without invoking the entire role. We also added a marker that will avoid to execute the task twice if it's been already executed.

Execute `edpm_bootstrap_command` during `download_cache`

---

roles/edpm_network_config/defaults/main.yml
roles/edpm_network_config/templates/2_linux_bonds_vlans/2_linux_bonds_vlans.j2
roles/edpm_network_config/templates/2_linux_bonds_vlans/2_linux_bonds_vlans_dpdk.j2
roles/edpm_network_config/templates/bonds_vlans/bonds_vlans.j2
roles/edpm_network_config/templates/bonds_vlans/bonds_vlans_storage.j2
roles/edpm_network_config/templates/bonds_vlans/controller_no_external.j2
roles/edpm_network_config/templates/ci/custom_network_multiple_nics.j2
roles/edpm_network_config/templates/ci/multiple_nics.j2
roles/edpm_network_config/templates/ci/multiple_nics_ipv6.j2
roles/edpm_network_config/templates/ci/public_bond.j2
roles/edpm_network_config/templates/multiple_nics/multiple_nics.j2
roles/edpm_network_config/templates/multiple_nics/multiple_nics_dpdk.j2
roles/edpm_network_config/templates/multiple_nics/multiple_nics_dvr.j2
roles/edpm_network_config/templates/multiple_nics_vlans/multiple_nics_vlans.j2
roles/edpm_network_config/templates/multiple_nics_vlans/multiple_nics_vlans_dpdk.j2
roles/edpm_network_config/templates/multiple_nics_vlans/multiple_nics_vlans_dvr.j2
roles/edpm_network_config/templates/net_config_bond.j2
roles/edpm_network_config/templates/net_config_bridge.j2
roles/edpm_network_config/templates/net_config_static.j2
roles/edpm_network_config/templates/net_config_static_bridge.j2
roles/edpm_network_config/templates/net_config_static_bridge_with_external_dhcp.j2
roles/edpm_network_config/templates/single_nic_vlans/controller_no_external.j2
roles/edpm_network_config/templates/single_nic_vlans/single_nic_vlans.j2
roles/edpm_network_config/templates/single_nic_vlans/single_nic_vlans_bgp.j2
roles/edpm_network_config/templates/single_nic_vlans/single_nic_vlans_storage.j2
roles/edpm_network_config/templates/standalone.j2
roles/edpm_network_config/templates/undercloud.j2

This change renames the `dns_search_domains` variable in-line with the variable naming convention of the repo. We then set a default value for this variable.

Update dns_search_domains and add default

---

playbooks/telemetry.yml
playbooks/telemetry_logging.yml
roles/edpm_network_config/tasks/main.yml

- Fixed order of keywords in `telemetry` and `telemetry_logging` playbooks
- Removed extra white space in a role name in `edpm_network_config` role
This is required by newer versions of `ansible-lint` because they have improved checks.

Fixed linting issues in playbooks and task files

---

roles/edpm_nova/defaults/main.yml
roles/edpm_nova/meta/argument_specs.yml
roles/edpm_nova/tasks/configure.yml
roles/edpm_nova/templates/nova_compute.json.j2

The dataplane operator will provide certs and keys to the ansibleEE pod in /var/lib/openstack/certs as well as a cacert file in /var/lib/openstack/cacerts.  It will also pass an ansible variable tls_certs_enabled to indicate that the certs are present.
This PR copies these files to the appropriate place on the compute node and then mounts these files in the nova-compute container.
We still need to confirm that these files are in the right location in the container and add config to use these certs - as well as code to trust the cacert.  Will need help from compute DFG for that.

Mount TLS certs

---

roles/edpm_neutron_metadata/defaults/main.yml
roles/edpm_neutron_metadata/templates/neutron-ovn-metadata-agent.conf.j2

Some metadata agent config options are usually provided by the nova and ovn operators and are set in separate config files.
To avoid confusion with empty values in the main config file used by the neutron-ovn-metadata-agent, those options will be set there only if the are provided in the role's parameters.

Set some neutron-ovn-metadata agent options only if necessary

---

roles/edpm_ovn/defaults/main.yml
roles/edpm_ovn/meta/argument_specs.yml
roles/edpm_ovn/molecule/default/molecule.yml
roles/edpm_ovn/molecule/default/verify.yml
roles/edpm_ovn/molecule/enable_chassis_extport/cleanup.yml
roles/edpm_ovn/molecule/enable_chassis_extport/collections.yml
roles/edpm_ovn/molecule/enable_chassis_extport/converge.yml
roles/edpm_ovn/molecule/enable_chassis_extport/molecule.yml
roles/edpm_ovn/molecule/enable_chassis_extport/prepare.yml
roles/edpm_ovn/molecule/enable_chassis_extport/test-data
roles/edpm_ovn/molecule/enable_chassis_extport/verify.yml
roles/edpm_ovn/molecule/enable_chassis_gw/cleanup.yml
roles/edpm_ovn/molecule/enable_chassis_gw/collections.yml
roles/edpm_ovn/molecule/enable_chassis_gw/converge.yml
roles/edpm_ovn/molecule/enable_chassis_gw/molecule.yml
roles/edpm_ovn/molecule/enable_chassis_gw/prepare.yml
roles/edpm_ovn/molecule/enable_chassis_gw/test-data
roles/edpm_ovn/molecule/enable_chassis_gw/verify.yml
roles/edpm_ovn/molecule/enable_chassis_gw_and_extport/cleanup.yml
roles/edpm_ovn/molecule/enable_chassis_gw_and_extport/collections.yml
roles/edpm_ovn/molecule/enable_chassis_gw_and_extport/converge.yml
roles/edpm_ovn/molecule/enable_chassis_gw_and_extport/molecule.yml
roles/edpm_ovn/molecule/enable_chassis_gw_and_extport/prepare.yml
roles/edpm_ovn/molecule/enable_chassis_gw_and_extport/test-data
roles/edpm_ovn/molecule/enable_chassis_gw_and_extport/verify.yml
roles/edpm_ovn/tasks/cleanup.yml
roles/edpm_ovn/tasks/configure.yml

This patch allows for configuring a Chassis as a host for external ports. This feature was introduced in ML2/OVN by https://review.opendev.org/c/openstack/neutron/+/894767.
This patch creates a new configuration for edpm_ovn called "edpm_enable_chassis_extport" which when enabled sets the "enable-chassis-as-extport-host" to the OVN CMS Options.

[ovn] Chassis as external port host edpm config

---

roles/edpm_bootstrap/tasks/download_cache.yml
roles/edpm_bootstrap/tasks/update_package.yml

In baremetal EDPM job, we use EDPM image to create EDPM node. it has all the required packages pre-installed during image build process.
If an older version of package got included during the image build process.  Then during edpm_deploy, bootstrap role is not going to update the package to latest.
Performing a dnf update will update all the system packages and avoid such issues.

Peform DNF update on edpm node via bootstrap_role

---

roles/edpm_neutron_dhcp/molecule/default/molecule.yml
roles/edpm_neutron_metadata/molecule/default/molecule.yml
roles/edpm_telemetry/molecule/default/molecule.yml

Running the scenarios with root user fails with
this config, it works fine without this option set. So let's drop it as it's not necessary like other
molecule podman scenarios.

[molecule][podman] Drop remote_tmp config_options

---

roles/edpm_libvirt/molecule/default/verify.yml

virtlogd is now reported as enabled not indirect
this change updates the molecule tests to reflect that

update virtlogd enabeld check

---

.ansible-lint
.yamllint
molecule-requirements.txt
roles/edpm_libvirt/molecule/default/molecule.yml
roles/edpm_libvirt/molecule/vagrant/README.md
roles/edpm_libvirt/molecule/vagrant/molecule.yml
roles/edpm_libvirt/molecule/vagrant/verify.yml
roles/edpm_nova/molecule/default/converge.yml
roles/edpm_nova/molecule/default/molecule.yml
roles/edpm_nova/molecule/default/verify.yml
roles/edpm_nova/molecule/vagrant/README.md
roles/edpm_nova/molecule/vagrant/molecule.yml
roles/edpm_nova/molecule/vagrant/verify.yml

The libvirt and nova roles currently uses the delegated driver
which runs molecule against localhost. This is required for
ci as the podman driver cannot be used with this role however
it also means you must use a separate development vm.
This change readds support for using the molecule vagrant plugin
for this role and configures the vagrant scenario to use the
prepare, converge and verify playbooks from the default delegated
scenario.
Additionally this change updates yamllint and ansible-lint to not
scan files in a venv i.e. .venv in the root of the edpm-ansible
repo. .venv is already ignored by .gitignore so this also only
affects local development.

add optional vagrant senairo for local testing and development.

---

roles/edpm_libvirt/defaults/main.yml
roles/edpm_libvirt/meta/argument_specs.yml
roles/edpm_libvirt/tasks/configure.yml

This follows the same logic as for the nova compute certs.
It does not include any config changes to actually use the certs.  I'm expecting the compute DFG folks will add this logic.

Add libvirt certs

---

.github/workflows/molecule.yaml
playbooks/reboot.yml
roles/edpm_kernel/meta/argument_specs.yml
roles/edpm_kernel/tasks/reboot.yaml
roles/edpm_reboot/defaults/main.yaml
roles/edpm_reboot/meta/argument_specs.yml
roles/edpm_reboot/meta/main.yaml
roles/edpm_reboot/molecule/default/converge.yml
roles/edpm_reboot/molecule/default/molecule.yml
roles/edpm_reboot/molecule/default/prepare.yml
roles/edpm_reboot/tasks/main.yaml
roles/edpm_reboot/tasks/reboot.yaml

There are steps in EDPM deployment and re-configuration that require
EDPM node reboot to take effect. Also reboot might be required due to
package updates.
This role runs need-restarting command and checks if any file exists
under /var/lib/openstack/reboot_required. If reboot is required and there
are no nova configuration files reboot is performed.
When nova files exist on a node reboot is performed only when
edpm_reboot_force_reboot is set to true.

Add role to run node reboot

---

.github/workflows/documentation.yaml
.gitignore
docs/Gemfile
docs/build-docs.sh
docs/source/main.adoc

Putting infrastructure in place for future move to asciidocs. At this time we only have the build itself and an empty index page, until there is a procedure to convert existing documentation, or part of it, to asciidocs.

Asciidocs build procedure

---

docs/source/playbooks/install_certs.rst
docs/source/roles/role-edpm_install_certs.rst
playbooks/install_certs.yml
roles/edpm_install_certs/meta/argument_specs.yml
roles/edpm_install_certs/meta/main.yml
roles/edpm_install_certs/tasks/copy_ca_certs.yaml
roles/edpm_install_certs/tasks/copy_certs_and_keys.yaml
roles/edpm_install_certs/tasks/main.yml
roles/edpm_libvirt/defaults/main.yml
roles/edpm_libvirt/meta/argument_specs.yml
roles/edpm_libvirt/tasks/configure.yml
roles/edpm_nova/defaults/main.yml
roles/edpm_nova/meta/argument_specs.yml
roles/edpm_nova/tasks/configure.yml
roles/edpm_nova/templates/nova_compute.json.j2

This is a role that moves certs into the right locations for all the services.  This is executed by a service early in the cycle, so that the services can have all the certs available.  So nova, for example, will be able to use the libvirt certs.

Add role edpm_install_certs

---

roles/edpm_ovn/defaults/main.yml
roles/edpm_ovn/meta/argument_specs.yml

We really don't need to expose all of these. In many cases we were essentially setting customer up for configuration conflicts if they were to supply different values in multiple ways. This way we have much cleaner interface.

OVN role arguments refactor

---

roles/edpm_nova/molecule/default/verify.yml
roles/edpm_nova/tasks/configure.yml

Use the nova stable compute uuid feature.
* In greenfield pre-generate compute_id before the first start of the nova-compute service
* During adoption of old deployment preserve the compute_id if exists but make it ready only
Depends-on: https://github.com/openstack-k8s-operators/data-plane-adoption/pull/223
Implements: https://issues.redhat.com/browse/OSPRH-117

[edpm_nova]Pre-generate compute_id

---

roles/edpm_kernel/molecule/kernelargs-update-substring/converge.yml
roles/edpm_kernel/molecule/kernelargs-update-substring/molecule.yml
roles/edpm_kernel/molecule/kernelargs-update-substring/verify.yml
roles/edpm_kernel/tasks/kernelargs.yml

In kernelargs.yml file we have a block of tasks for the definitions of custom kernel arguments. That block has 3 conditionals checks, one of them is the evaluation of kernel parameters defined in /proc/cmdline using the `edpm_kernel_args not in cmdline` notation. The problem is that this kind of notation will evaluate also partial matches.
E.g. if we first launch a deployment defining
```
edpm_kernel_args="isolcpus=1,3,5,7,9,11,13,15"
```
and then we'll do a deployment defining
```
edpm_kernel_args="isolcpus=1,3,5,7,9"
```
the check will evaluate to false because it matches the substring so the new kernel arguments won't be applied.
Also, a new molecule test for this specific case has been added.

[edpm_kernel] Improve `edpm_kernel_args` search in `/proc/cmdline`

---

roles/edpm_libvirt/molecule/default/prepare.yml
roles/edpm_libvirt/molecule/default/verify.yml
roles/edpm_libvirt/tasks/configure.yml
roles/edpm_nova/molecule/default/prepare.yml

To support VTPM with Selinux we need to enable the policy.
Related: [OSPRH-2449](https://issues.redhat.com//browse/OSPRH-2449)
Related: [OSPRH-2451](https://issues.redhat.com//browse/OSPRH-2451)

[edpm_libvirt]Enable os_enable_vtpm selinux boolean

---

roles/edpm_neutron_sriov/molecule/default/converge.yml
roles/edpm_neutron_sriov/tasks/install.yml
roles/edpm_nova/tasks/install.yml

Getting permission denied error for directory
'/var/lib/openstack/config' with user 'cloud-admin'.
This issue is due to the provolege configuration
for '/var/lib/openstack/config' dir is '0750' in
neutron-sriov role.
Depends-On: https://github.com/openstack-k8s-operators/edpm-ansible/pull/540

Fixing nova permission denied issues

---

roles/edpm_users/tasks/create_users_and_groups.yml

Create host user and group, if not exists
During Wallaby to Anteleope FFU (EDPM adoption), users that exist
should not be attempted to get changed IDs, home paths, or the like.
In particular, changing openwswitch user ID to a constant agreed upon
for OSP-related services use from Kolla, breaks its upgrades.
Use getent to check if a user being created is already exists.
Only create it in a rescue block (getent fails if user does not exist).
While the user module is idempotent per se, it doesn't allow changin
user IDs.
This fixes ovs edpm role during EDPM adoption, in particular.
Depends-On: https://github.com/openstack-k8s-operators/install_yamls/pull/702

Create host user and group, if not exists

---

roles/edpm_ovs/tasks/user.yml

Due to the changes in [1] the openvswitch user is created before the
openvswitch package is installed. In RHEL systems the edpm_ovs role now
fails with [2]
This patch ensures the hugetlbfs group is created before the openvswitch
users is created and added to the hugetlbfs group.
[1] https://github.com/openstack-k8s-operators/edpm-ansible/pull/532
[2]
```
TASK [osp.edpm.edpm_users : Ensure user is present on the host [ openvswitch ]] ***
task path: /usr/share/ansible/collections/ansible_collections/osp/edpm/roles/edpm_users/tasks/create_users_and_groups.yml:32
fatal: [compute-0]: FAILED! => {"changed": false, "msg": "Group hugetlbfs does not exist"}
```
JIRA: https://issues.redhat.com/browse/OSPCIX-173

Ensure hugetlbfs group exists

---

.github/workflows/build-collection.yaml
.github/workflows/codeql.yml
.github/workflows/documentation.yaml
.github/workflows/molecule.yaml
.github/workflows/openstack-ansibleee-runner.yaml

EOL of node 16, we ought to move to more recent versions of github actions using node 20.
checkout action was bumped to version 4
setup-python was bumped to version 5
For more information https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20

Bumping checkout and setup-python actions

---

docs/source/testing_with_ansibleee.rst

The previous "edpm-ansible" metadata name was too generic, and other CRs could accidentally claim the PV.

Fix metadata name for testing with an NFS PV

---

molecule/test-helpers/verify_podman.yaml
plugins/modules/edpm_container_manage.py
roles/edpm_ovn_bgp_agent/molecule/default/verify.yml

As highlighted by @SeanMooney on https://issues.redhat.com/browse/OSPRH-153, we would like Podman log behaviour to be the one provided by the journald log_driver, which has been the default for a while.
The centralized logging retrieval system for the EDPM will expect the logs for all the containers to be stored in the journal.

Use journald as log_driver for the containers

---

roles/edpm_libvirt/meta/argument_specs.yml
roles/edpm_libvirt/tasks/configure.yml
roles/edpm_libvirt/templates/qemu.conf.j2
roles/edpm_ovs_dpdk/defaults/main.yml
roles/edpm_ovs_dpdk/meta/argument_specs.yml
roles/edpm_ovs_dpdk/tasks/configure.yml

Missing libvirt qemu group config and ovn bridge
datapath type is not updated correctly.

Libvirt qemu group config changes

---

docs/source/contributing.rst
docs/source/contributing_playbooks.rst
playbooks/bootstrap.yml
playbooks/ceph_client.yml
playbooks/ceph_hci_pre.yml
playbooks/configure_network.yml
playbooks/configure_os.yml
playbooks/configure_ovs_dpdk.yml
playbooks/download_cache.yml
playbooks/frr.yml
playbooks/install_certs.yml
playbooks/install_os.yml
playbooks/libvirt.yml
playbooks/neutron_dhcp.yml
playbooks/neutron_metadata.yaml
playbooks/neutron_ovn.yaml
playbooks/neutron_sriov.yml
playbooks/nova.yml
playbooks/ovn.yml
playbooks/ovn_bgp_agent.yml
playbooks/reboot.yml
playbooks/run_os.yml
playbooks/select_kernel_ddp_package.yml
playbooks/telemetry.yml
playbooks/telemetry_logging.yml
playbooks/validate_network.yml

Sometimes we may want to apply our play to a subset of nodes, or to all nodes, even though it was originally targeting 'all' or just some of them.
Right now, all of our playbooks target all hosts by default, so the override can be hypothetically used to target subset of nodes. But eventually, when we have playbooks for specific groups in inventory, this will allow us to instead go for all of them.
We just need to document it.

Allow hosts override from extra vars

---

roles/edpm_libvirt/defaults/main.yml
roles/edpm_libvirt/meta/argument_specs.yml

This change forces an older version of libvirt to be used
as 9.10.0 is know to have a parsing bug preventing nova
form working.
A follow up PR will remove the pin once libvirt 10 is aviable in
the centos 9 repos.

pin libvirt to < 9.10.0

---

roles/edpm_telemetry/tasks/deploy_ceilometer.yml

This lets us customize the ceilometer configuration based on the customServiceConfig field in ceilometer's part of the control plane CR.
Depends-On: https://github.com/openstack-k8s-operators/telemetry-operator/pull/285

Add ceilometer config customization

---

playbooks/configure_os.yml
playbooks/install_os.yml
playbooks/nova.yml
playbooks/nova_storage.yml
playbooks/run_os.yml
roles/edpm_iscsid/tasks/main.yml
roles/edpm_nova/tasks/configure.yml
roles/edpm_nova/templates/nova_compute.json.j2
roles/edpm_nvmeof/meta/argument_specs.yml
roles/edpm_nvmeof/meta/main.yml
roles/edpm_nvmeof/molecule/default/collections.yml
roles/edpm_nvmeof/molecule/default/converge.yml
roles/edpm_nvmeof/molecule/default/molecule.yml
roles/edpm_nvmeof/molecule/default/prepare.yml
roles/edpm_nvmeof/molecule/default/verify.yml
roles/edpm_nvmeof/tasks/install.yml
roles/edpm_nvmeof/tasks/main.yml

First commit:
Revamp deploying storage services required by nova
Storage services (namely the iSCSI and multipath daemons) required
by nova are now deployed using a dedicated playbook, which in turn
is imported by the nova playbook. This ensures the services only
get installed on EDPM nodes hosting nova.
Second commit:
NVMe-oF support has these components:
- Load the nvme-fabrics kernel module
- Install the nvme-cli package on the host (which initializes several files in /etc/nvme, and also some udev rules)
- Bind mount /etc/nvme into the nova-compute container
Jira: [OSPRH-1579](https://issues.redhat.com//browse/OSPRH-1579)

Support NVMEe-oF storage protocols

---

roles/edpm_nova/molecule/default/test-data/provider1.yaml
roles/edpm_nova/molecule/default/verify.yml
roles/edpm_nova/templates/config.json.j2

The kolla config of the nova-compute container is extended to move the provider*.yaml files to /etc/nova/provider_config/
Implements: [OSPRH-2503](https://issues.redhat.com//browse/OSPRH-2503)

[edpm_nova]Support provider*.yaml custom config

---

roles/edpm_ovn/defaults/main.yml
roles/edpm_ovn/meta/argument_specs.yml
roles/edpm_ovn/molecule/availability_zones/cleanup.yml
roles/edpm_ovn/molecule/availability_zones/collections.yml
roles/edpm_ovn/molecule/availability_zones/converge.yml
roles/edpm_ovn/molecule/availability_zones/molecule.yml
roles/edpm_ovn/molecule/availability_zones/prepare.yml
roles/edpm_ovn/molecule/availability_zones/test-data
roles/edpm_ovn/molecule/availability_zones/verify.yml
roles/edpm_ovn/tasks/cleanup.yml
roles/edpm_ovn/tasks/configure.yml

Role var is added to configure availability zones in external-ids:ovn-cms-options.
Related-Issue: [OSPRH-5009](https://issues.redhat.com//browse/OSPRH-5009)

[edpm_ovn] Add support for configuring Availability zones

---

docs/source/playbooks/ssh_known_hosts.rst
playbooks/ssh_known_hosts.yml

The playbook will be run by a dedicated dataplane-operator service that
will be executed across all nodes.

 Add new ssh_known_hosts.yml playbook 

---

roles/edpm_swift/defaults/main.yml
roles/edpm_swift/handlers/main.yml
roles/edpm_swift/tasks/configure.yml
roles/edpm_swift/tasks/main.yml

Makes it possible to selectively apply updates to the Swift rings only, which require a service restart in this case.

Add handler and tags for Swift ring updates

---

.github/workflows/molecule.yaml
playbooks/fips_status.yml
roles/edpm_bootstrap/defaults/main.yml
roles/edpm_bootstrap/meta/argument_specs.yml
roles/edpm_bootstrap/molecule/default/molecule.yml
roles/edpm_bootstrap/molecule/default/prepare.yml
roles/edpm_bootstrap/tasks/bootstrap.yml
roles/edpm_bootstrap/tasks/fips.yml
roles/edpm_bootstrap/tasks/fips_status.yml
roles/edpm_iscsid/defaults/main.yml
zuul.d/jobs.yaml
zuul.d/projects.yaml

These tasks can be used to check the status, enable or disable FIPS on a node.
They rely on `fips-mode-setup` tool provided by the `crypto-policies-scripts` package.
The action is governed by the `edpm_fips_mode` variable which can assumes 3 values:
- `enable`, to enable FIPS
- `disable`, to disable FIPS
- `check`, to check the status of FIPS
It defaults to `check`.
Closes: https://issues.redhat.com/browse/OSPRH-3071

[FIPS] Added FIPS related tasks in `edpm_bootstrap` and `edpm_iscsid` roles

---

roles/edpm_nova/tasks/configure.yml

The cert management is moved to a separate role by #525 but a rebase
mistake in ca102fc reintroduced the task to the nova role.

[edpm_nova]Remove cert copy task

---

roles/edpm_libvirt/defaults/main.yml
roles/edpm_libvirt/molecule/default/collections.yml
roles/edpm_libvirt/molecule/default/converge.yml
roles/edpm_libvirt/molecule/default/prepare.yml
roles/edpm_libvirt/molecule/default/test-helpers/verify_firewall.yaml
roles/edpm_libvirt/molecule/default/verify.yml
roles/edpm_libvirt/molecule/vagrant/collections.yml
roles/edpm_libvirt/tasks/configure.yml
roles/edpm_libvirt/tasks/install.yml
roles/edpm_libvirt/tasks/post-install.yml
roles/edpm_libvirt/templates/firewall.yaml.j2
roles/edpm_libvirt/templates/qemu.conf.j2
roles/edpm_libvirt/templates/virtnodedevd.conf
roles/edpm_libvirt/templates/virtproxyd.conf
roles/edpm_libvirt/templates/virtqemud.conf
roles/edpm_libvirt/templates/virtsecretd.conf

This change adds molecule testing for deploying libvirt
with tls. to enable this the prepare playbook is enhanced
to generate a ca and issue client and server certs to mimic
what will be generated by cert manager.
The edpm_libvirt role is updated to use the defualt locations
expect by libvirt as documented in https://libvirt.org/kbase/tlscerts.html
This is done to ensure that virsh and other clients automaticaly work
and to avoid overriding the libvirt socket activation files to use custom
values.
Closes: [OSPRH-2387](https://issues.redhat.com//browse/OSPRH-2387)

Add support for TLS to edpm_libvirt

---

roles/edpm_nova/templates/nova_compute.json.j2

The feature isn't fully implemented yet and the certificates aren't at the specified location. This means, that the ansible fails when deploying with TLS enabled.

[edpm_nova]Remove certificate mounts when TLS enabled

---

roles/edpm_swift/tasks/disks.yml
roles/edpm_swift/templates/kolla_config/swift_account_auditor.yaml.j2
roles/edpm_swift/templates/kolla_config/swift_account_reaper.yaml.j2
roles/edpm_swift/templates/kolla_config/swift_account_replicator.yaml.j2
roles/edpm_swift/templates/kolla_config/swift_account_server.yaml.j2
roles/edpm_swift/templates/kolla_config/swift_container_auditor.yaml.j2
roles/edpm_swift/templates/kolla_config/swift_container_replicator.yaml.j2
roles/edpm_swift/templates/kolla_config/swift_container_server.yaml.j2
roles/edpm_swift/templates/kolla_config/swift_container_updater.yaml.j2
roles/edpm_swift/templates/kolla_config/swift_object_auditor.yaml.j2
roles/edpm_swift/templates/kolla_config/swift_object_expirer.yaml.j2
roles/edpm_swift/templates/kolla_config/swift_object_replicator.yaml.j2
roles/edpm_swift/templates/kolla_config/swift_object_server.yaml.j2
roles/edpm_swift/templates/kolla_config/swift_object_updater.yaml.j2
roles/edpm_swift/templates/rsync.yaml.j2

There were a couple of changes in swift-operator and its configuration files recently, and changes need to be applied to EDPM as well. Also fixing permissions on the created disks.

Fix swift config files and permissions

---

openstack_ansibleee/Dockerfile

The variable was not used everywhere it could be used.

Replace /var/tmp/edpm-ansible with $REMOTE_SOURCE_DIR

---

roles/edpm_install_certs/meta/argument_specs.yml
roles/edpm_install_certs/tasks/copy_certs_and_keys.yaml
roles/edpm_libvirt/defaults/main.yml
roles/edpm_libvirt/molecule/default/prepare.yml
roles/edpm_libvirt/tasks/configure.yml

The CA bundle includes all of the standard root CAs. Libvirt must only trust the specific CA.
Depends-On: https://github.com/openstack-k8s-operators/dataplane-operator/pull/731

Libvirt must not trust the CA bundle

---

roles/edpm_podman/defaults/main.yml
roles/edpm_podman/meta/argument_specs.yml
roles/edpm_podman/tasks/configure.yml
roles/edpm_podman/tasks/login-kube-registry.yml
roles/edpm_podman/tasks/login.yml

Adds a new tasks file, roles/edpm_podman/tasks/login-kube-registry.yml.
The tasks login to a kubernetes registry using service account
credentials that are read from a known location made available by the
service account associated with the ansible pod.
The podman login command uses
"--authfile ~/.config/containers/auth.json" to override the default
authfile location of $XDG_RUNTIME_DIR/containers/auth.json. This
override is needed since $XDG_RUNTIME_DIR is not defined when using
"become: true" with ansible, which results in the podman logins not
actually being persisted anywhere. Overriding the location also persists
the logins across reboots. The authfile override is also added to the
existing podman login task in login.yml

Add tasks to login to kube registry with a service account to edpm_podman

---

roles/edpm_libvirt/tasks/configure.yml

Previously the role only relabelled /run/libvirt if that dir itself had
wrong labels, but we need to do the relabeling also if any of the stuff
in that directory still has container_t label. During adoption we can
have a situation where /run/libvirt/common has a wrong label but
/run/libvirt has the correct one.
So this patch checks /run/libvirt recursively

[edpm_libvirt]Make sure that /run/libvirt is relabelled

---

roles/edpm_libvirt/defaults/main.yml
roles/edpm_libvirt/meta/argument_specs.yml
roles/edpm_libvirt/tasks/adoption.yml
roles/edpm_libvirt/tasks/main.yml
roles/edpm_nova/defaults/main.yml
roles/edpm_nova/meta/argument_specs.yml
roles/edpm_nova/tasks/adoption.yml
roles/edpm_nova/tasks/main.yml

Match the target container by a strict name.
Filter unrelated nova_virtlogd_wrapper container
and make the nova_virtlogd stopping condition triggering.
Move the stopping logic for nova_virtlogd_wrapper and nova_virtlogd
into the libvirt role as we need to stop these *before* we start
deploying de-containerized libvirt. While the nova role is called
after the libvirt role, so stopping the tripleo libvirt related
happens too late (libvirt has already failed).
Also stop other Nova control plane services, in case of all-in-one
overcloud adoption.
JIRA [OSPRH-2302](https://issues.redhat.com/browse/OSPRH-2302)

Adoption: fix stopping nova services from tripleo

---

roles/edpm_libvirt/tasks/configure.yml

Match the labels with regex to properly trigger restorecon

Fix selinux labels check for /run/libvirt

---

roles/edpm_install_certs/tasks/copy_ca_certs.yaml
roles/edpm_ovn/defaults/main.yml
roles/edpm_ovn/meta/argument_specs.yml
roles/edpm_ovn/templates/kolla_ovn_controller.yaml.j2
roles/edpm_ovn/templates/ovn_controller.yaml.j2

Update to latest edpm TLS logic.
Use the same key/crt names as control plane for consistency.
Trust the CA bundle. Make it world readable to allow it to be mounted directly.
Expects dataplane-operator to pass edpm_service_name if it's not the default.
Jira: [OSPRH-2191](https://issues.redhat.com//browse/OSPRH-2191)

OVN TLS support

---

roles/edpm_nova/defaults/main.yml
roles/edpm_nova/molecule/default/collections.yml
roles/edpm_nova/molecule/default/converge.yml
roles/edpm_nova/molecule/default/prepare.yml
roles/edpm_nova/molecule/default/verify.yml
roles/edpm_nova/molecule/vagrant/collections.yml
roles/edpm_nova/templates/02-nova-host-specific.conf.j2
roles/edpm_nova/templates/nova_compute.json.j2

Nova already connected to libvirt via unix socket so it does not
need the libvirt tls certs for local communcitaiton. nova does
not need to connect to remote libvirt, as a result we do not need
to provide access to the libvirt client cert.
The 02-nova-host-specific.conf.j2 template has been updated to
enable libvirt native tls for live migration when tls is enabled.
molecule test coverage is added for the above changes.
Closes: [OSPRH-5053](https://issues.redhat.com//browse/OSPRH-5053)

ADD tls-e support for edpm_nova

---

.github/workflows/molecule.yaml
docs/source/playbooks/sriov_derive_device_spec.rst
docs/source/roles/role-edpm_derive_pci_device_spec.rst
playbooks/sriov_derive_device_spec.yml
plugins/modules/edpm_derive_pci_passthrough_devicespec.py
plugins/tests/molecule/edpm_derive_pci_passthrough_devicespec/test_derive_pci_passthrough_devicespec.py
roles/edpm_derive_pci_device_spec/defaults/main.yml
roles/edpm_derive_pci_device_spec/meta/argument_specs.yml
roles/edpm_derive_pci_device_spec/meta/main.yml
roles/edpm_derive_pci_device_spec/molecule/default/collections.yml
roles/edpm_derive_pci_device_spec/molecule/default/converge.yml
roles/edpm_derive_pci_device_spec/molecule/default/molecule.yml
roles/edpm_derive_pci_device_spec/molecule/default/prepare.yml
roles/edpm_derive_pci_device_spec/molecule/default/verify.yml
roles/edpm_derive_pci_device_spec/tasks/derive_pci_device_spec.yml
roles/edpm_derive_pci_device_spec/tasks/main.yml
scripts/generate_molecule.py

This role will generate the pci device_spec for sriov nic partitioning deployment.
The generated config file should be used to create device_spec configmap for custom nova dataplane service.
This has been re-factored from [PR](https://github.com/openstack-k8s-operators/edpm-ansible/pull/572)

Derive pci device_spec edpm_derive_pci_device_spec

---

docs/source/roles/role-edpm-reboot.rst

Add missing rst file for inclussion of reboot role into generated docs.
PR of reboot role: https://github.com/openstack-k8s-operators/edpm-ansible/pull/503

Add documentation source file for reboot role

---

roles/edpm_neutron_dhcp/defaults/main.yml
roles/edpm_neutron_dhcp/meta/argument_specs.yml
roles/edpm_neutron_dhcp/templates/neutron-dhcp-agent.conf.j2
roles/edpm_neutron_metadata/defaults/main.yml
roles/edpm_neutron_metadata/meta/argument_specs.yml
roles/edpm_neutron_sriov/defaults/main.yml
roles/edpm_neutron_sriov/meta/argument_specs.yml

Variable 'edpm_neutron_metadata_agent_DEFAULT_host' defined in the edpm_neutron_metadata role wasn't actually used anywhere in the role except argument_specs.yml meta file where it was used as default value for the 'edpm_neutron_metadata_agent_DEFAULT_nova_metadata_host' variable (which was also not correct).
Variable 'edpm_neutron_metadata_agent_DEFAULT_host' is actually not needed anywhere as neutron_ovn_metadata_agent reports hostname on which it is run using hostname defined in the "ovn chassis" (and this is configured by the edpm_ovn role in external_ids in ovsdb).
Because of all of that mentioned above, this small patch removes that not used variable.

Clean edpm_neutron_metadata role from unused variable

---

roles/edpm_install_certs/tasks/copy_certs_and_keys.yaml

the tls certs are indexed by the node.HostName
when generating the invetory the inventory_hostname is
computed via strings.Split(node.HostName, ".")[0]
node.HostName is stored in the canonical_hostname field
of the host vars.
This change updates edpm_install_certs to align
to the go code by using canonical_hostname instead.
Depends-On: https://github.com/openstack-k8s-operators/dataplane-operator/pull/778

use canonical_hostname not inventory hostname for certs

---

roles/edpm_neutron_dhcp/molecule/default/molecule.yml
roles/edpm_neutron_dhcp/molecule/default/tests/test_neutron_dhcp.py
roles/edpm_neutron_dhcp/templates/neutron-dhcp-agent.conf.j2
roles/edpm_neutron_ovn/molecule/default/molecule.yml
roles/edpm_neutron_ovn/molecule/default/verify.yml
roles/edpm_neutron_ovn/templates/neutron-ovn-agent.conf.j2
roles/edpm_neutron_sriov/molecule/default/molecule.yml
roles/edpm_neutron_sriov/molecule/default/verify.yml
roles/edpm_neutron_sriov/templates/neutron-sriov-agent.conf.j2
roles/edpm_nova/molecule/default/molecule.yml
roles/edpm_nova/molecule/default/verify.yml
roles/edpm_nova/templates/02-nova-host-specific.conf.j2
roles/edpm_ovn/defaults/main.yml
roles/edpm_ovn/molecule/default/molecule.yml
roles/edpm_ovn/molecule/default/verify-tasks.yml
roles/edpm_ovn/molecule/noconfig/molecule.yml
roles/edpm_telemetry/molecule/default/molecule.yml
roles/edpm_telemetry/molecule/default/verify.yml
roles/edpm_telemetry/tasks/configure.yml
roles/edpm_telemetry/templates/ceilometer-agent-compute.json.j2
roles/edpm_telemetry/templates/ceilometer-agent-ipmi.json.j2
roles/edpm_telemetry/templates/ceilometer-host-specific.conf.j2

The greenfield deployment sets up host FQDN via IPAM but did not change
the /etc/hostname to FQDN. This causes that libvirt will see and use
FQDN for the node names, but nova-compute uses the sort hostname
returned by socket.gethostname().
In greenfield it causes that the nova-compute host name is different
form the compute nodename. Nova works with this setup, but it will cause
confusion for the users coming from older versions where both names are
FQDN.
During adoption, when the adopted cloud does not have FQDN in the
/etc/hostname, the compute service host name will change as in 18 we are
not yet hardcoding the FQDN in the nova.conf. This results in failed
adoption.
This PR ensures the [DEFAULT]host is set to the FQDN based on the
canonical_hostname variable for all the EDPM openstack …

Use FQDN as sevice hostname

---

roles/edpm_telemetry/tasks/install.yml

Node Exporter fails to start and then the service fails with:
```
TASK [osp.edpm.edpm_telemetry : Restart node_exporter] *************************
[1;30mtask path: /usr/share/ansible/collections/ansible_collections/osp/edpm/roles/edpm_telemetry/tasks/install.yml:139[0m
[0;31mfatal: [compute-0]: FAILED! => {"changed": false, "msg": "Unable to restart service edpm_node_exporter.service: Job for edpm_node_exporter.service failed because the control process exited with error code.\nSee \"systemctl status edpm_node_exporter.service\" and \"journalctl -xeu edpm_node_exporter.service\" for details.\n"}[0m
```
We're already using "become: true" in the non-tls version of the task.
We have another PR blocked by this issue: https://github.com/openstack-k8s-operators/dataplane-operator/pull/754

Add become: True to node_exporter when TLS enabled

---

roles/edpm_neutron_metadata/defaults/main.yml
roles/edpm_neutron_metadata/meta/argument_specs.yml
roles/edpm_neutron_metadata/templates/ovn_metadata_agent.yaml.j2
roles/edpm_ovn/templates/ovn_controller.yaml.j2
roles/edpm_ovn_bgp_agent/templates/bgp_ovn_controller.yaml.j2
roles/edpm_ovn_bgp_agent/templates/nb_db_server.yaml.j2
roles/edpm_ovn_bgp_agent/templates/northd.yaml.j2
roles/edpm_ovn_bgp_agent/templates/ovn_bgp_agent.yaml.j2
roles/edpm_ovn_bgp_agent/templates/sb_db_server.yaml.j2

Metadata agent requires TLS certs to access the southdb. Also cleanup dup volume mounts in ovn services.

Add OVN TLS certs for metadata agent

---

roles/edpm_libvirt/defaults/main.yml
roles/edpm_nova/defaults/main.yml
roles/edpm_nova/meta/argument_specs.yml
roles/edpm_nova/molecule/default/converge.yml
roles/edpm_nova/tasks/install.yml
roles/edpm_nova/templates/02-nova-host-specific.conf.j2
roles/edpm_nova/templates/nova_compute.json.j2

The current certs are not valid for libvirt.
Specific requirements in https://libvirt.org/kbase/tlscerts.html
QEMU cert paths are also incorrect. Current dataplan-operator is broken https://github.com/openstack-k8s-operators/openstack-operator/pull/732#issuecomment-2041915225

Disable libvirt TLS for now

---

roles/edpm_libvirt/defaults/main.yml
roles/edpm_libvirt/templates/qemu.conf.j2
roles/edpm_nova/defaults/main.yml
roles/edpm_nova/molecule/default/verify.yml
roles/edpm_nova/templates/02-nova-host-specific.conf.j2

Related: [OSPRH-2387](https://issues.redhat.com//browse/OSPRH-2387)

Re-enable libvirt TLS but not NBD TLS

---

.github/workflows/molecule.yaml
docs/source/playbooks/pre_adoption_validation.rst
docs/source/roles/role-edpm_pre_adoption_validation.rst
playbooks/pre_adoption_validation.yml
roles/edpm_pre_adoption_validation/defaults/main.yml
roles/edpm_pre_adoption_validation/handlers/main.yml
roles/edpm_pre_adoption_validation/meta/argument_specs.yml
roles/edpm_pre_adoption_validation/meta/main.yml
roles/edpm_pre_adoption_validation/molecule/adoption-negative/converge.yml
roles/edpm_pre_adoption_validation/molecule/adoption-negative/molecule.yml
roles/edpm_pre_adoption_validation/molecule/adoption-negative/prepare.yml
roles/edpm_pre_adoption_validation/molecule/adoption-negative/test-data/old_neutron.conf
roles/edpm_pre_adoption_validation/molecule/adoption-negative/test-data/old_nova.conf
roles/edpm_pre_adoption_validation/molecule/adoption-positive/converge.yml
roles/edpm_pre_adoption_validation/molecule/adoption-positive/molecule.yml
roles/edpm_pre_adoption_validation/molecule/adoption-positive/prepare.yml
roles/edpm_pre_adoption_validation/molecule/adoption-positive/test-data/old_neutron.conf
roles/edpm_pre_adoption_validation/molecule/adoption-positive/test-data/old_nova.conf
roles/edpm_pre_adoption_validation/molecule/greenfield/converge.yml
roles/edpm_pre_adoption_validation/molecule/greenfield/molecule.yml
roles/edpm_pre_adoption_validation/molecule/greenfield/prepare.yml
roles/edpm_pre_adoption_validation/tasks/main.yml

The new edpm_pre_adoption_validation role is intended to be used as
dataplane service in a separate deployment during adoption that runs
before the main deployment of the adoption process. This role does not
change anything on the EDPM nodes just reads their current (pre-adoption)
configuration and check if the intended new (post-adoption)
configuration will not cause any trouble.
The first check introduced by this commit ensures that the openstack
service hostname will not change during adoption on the EDPM nodes. Such
change would cause adoption failure in a later stage, after the point of
no return, as nova-compute will refuse to start up if it detects the
host rename. Additionally neutron services might fail too / or create
database corruption due to the host rename.
Implements: …

[adoption]Add a new role for pre adoption validation 

---

roles/edpm_telemetry/tasks/install.yml

This will break the host.
E.g systemd-hostnamed fails with `type=AVC msg=audit([1713190908](tel:1713190908).762:30498): avc:  denied  { write } for  pid=116232 comm="systemd-hostnam" name="system_bus_socket" dev="tmpfs" ino=459 scontext=system_u:system_r:systemd_hostnamed_t:s0 tcontext=system_u:object_r:container_file_t:s0 tclass=sock_file permissive=0`

Stop edpm_telemetry selinux relabelling the system dbus socket

---

roles/edpm_frr/templates/frr.yaml.j2

We dropped /openstack/healthcheck in the image so let's remove the healthcheck from the container definition.

Remove healthcheck for frr container

---

roles/edpm_pre_adoption_validation/defaults/main.yml
roles/edpm_pre_adoption_validation/meta/argument_specs.yml
roles/edpm_pre_adoption_validation/molecule/adoption-negative/prepare.yml
roles/edpm_pre_adoption_validation/molecule/adoption-positive/prepare.yml

The 91d657948bcfa5159e02f4ae4dae579c58a7bfbc wrongly used
/var/lib/config-data/nova instead of nova_libvirt to look at the config
of from of the pre-adopted node. We missed this as it was only tested
with standalone deployments where both nova and nova_libvirt exists on
the machine. In a multinode deployment only nova_libvirt exists on the
compute node.
Implements: [OSPRH-6333](https://issues.redhat.com//browse/OSPRH-6333)

Fix pre adoption nova.conf path default

---

playbooks/configure_os.yml

Drop edpm_ssh_known_hosts role from configure_os.yml playbook
The role is now run from playbooks/ssh_known_hosts.yml, which is used by
the ssh-known-hosts DataPlaneService, which has been included by default
on the NodeSet since dataplane-operator commit
73064d451ea4a23cce919d47e1a866ad79506b43.

Drop edpm_ssh_known_hosts role from configure_os.yml playbook

---

roles/edpm_neutron_sriov/defaults/main.yml
roles/edpm_neutron_sriov/meta/argument_specs.yml
roles/edpm_neutron_sriov/templates/neutron_sriov_agent.yaml.j2

Depends-On: https://github.com/openstack-k8s-operators/dataplane-operator/pull/842

[edpm_neutron_sriov] Add caCerts to container if tls enabled

---

roles/edpm_neutron_dhcp/defaults/main.yml
roles/edpm_neutron_dhcp/meta/argument_specs.yml
roles/edpm_neutron_dhcp/templates/neutron_dhcp_agent.yaml.j2

Depends-On: https://github.com/openstack-k8s-operators/dataplane-operator/pull/848
Closes: [OSPRH-6498](https://issues.redhat.com//browse/OSPRH-6498)

[edpm_neutron_dhcp] Add caCerts to container if tls enabled

---

roles/edpm_nova/tasks/configure.yml

The podman version 4.6.0 has a bug that causes that sometimes a
container fails to start if it mounts an file with +i flag set.
This podman version is used in the adoption form state making the
adoption unstable (1 in 8 CI run fails). The greenfield 18 deployment
uses podman 4.9.4 that does not show this error. So to make the adoption
stable the edpm_nova role will not add the +i flag to existing
compute_id files. Still if the role pre-generates the file that means it
is a greenfield run so the flag can be, and will be, set safely.

[edpm_nova]Do not add immutable flag to compute_id 

---

playbooks/bootstrap.yml

Sometimes baremetal nodes are not reachable for few mins after they have been provisioned. As bootstrap is always the first play run, this would allow us wait for sometime for the connections to be ready.

Wait for nodes to be reachable

---

roles/edpm_pre_adoption_validation/defaults/main.yml
roles/edpm_pre_adoption_validation/meta/argument_specs.yml
roles/edpm_pre_adoption_validation/molecule/hostname-adoption-negative/molecule.yml
roles/edpm_pre_adoption_validation/molecule/hostname-adoption-positive/molecule.yml
roles/edpm_pre_adoption_validation/molecule/hostname-greenfield/molecule.yml
roles/edpm_pre_adoption_validation/molecule/kernel-args-existing-args/molecule.yml
roles/edpm_pre_adoption_validation/molecule/kernel-args-new-hugepages/molecule.yml
roles/edpm_pre_adoption_validation/molecule/kernel-args-no-args/molecule.yml
roles/edpm_pre_adoption_validation/molecule/tuned-new-profile/converge.yml
roles/edpm_pre_adoption_validation/molecule/tuned-new-profile/molecule.yml
roles/edpm_pre_adoption_validation/molecule/tuned-new-profile/prepare.yml
roles/edpm_pre_adoption_validation/molecule/tuned-no-change/converge.yml
roles/edpm_pre_adoption_validation/molecule/tuned-no-change/molecule.yml
roles/edpm_pre_adoption_validation/molecule/tuned-no-change/prepare.yml
roles/edpm_pre_adoption_validation/molecule/tuned-no-profile/converge.yml
roles/edpm_pre_adoption_validation/molecule/tuned-no-profile/molecule.yml
roles/edpm_pre_adoption_validation/molecule/tuned-no-profile/prepare.yml
roles/edpm_pre_adoption_validation/tasks/hostname.yml
roles/edpm_pre_adoption_validation/tasks/tuned.yml

New check is added to edpm_pre_adoption_validation role that ensure that
the tuned profile does not change during adoption as such change would
require a reboot that is not possible during adoption.
Implements: [OSPRH-5715](https://issues.redhat.com//browse/OSPRH-5715)

[pre-adoption-validation]Check tuned profile

---

roles/edpm_libvirt/templates/qemu.conf.j2

Depends-On: https://github.com/openstack-k8s-operators/openstack-operator/pull/780
Jira: [OSPRH-6174](https://issues.redhat.com//browse/OSPRH-6174)

[libvirt] enable vencrypt when libvirt tls enabled

---

roles/edpm_tuned/defaults/main.yml
roles/edpm_tuned/meta/argument_specs.yml
roles/edpm_tuned/tasks/configure.yml

Tuned powersave profile setting needs additional
edpm variable to set the c-state value

Add edpm variable for powersave profile

---

roles/edpm_frr/defaults/main.yml
roles/edpm_neutron_dhcp/defaults/main.yml
roles/edpm_neutron_metadata/defaults/main.yml
roles/edpm_neutron_ovn/defaults/main.yml
roles/edpm_neutron_sriov/defaults/main.yml
roles/edpm_ovn_bgp_agent/defaults/main.yml
roles/edpm_telemetry/defaults/main.yml
roles/edpm_telemetry_logging/defaults/main.yml

Some vars were not using "edpm_service_name" for
the generated content, this patch fixes it.
Additionally fixed some unused vars.

Fix roles default vars to correctly use edpm_service_name

---

roles/edpm_neutron_metadata/meta/argument_specs.yml

edpm_neutron_metadata_tls_volumes argument.
List types should specify 'elements' field.

Missing type: 'list' field for the

---

roles/edpm_kernel/tasks/kernelargs.yml

In order to update the kernel args properly in RHEL 9.X the --update-bls-cmdline is required.Without this flag the /boot/loader/entries/ files are not updated which causes the kernal args in the grub.cfg to be ignored. Added the flag for RHEL9 and up to allow proper cmdline update during boot.
This patch should fix this issue: [EDPM fails to set kernel args in deployed compute in RHEL 9.4](https://issues.redhat.com/browse/OSPRH-6665)

Fix grub2-mkconfig kernel args for --update-bls-cmdline

---

roles/edpm_libvirt/molecule/default/prepare.yml
roles/edpm_libvirt/molecule/default/verify.yml
roles/edpm_libvirt/molecule/vagrant/molecule.yml
roles/edpm_libvirt/tasks/configure.yml
roles/edpm_libvirt/templates/qemu.conf.j2

This change disabled nbd_tls to prevent guest
crahses on local storage guest live migrations.
Closes: [OSPRH-6931](https://issues.redhat.com//browse/OSPRH-6931)

disable nbd_tls until RHEL-33754 is resolved

---

roles/edpm_network_config/tasks/os_net_config.yml

Adds a debug task to display the contents of the os-net-config config file before this is applied. This can be especially useful if node connectivity is disrupted after the config is applied.
https://issues.redhat.com/browse/OSPRH-5754

Add output of os-net-config file before applying in edpm_network_config

---

roles/edpm_libvirt/defaults/main.yml
roles/edpm_neutron_dhcp/defaults/main.yml
roles/edpm_neutron_metadata/defaults/main.yml
roles/edpm_neutron_ovn/defaults/main.yml
roles/edpm_neutron_sriov/defaults/main.yml
roles/edpm_nova/defaults/main.yml
roles/edpm_nova/tasks/install.yml
roles/edpm_nova/templates/nova_compute.json.j2
roles/edpm_ovn/defaults/main.yml
roles/edpm_ovn_bgp_agent/defaults/main.yml
roles/edpm_telemetry/defaults/main.yml
roles/edpm_telemetry_logging/defaults/main.yml

edpm_service_name corresponds to the DataPlaneService name, creating
tight coupling between the name of the service and the expected podman
volume paths.
This breaks many assumptions around custom DataPlaneServices, and the
fact that different services may use the same ansible roles, or a single
service may use multiple ansible roles that need different volume paths.
These paths should instead be isolated from the DataPlaneService name.
This commit drops usage of edpm_service_name which is set by
dataplane-operator, and adds a new var per role for creating the path.
The new vars will not be set by dataplane-operator.
A corresponding dataplane-operator commit will take care of creating the
paths so that they are in the ansible role expected locations.
Jira: …

Drop usage of edpm_service_name

---

.github/workflows/molecule.yaml
playbooks/update.yml
roles/edpm_update/defaults/main.yml
roles/edpm_update/meta/argument_specs.yml
roles/edpm_update/meta/main.yml
roles/edpm_update/molecule/default/Containerfile.j2
roles/edpm_update/molecule/default/converge.yml
roles/edpm_update/molecule/default/molecule.yml
roles/edpm_update/molecule/default/prepare.yml
roles/edpm_update/tasks/containers.yml
roles/edpm_update/tasks/main.yml
roles/edpm_update/tasks/packages.yml

The `edpm_update` role is added to allow the update of packages and containers on EDPM nodes.
The related `update.yml` playbook has been added.
Jira: https://issues.redhat.com/browse/OSPRH-6219

[edpm_update] Added `edpm_update` role and `update` playbook

---

docs/source/playbooks/tripleo_cleanup.rst
docs/source/roles/role-edpm_tripleo_cleanup.rst
playbooks/tripleo_cleanup.yml
roles/edpm_tripleo_cleanup/defaults/main.yml
roles/edpm_tripleo_cleanup/meta/argument_specs.yml
roles/edpm_tripleo_cleanup/meta/main.yml
roles/edpm_tripleo_cleanup/molecule/default/collections.yml
roles/edpm_tripleo_cleanup/molecule/default/converge.yml
roles/edpm_tripleo_cleanup/molecule/default/molecule.yml
roles/edpm_tripleo_cleanup/molecule/default/prepare.yml
roles/edpm_tripleo_cleanup/molecule/default/test-data/fake-tripleo-service.service
roles/edpm_tripleo_cleanup/molecule/default/verify.yml
roles/edpm_tripleo_cleanup/tasks/main.yml
zuul.d/jobs.yaml
zuul.d/projects.yaml

Just a role with documentation and tests. Actual invocations of the role, along with removals of other cleanup routines, will be included in follow up PRs.

Cleanup role for tripleo services

---

roles/edpm_neutron_dhcp/tasks/run.yml

The Neutron DHCP agent doesn't follow naming convention for Neutron agent services in standalone. It does not contain the _agent suffix and is named just neutron_dhcp.
Resolves: [OSPRH-6703](https://issues.redhat.com//browse/OSPRH-6703)

Use correct standalone container name for DHCP agent

---

roles/edpm_ovn/defaults/main.yml
roles/edpm_ovn/meta/argument_specs.yml
roles/edpm_ovn/molecule/default/verify-tasks.yml
roles/edpm_ovn/molecule/noconfig/verify.yml

This patch allows for the ovn-encap-tos to be configured in ovn-controller.
By default this option has the value of 0, as per OVS options:tos description [0], but it could also contain the word "inherit" therefore the field type for this patch is "str".
[0]
options : tos: optional string
Optional. The value of the ToS bits to be set on the encapsulat‐
ing packet. ToS is interpreted as DSCP and ECN  bits,  ECN  part
must be zero. It may also be the word inherit, in which case the
ToS will be copied from the inner packet if it is IPv4  or  IPv6
(otherwise  it  will be 0). The ECN fields are always inherited.
Default is 0.
http://www.openvswitch.org/support/dist-docs/ovs-vswitchd.conf.db.5.txt
Resolves: [OSPRH-6712](https://issues.redhat.com//browse/OSPRH-6712)

Allow ovn-encap-tos to be configured

---

docs/source/roles/role-edpm_reboot.rst
roles/edpm_bootstrap/tasks/fips.yml
roles/edpm_reboot/defaults/main.yaml
roles/edpm_reboot/meta/argument_specs.yml
roles/edpm_reboot/tasks/main.yaml

Add edpm_reboot_strategy to reboot role that defines if reboot should be started or not. There are three modes: auto, never and force. The default is auto.
Add also more generic check for existence of openstack configs for already
deployed nodes, both old tripleo and new edpm node.

Add edpm_reboot_strategy to reboot role

---

roles/edpm_bootstrap/defaults/main.yml
roles/edpm_bootstrap/meta/argument_specs.yml

This has changed from rhosp-release to rhoso-release for OSP18.

Use rhoso-release as release rpm name

---

roles/edpm_sshd/molecule/banners/converge.yml
roles/edpm_sshd/molecule/banners/verify.yml
roles/edpm_sshd/tasks/configure.yml
roles/edpm_sshd/templates/sshd_config_block.j2

Use private variable when rendering sshd server options. This avoids issues with clobbering user provided settings when we try to re-use the same variable name.

Use private variable for sshd_options

---

roles/edpm_bootstrap/tasks/fips.yml

As reported in https://issues.redhat.com/browse/OSPRH-7301 , the fips task incorrectly changes the reboot policy when the required fips status changes.  We should follow whatever is defined by the deployer instead.
If nothing is defined, the policy is auto - which will result in a reboot.
In the case of a redeployed or adopted environment, we will end up simply logging that a reboot is supposed to happen.  But we will then likely fail the subsquent fips status check - which is the desired behavior.
Resolves: https://issues.redhat.com/browse/OSPRH-7301

FIPS task should not change reboot policy

---

roles/edpm_ovn/defaults/main.yml
roles/edpm_ovn/meta/argument_specs.yml

`true` value is needed when executing "fail safe upgrades" only [0]. (These are upgrades where an LTS release is skipped; or when ovn-controllers are updated after northd.) This is not the upgrade scenario that we follow.
This was fixed in puppet modules in [1] but sadly was missed when the code was imported to this repo (several months before the change in puppet modules.)
[0] https://docs.ovn.org/en/latest/intro/install/ovn-upgrades.html#fail-safe-upgrade
[1] https://opendev.org/openstack/puppet-tripleo/commit/68b4a7c87d3af1200d18149365844d40683cb530
Depends-On: https://github.com/openstack-k8s-operators/openstack-operator/pull/792

Set ovn_match_northd_version to false by default

---

zuul.d/projects.yaml

This adds cifmw-data-plane-adoption-osp-17-to-extracted-crc to github-check.
https://issues.redhat.com/browse/OSPRH-7332

 Add data-plane-adoption job to the edpm-ansible zuul github-check layout 

---

roles/edpm_growvols/defaults/main.yml

We're getting increasing field feedback for OSP17.1 that the default amount of space for logs is insufficent. As such, posting this change to align and hopefully head off issues. This is likely less of an issue as the reports have largely been centered around controllers, but overall it is best to keep some level of alignment.
https://bugzilla.redhat.com/show_bug.cgi?id=2280656 https://issues.redhat.com/browse/OSP-32120

Increase default space for logs

---

roles/edpm_install_certs/tasks/adoption.yml

To copy file only on remote server remote_src
should be set to true.

Use remote_src for backing up the directory

---

roles/edpm_tripleo_cleanup/defaults/main.yml
roles/edpm_tripleo_cleanup/meta/argument_specs.yml
roles/edpm_tripleo_cleanup/tasks/main.yml

Swift storage services are removed by a separate procedure later during adoption process.
Therefore it is undesirable to remove them together with other services originally deployed by tripleO.
https://issues.redhat.com/browse/OSPRH-7432

Skip removal of services related to swift storage

---

roles/edpm_neutron_dhcp/tasks/install.yml
roles/edpm_neutron_metadata/tasks/install.yml

Installation tasks in the edpm_neutron_dhcp and edpm_neutron_metadata were using `default(lookup('pipe', 'whoami'))` which [by design runs on the ansible controller](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pipe_lookup.html#notes) and not the target host as this tasks intends. 
Replacing with `default(ansible_user_id)` which is the user that Ansible logs in.
JIRA: [OSPRH-7321](https://issues.redhat.com/browse/OSPRH-7321)

Fix file ownership for neutron dhcp and metadata agent

---

roles/edpm_nftables/molecule/action/prepare.yml
roles/edpm_nftables/molecule/destination/prepare.yml
roles/edpm_nftables/molecule/source/prepare.yml

This change adds a string port range component to the molecule tests to ensure we're able to parse a string without trying to iterate over it.
Resolves: https://issues.redhat.com/browse/OSPRH-7637

Add molecule check for string port-range

---

molecule/test-helpers/verify_mounts.yaml
roles/edpm_nova/defaults/main.yml
roles/edpm_nova/meta/argument_specs.yml
roles/edpm_nova/molecule/default/converge.yml
roles/edpm_nova/molecule/default/prepare.yml
roles/edpm_nova/molecule/default/verify.yml
roles/edpm_nova/molecule/vagrant/molecule.yml
roles/edpm_nova/tasks/configure.yml
roles/edpm_nova/templates/nova_compute.json.j2

This change add support for optionally addding a restrict
set of addtional host bind mounts to the nova_compute container
This functionality is intended only for certifed vendor
integrations not as a generic feature.
Closes: [OSPRH-7644](https://issues.redhat.com//browse/OSPRH-7644)

add supprot for limited extra bind mount suppport in edpm_nova

---

roles/edpm_kernel/tasks/kernelargs.yml

The EFI grub.cfg is being replaced with a RHEL style redirect[1] so that it no longer has to be updated along with the /boot/grub2/grub.cfg. This change removes the tasks which overwrite the EFI grub.cfg, which undoes the fix in [1].
An equivalent change is occuring for 17.1 images[2] and for upgrade paths into 17.1[3] so we will be able to ensure any host upgrading to 18.0 will have the correct redirect grub.cfg in place.
[1] https://github.com/openstack-k8s-operators/edpm-image-builder/pull/30
[2] https://code.engineering.redhat.com/gerrit/c/openstack-tripleo-image-elements/+/452100
[3] https://code.engineering.redhat.com/gerrit/c/tripleo-ansible/+/452086
https://code.engineering.redhat.com/gerrit/c/openstack-tripleo-heat-templates/+/452099

Stop overwriting EFI grub.cfg

---

playbooks/configure_os.yml
roles/edpm_extra_mounts/defaults/main.yml
roles/edpm_extra_mounts/handlers/main.yml
roles/edpm_extra_mounts/meta/argument_specs.yml
roles/edpm_extra_mounts/meta/main.yml
roles/edpm_extra_mounts/molecule/default/collections.yml
roles/edpm_extra_mounts/molecule/default/converge.yml
roles/edpm_extra_mounts/molecule/default/molecule.yml
roles/edpm_extra_mounts/molecule/default/prepare.yml
roles/edpm_extra_mounts/molecule/default/verify.yml
roles/edpm_extra_mounts/molecule/molecule_config.yaml
roles/edpm_extra_mounts/molecule/vagrant/README.md
roles/edpm_extra_mounts/molecule/vagrant/collections.yml
roles/edpm_extra_mounts/molecule/vagrant/molecule.yml
roles/edpm_extra_mounts/molecule/vagrant/verify.yml
roles/edpm_extra_mounts/tasks/extra_mounts.yml
roles/edpm_extra_mounts/tasks/main.yml
roles/edpm_extra_mounts/vars/main.yml

Default mounts are added early on bootstrap stage, by default create 1GB and 2MB huge pages
Extra mounts are empty by default and
are required to allow mounting /var/lib/nova/instance in nfs. This part is called on configure-os stage when network elements are created
Closes: https://issues.redhat.com/browse/OSPRH-7088

Add edpm_extra_mounts role to configure default and extra mounts

---

roles/edpm_kernel/vars/main.yml

Logging martian packets is done via printk. Depending on the default console configuration, it may cause writing on a serial line. Some UART controllers are slow, and it may stall CPUs for up to 200ms. When this logging happens, it causes random latency issues.
Disable logging of martian packets by default. It can be enabled for debugging purposes.

Disable martian packts logging as default

---

roles/edpm_nftables/defaults/main.yml
roles/edpm_nftables/tasks/configure.yml
roles/edpm_nftables/templates/base-rules.yaml.j2

Depending on the console redirection configured on boot, logging packets before dropping them may cause excessive latency issues. Sometimes this can even stall a CPU for 200ms with some UART controllers and console=ttyS0.
In most openstack deployments, the is a bridge that may receive random DHCP requests. For example, when creating a lot of SRIOV VFs, NetworkManager will try to configure them with DHCP and broadcast packets. This causes the packets to be received by all overcloud nodes and be dropped, e.g:
```
kernel: IN=ens8f0v2 OUT= MAC=ff:ff:ff:ff:ff:ff:2a:75:ff:3d:02:f0:08:00 SRC=0.0.0.0 DST=255.255.255.255 LEN=327 TOS=0x00 PREC=0xC0 TTL=64 ID=0 DF PROTO=UDP SPT=68 DPT=67 LEN=307
```
I could not find any motivation for the existence of this LOG rule. Not event in puppet tripleo where …

nftables: disable logging of dropped packets by default

---

roles/edpm_nftables/tasks/service-bootstrap.yml

Since we are defining firewall rules with `edpm_nftables` role (using `nftables` service), it's useless and potentially harmful keep firewalld enabled and running on the host.
Fixes: https://issues.redhat.com/browse/OSPRH-7739
Signed-off-by: Roberto Alfieri <ralfieri@redhat.com>

Disable firewalld service in `edpm_nftables` role

---

roles/edpm_update/defaults/main.yml

This change uses the original edpm_services list to determine which services will be updated, rather than inheriting the servicesOverride. This ensures that all services applied on the nodeSet will be updated during the minor update workflow.
Jira: https://issues.redhat.com/browse/OSPRH-8107

Don't use override services to determine update

---

roles/edpm_nftables/tasks/service-bootstrap.yml

Under some OS firewalld is not present, leading to the disabling task to fail. Avoid disabling it if not present.

Disable firewalld only when present

---

roles/edpm_nftables/tasks/service-bootstrap.yml

Follow up from comment in:
https://github.com/openstack-k8s-operators/edpm-ansible/pull/691
Adding the additional when condition if
status is not-found.

Disable firewalld when present, status not-found

---

roles/edpm_download_cache/tasks/container_images.yml
roles/edpm_telemetry/defaults/main.yml
roles/edpm_telemetry/tasks/download_cache.yml

This PR adds telemetry and swift to download_cache.
After the download_cache service runs I can see the ceilometer, node exporter and swift images correctly downloaded on the compute node.

[OSPRH-8216] Cache telemetry and swift images

---

roles/edpm_reboot/defaults/main.yaml
roles/edpm_reboot/meta/argument_specs.yml
roles/edpm_reboot/molecule/pre-adoption/converge.yml
roles/edpm_reboot/molecule/pre-adoption/molecule.yml
roles/edpm_reboot/molecule/pre-adoption/prepare.yml

Change edpm_reboot_old_tripleo_node_config_dir to check for tripleo files in /var/lib/config-data/puppet-generated instead of /var/lib/config-data. Path /var/lib/config-data is still being used in edpm for storing configs whereas puppet-generated is suppose to be used only in 17/wallaby. This will make sure for greenfield auto mode is back working, but reboot is skipped on tripleo nodes during adoption.
Resolves: [OSPRH-8415](https://issues.redhat.com//browse/OSPRH-8415)

Change pattern for detecting pre-adopted versus edpm nodes

---

roles/edpm_tripleo_cleanup/defaults/main.yml
roles/edpm_tripleo_cleanup/tasks/main.yml
zuul.d/projects.yaml

Apparently the 'when' condition on a block is not evaluated only before the block begins executing, but it is evaluated for each task separately. That means that if the fact that is used in the 'when' condition changes during the block execution, it affects whether the following tasks in the block will execute or not.
In our case, the "Filter for tripleo services" task set the tripleo_services fact, and due to that the following "Filter services in skip list" task never executed because the "when" condition on the block says to execute only if tripleo_services is empty.
I've pulled the two set_fact tasks into a single one to get around this issue, since i didn't want to pollute the facts list with a temporary fact. (Facts can't be undefined.)
Resolves: …

tripleo_cleanup: Fix a task that was always skipped and it shouldn't be

---

zuul.d/projects.yaml

This updates the github-check zuul layout to use the new name for the adoption jobs added in the depends-on.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2091
https://issues.redhat.com/browse/OSPRH-8452

Rename the data plane adoption github-check jobs for new naming scheme

---

roles/edpm_update/defaults/main.yml
roles/edpm_update/molecule/default/converge.yml

The list of service types is added as an ansible variable to the
inventory as edpm_service_types. This will be used instead of
edpm_services since service names could be any custom value.
edpm-ansible roles such as edpm_update, need a list of consistent
service identifiers (types instead of names), so it knows which other
roles to include for update tasks.
Depends-On: https://github.com/openstack-k8s-operators/openstack-operator/pull/962
Jira: https://issues.redhat.com/browse/OSPRH-8107

Use edpm_service_types in edpm_update

---

roles/edpm_bootstrap/tasks/download_cache.yml
roles/edpm_bootstrap/tasks/packages.yml
roles/edpm_kernel/tasks/download_cache.yml
roles/edpm_kernel/tasks/main.yml
roles/edpm_libvirt/tasks/download_cache.yml
roles/edpm_logrotate_crond/tasks/download_cache_packages.yml
roles/edpm_logrotate_crond/tasks/install.yml
roles/edpm_network_config/tasks/download_cache.yml
roles/edpm_network_config/tasks/main.yml
roles/edpm_network_config/tasks/network_config.yml
roles/edpm_ovs/tasks/download_cache.yml
roles/edpm_podman/tasks/buildah_login.yml
roles/edpm_podman/tasks/download_cache.yml
roles/edpm_podman/tasks/install.yml
roles/edpm_sshd/tasks/download_cache.yml
roles/edpm_sshd/tasks/install.yml
roles/edpm_tuned/tasks/download_cache.yml
roles/edpm_tuned/tasks/install.yml

Otherwise it fails with below in case the package is not available, i.e correct repos are not enabled.
ASK [osp.edpm.edpm_bootstrap : Deploy network-scripts required for deprecated network service] ***
fatal: [edpm-compute-1]: FAILED! => {"msg": "The conditional check 'edpm_bootstrap_legacy_network_packages_result.rc == 0' failed. The error was: error while evaluating conditional (edpm_bootstrap_legacy_network_packages_result.rc == 0): 'dict object' has no attribute 'rc'. 'dict object' has no attribute 'rc'"}
jira: https://issues.redhat.com/browse/OSPRH-8911

Fix result check syntax

---

roles/edpm_libvirt/molecule/default/verify.yml

libvirt 10.5.0 re-implemented virt-pki-validate in c and changed some of the required values
for the certs. this pr disable the invocation of virt-pki-validate temporarily until we can address the warnings  post ga.

Changing cert permissions to comply with changed virt-pki-validate rules

---

roles/edpm_telemetry/molecule/default/converge.yml
roles/edpm_telemetry_logging/molecule/default/converge.yml
roles/edpm_telemetry_logging/tasks/configure.yml

It was detected in the CI of the PR https://github.com/openstack-k8s-operators/telemetry-operator/pull/457

Re-introduce a become: true that was previously wrongly removed

---

roles/edpm_nova/tasks/install.yml
roles/edpm_nova/templates/nova_compute.json.j2

The situation requiring the conditional implemented in 86502f8bef186b9d7da71c3d927c8752f64a716f has been resolved since merge of 05539a624fcd8baf60dcec6a60c7928edd9f4252 into dataplane-operator.
The conditional serves no further purpose and should be safe to remove.

Resolving TODO conditional nova template rendering

---

roles/edpm_libvirt/molecule/default/verify.yml
roles/edpm_libvirt/tasks/configure.yml

Resolves: [OSPCIX-393](https://issues.redhat.com//browse/OSPCIX-393) 
Permissions for directories are now set according to new virt-pki-validate recommendations. Instead of checking return code of the tool, we are now matching on output. This is because even a single warning changes rc to 1.

Restoring virt-pki-validate check in molecule test

---

roles/edpm_frr/defaults/main.yml
roles/edpm_frr/meta/argument_specs.yml
roles/edpm_frr/templates/daemons.j2

https://docs.frrouting.org/en/latest/zebra.html#cmdoption-zebra-K
"If this option is specified, the graceful restart time is TIME seconds. Zebra, when started, will read in routes. Those routes that Zebra identifies that it was the originator of will be swept in TIME seconds. If no time is specified then we will sweep those routes immediately."

Allow setting Zebra graceful_restart time

---

docs/docs-requirements.txt
meta/runtime.yml
molecule-requirements.txt
openstack_ansibleee/Dockerfile
roles/edpm_bootstrap/molecule/molecule_config.yaml

We can safely move on to the 2.15.* as there were no real breaking changes, with possible exception of `callback_whitelist`. [0]
[0] https://github.com/ansible/ansible/blob/stable-2.15/changelogs/CHANGELOG-v2.15.rst#id34

Releasing version constraint to allow versions 2.15.0

---

docs/docs-requirements.txt
meta/runtime.yml
molecule-requirements.txt
openstack_ansibleee/Dockerfile
roles/edpm_bootstrap/molecule/molecule_config.yaml

Previously deprecated callback_whitelist configuration option was replaced with callback callbacks_enabled in 2.15.0.
Upstream ee image was moved to tag 0.21.0
Signed-off-by: Jiri Podivin <jpodivin@gmail.com>
(cherry picked from commit f1eb19766c3d3251894105c6e55cea07eab89500)
Resolves: https://issues.redhat.com/browse/OSPCIX-429

Releasing version constraint to allow versions >= 2.15.0

---

roles/edpm_kernel/molecule/kernelargs-update-substring/converge.yml
roles/edpm_kernel/molecule/kernelargs-update-substring/test_vars.yml
roles/edpm_kernel/molecule/kernelargs-update-substring/verify.yml
roles/edpm_kernel/tasks/kernelargs.yml

The conditions required to enter the kernel args configuration block have been refactored.
The regular expression that checks for the `edpm_kernel_args` variable value presence in the command line arguments has been rewritten to intercept the substrings of the same parameters.
Also, the molecule test for this particular scenario, `kernelargs-update-substring` has been rewritten to catch these kind of errors.

[edpm_kernel] Improved kernel args block conditions

---

roles/edpm_frr/templates/frr.yaml.j2
roles/edpm_neutron_dhcp/templates/neutron_dhcp_agent.yaml.j2
roles/edpm_neutron_metadata/templates/ovn_metadata_agent.yaml.j2
roles/edpm_neutron_ovn/templates/ovn_agent.yaml.j2
roles/edpm_neutron_sriov/templates/neutron_sriov_agent.yaml.j2
roles/edpm_ovn/templates/ovn_controller.yaml.j2
roles/edpm_ovn_bgp_agent/templates/bgp_ovn_controller.yaml.j2
roles/edpm_ovn_bgp_agent/templates/nb_db_server.yaml.j2
roles/edpm_ovn_bgp_agent/templates/northd.yaml.j2
roles/edpm_ovn_bgp_agent/templates/ovn_bgp_agent.yaml.j2
roles/edpm_ovn_bgp_agent/templates/sb_db_server.yaml.j2
roles/edpm_swift/templates/rsync.yaml.j2
roles/edpm_swift/templates/swift_account_auditor.yaml.j2
roles/edpm_swift/templates/swift_account_reaper.yaml.j2
roles/edpm_swift/templates/swift_account_replicator.yaml.j2
roles/edpm_swift/templates/swift_account_server.yaml.j2
roles/edpm_swift/templates/swift_container_auditor.yaml.j2
roles/edpm_swift/templates/swift_container_replicator.yaml.j2
roles/edpm_swift/templates/swift_container_server.yaml.j2
roles/edpm_swift/templates/swift_container_updater.yaml.j2
roles/edpm_swift/templates/swift_object_auditor.yaml.j2
roles/edpm_swift/templates/swift_object_expirer.yaml.j2
roles/edpm_swift/templates/swift_object_replicator.yaml.j2
roles/edpm_swift/templates/swift_object_server.yaml.j2
roles/edpm_swift/templates/swift_object_updater.yaml.j2

They have no relevance atm as containers are started individually with edpm_container_manage/edpm_container_standalone.

Remove start_order from container configs

---

roles/edpm_kernel/tasks/kernelargs.yml

The type of edpm_kernel_args could be a str, so both types need to be
checked, otherwise the whole block is skipped.
Jira: [OSPRH-10007](https://issues.redhat.com//browse/OSPRH-10007)

Check for AnsibleUnicode or str for edpm_kernel_args

---

roles/edpm_container_standalone/defaults/main.yml
roles/edpm_container_standalone/meta/argument_specs.yml
roles/edpm_neutron_dhcp/tasks/run.yml
roles/edpm_neutron_sriov/tasks/run.yml
roles/edpm_nova/tasks/install.yml
roles/edpm_telemetry/tasks/install.yml

Remove some debug vars

---

roles/edpm_swift/tasks/run.yml
roles/edpm_telemetry/defaults/main.yml
roles/edpm_telemetry/tasks/install.yml

This changes telemetry and swift containers.

Don't use multiple tasks to start containers of a service

---

roles/edpm_extra_mounts/defaults/main.yml
roles/edpm_extra_mounts/meta/argument_specs.yml
roles/edpm_extra_mounts/molecule/default/converge.yml
roles/edpm_extra_mounts/tasks/extra_mounts.yml

hugepages shoudn't have mounted path, only name
jira: https://issues.redhat.com/browse/OSPRH-10218

Fix creating huge pages

---

zuul.d/jobs.yaml
zuul.d/projects.yaml

Without it, we miss testing some of the roles like edpm-ssh-known-hosts.
Let's see if adding a parent from openstack-operator works. Else we have to copy the full definition.
jira: https://issues.redhat.com/browse/OSPRH-10307

Add multinode tempest job to edpm-ansible

---

roles/edpm_frr/meta/argument_specs.yml

We collect  ansible_facts when required, don't fail when validating arguments.
Jira: https://issues.redhat.com/browse/OSPRH-10338

Don't fail in validating arguments if ansible_facts have not been gathered yet

---

roles/edpm_update/tasks/containers.yml

The iscsid and multipathd containers need to be updated on nodes running the "nova" service. These storage containers are deployed wherever Nova is deployed.
Jira: [OSPRH-9712](https://issues.redhat.com//browse/OSPRH-9712)

Handle storage containers during EDPM update

---

roles/edpm_neutron_dhcp/tasks/bootstrap.yml
roles/edpm_neutron_metadata/tasks/bootstrap.yml
roles/edpm_neutron_ovn/tasks/bootstrap.yml
roles/edpm_ovn/tasks/bootstrap.yml
roles/edpm_ovn_bgp_agent/tasks/configure.yml
roles/edpm_ovn_bgp_agent/tasks/configure_ovn.yml

Currently each depending role has his own version of
ovs installation with hardcoded package name, this leads
to ovs upgrade during adoption and cause network downtime.
Reusing edpm_ovs role for ovs installation to avoid
the issue as it has option to override rpm name and
override is used during adoption to avoid ovs upgrade.
Related-Issue: [OSPRH-10283](https://issues.redhat.com//browse/OSPRH-10283)

Use edpm_ovs role for ovs installation

---

roles/edpm_neutron_dhcp/tasks/configure.yml
roles/edpm_neutron_dhcp/tasks/run.yml
roles/edpm_neutron_metadata/tasks/configure.yml
roles/edpm_neutron_metadata/tasks/run.yml
roles/edpm_neutron_ovn/tasks/configure.yml
roles/edpm_neutron_ovn/tasks/run.yml
roles/edpm_neutron_sriov/tasks/configure.yml
roles/edpm_neutron_sriov/tasks/run.yml
roles/edpm_ovn/tasks/configure.yml
roles/edpm_ovn/tasks/run.yml
roles/edpm_ovn_bgp_agent/tasks/configure.yml
roles/edpm_ovn_bgp_agent/tasks/run.yml
roles/edpm_ovn_bgp_agent/tasks/run_ovn.yml

The logic to determine whether to mount a cacert bundle was mistakenly placed in configure.yml instead of run.yaml where the templates that use this logic are generated. (run.yaml and run_ovn.yaml)  This breaks updates which execute run.yaml instead of configure.yaml
This patch moves the logic to the right place.
Resolves: https://issues.redhat.com/browse/OSPRH-10450

Fix CAcert mounting

---

roles/edpm_tripleo_cleanup/molecule/default/converge.yml
roles/edpm_tripleo_cleanup/molecule/default/create_mock_service.yml
roles/edpm_tripleo_cleanup/molecule/default/prepare.yml
roles/edpm_tripleo_cleanup/molecule/default/verify.yml
roles/edpm_tripleo_cleanup/tasks/main.yml
roles/edpm_tripleo_cleanup/tasks/remove_unit_files.yml

Previously edpm_tripleo_cleanup role was cleaning old service files only from the /usr/lib/systemd/system location but it seems that some services, like e.g. neutron and nova related things have their service files created in the /etc/systemd/system location.
This patch adds cleaning of the service files also from the /etc/systemd/system location.
Closes-bug: #[OSPRH-6703](https://issues.redhat.com//browse/OSPRH-6703)

Cleanup Tripleo systemd services from the /etc/systemd location also

---

docs/docs-requirements.txt

Latest antsibull-docs 2.15.0 uses pydantic v2 which has broken the way we use it to override documentation argspec parsing.

Pin antsibul-docs to fix html_docs

---

roles/edpm_podman/defaults/main.yml
roles/edpm_podman/meta/argument_specs.yml
roles/edpm_podman/tasks/install.yml

If we determine that the OCP cluster is deployed using a disconnected or private registry we will use OCP's registries.conf for consistency purposes. This change adds two values 'edpm_podman_registries_conf' and 'edpm_podman_disconnected_ocp'. These values are both provided to us via the openstack-operator dataplane utils package based on the logic implemented in: https://github.com/openstack-k8s-operators/openstack-operator/pull/1098
Depends-On: https://github.com/openstack-k8s-operators/openstack-operator/pull/1098
Jira: https://issues.redhat.com/browse/OSPRH-10304

Use OCP registries.conf with disconnected

---

roles/edpm_pre_adoption_validation/defaults/main.yml
roles/edpm_pre_adoption_validation/meta/argument_specs.yml
roles/edpm_pre_adoption_validation/molecule/hostname-adoption-positive/molecule.yml
roles/edpm_pre_adoption_validation/molecule/hostname-greenfield/molecule.yml
roles/edpm_pre_adoption_validation/molecule/hostname-service-config-canonical-mismatch/molecule.yml
roles/edpm_pre_adoption_validation/molecule/hostname-service-config-hostname-mismatch/molecule.yml
roles/edpm_pre_adoption_validation/molecule/kernel-args-existing-args/molecule.yml
roles/edpm_pre_adoption_validation/molecule/kernel-args-new-args/molecule.yml
roles/edpm_pre_adoption_validation/molecule/kernel-args-new-hugepages/molecule.yml
roles/edpm_pre_adoption_validation/molecule/kernel-args-no-args/molecule.yml
roles/edpm_pre_adoption_validation/molecule/machined-check-fail/converge.yml
roles/edpm_pre_adoption_validation/molecule/machined-check-fail/molecule.yml
roles/edpm_pre_adoption_validation/molecule/machined-check-fail/prepare.yml
roles/edpm_pre_adoption_validation/molecule/tuned-no-change/molecule.yml
roles/edpm_pre_adoption_validation/molecule/tuned-no-profile/molecule.yml
roles/edpm_pre_adoption_validation/tasks/machined.yml

Fail pre-adoption check, if systemd-container package is missing. The package must be pre-installed to not affect running workloads during EDPM adoption.
Related molecule fix: use validations enablement feature flags
to properly isolate testing cases.
JIRA: [OSPRH-10318](https://issues.redhat.com/browse/OSPRH-10318)

Add pre-adoption check for machined

---

roles/edpm_telemetry_power_monitoring/defaults/main.yml

The configurations for ipmi agent service in ansibleee pod would be stored under "/var/lib/openstack/configs/telemetry-power-monitoring" and not "/var/lib/openstack/configs/telemetry".

Fix ceilometer ipmi agent volume mounts

---

plugins/modules/edpm_container_manage.py

Don't start container if restarted is set
If the container_manage is called with `restart` set, it means the
systemd handles the restart. In such case, we do not want containers to
be started because they will be started later by the systemd.
Resolves: [OSPRH-9812](https://issues.redhat.com//browse/OSPRH-9812)

Change action for config with `restart` in container_manage to `created`

---

roles/edpm_telemetry/defaults/main.yml
roles/edpm_telemetry/meta/argument_specs.yml
roles/edpm_telemetry/tasks/install.yml
roles/edpm_telemetry/templates/podman_exporter.json.j2

This PR adds prometheus-podman-exporter container deployment
which serves for reporting health of containerized services.
Related: [OBSDA-574](https://issues.redhat.com/browse/OBSDA-574)
Related: [OSPRH-1052](https://issues.redhat.com/browse/OSPRH-1052)
Closes: [OSPRH-5007](https://issues.redhat.com/browse/OSPRH-5007)

Add prometheus-podman-exporter deployment

---

roles/edpm_telemetry_power_monitoring/defaults/main.yml
roles/edpm_telemetry_power_monitoring/meta/argument_specs.yml
roles/edpm_telemetry_power_monitoring/templates/kepler.json.j2

Since, ipmi agent is deployed by power monitoring role it's configuration should not be stored with telemetry services. This is necessary since both require different polling.yaml files.

Do not store power monitoring config files with telemetry

---

plugins/action/container_systemd.py
plugins/filter/haskey.yml
plugins/filter/helpers.py
plugins/modules/edpm_container_manage.py
plugins/modules/edpm_derive_pci_passthrough_devicespec.py
plugins/modules/edpm_os_net_config.py
plugins/modules/edpm_os_net_config_mappings.py
roles/edpm_container_manage/tasks/create.yml

We have accumulated quite a bit of idiosyncracies in our python code. This doesn't resolve all of them by any means, but it does take care of some of the most egregious ones. Dead code, useless imports, duplication and typos are all included. 
None of these changes should alter the way our code works. I've tried to avoid veering into full on refactor with this. That being said there is one minor change of `osp.edpm.haskey` filter API. However the filter in question is only used by one role, so it shouldn't have any adverse effects. 
Normally I would squash this. But since most of these are rather disjoint issues, I can't help but feel that it would make a mess of blame for whoever will follow. So I'm keeping the commits separate, unless people insist on squashing.

Stylistic adjustments for modules, plugins and filters

---

roles/edpm_neutron_metadata/defaults/main.yml
roles/edpm_neutron_metadata/meta/argument_specs.yml

This was set by default to '2' but according to the KCS article [1] it is recommended to have it set to '1'. If necessary it can be overwritten through the OpenStackDataPlaneNodeSet CR.
[1] https://access.redhat.com/solutions/6666911
Closes: #[OSPRH-10780](https://issues.redhat.com//browse/OSPRH-10780)

Change default number of ovn-metadata-workers to 1

---

openstack_ansibleee/Dockerfile
plugins/filter/helpers.py
plugins/modules/edpm_nftables_from_files.py
plugins/modules/edpm_nftables_snippet.py

As [quay.io/ansible/creator-ee](https://quay.io/repository/ansible/creator-ee?tab=tags&tag=latest)  is no longer maintained: https://github.com/ansible/creator-ee
closes [OSPRH-10743](https://issues.redhat.com//browse/OSPRH-10743)

Replace creator-ee with ansible-dev-tools image

---

roles/edpm_pre_adoption_validation/molecule/machined-check/converge.yml
roles/edpm_pre_adoption_validation/molecule/machined-check/molecule.yml
roles/edpm_pre_adoption_validation/molecule/machined-check/prepare.yml
roles/edpm_pre_adoption_validation/tasks/machined.yml

Fix validate systemd-container package task
Add postitive check test case
Include machined task instead of tuned
JIRA: #[OSPRH-10318](https://issues.redhat.com/browse/OSPRH-10318)

Fix validate systemd-container package task

---

roles/edpm_frr/tasks/configure.yml
roles/edpm_users/tasks/create_users_and_groups.yml

This seems broken with ansible 2.17.x. Also the current logic of running certain tasks for failed hosts won't work with `any_errors_fatal: true` as it would run them for all nodes.
Jira: https://issues.redhat.com/browse/OSPRH-11264

Don't use rescue with any_errors_fatal: true

---

.pre-commit-config.yaml
molecule/test-helpers/verify_podman.yaml
roles/edpm_nova/handlers/main.yml
roles/edpm_nova/tasks/configure.yml
roles/edpm_nova/tasks/install.yml
roles/edpm_nova/templates/config.json.j2
roles/edpm_nova/templates/nova_compute_init.json.j2
roles/edpm_nova/templates/nova_statedir_ownership.py
tests/test_nova_statedir_ownership.py

When /var/lib/nova is mounted via NFS, Kolla driven permissions change over that directory breaks access to it for VM instances.
That had been already solved in TripleO by introducing a custom init container that calls a script for smart ownership changes.
Reintroduce that script and tests from TripleO as is, and add a Nova EDPM init container to call it instead of recursive chown.
Jira: #[OSPRH-10729](https://issues.redhat.com/browse/OSPRH-10729)

Fix /var/lib/nova access for NFS shares

---

roles/edpm_tripleo_cleanup/tasks/remove_unit_files.yml

File names which should be removed had automatically added ".service" extension to the name which ended up with names like "tripleo-service.service.service" as names of the services already have ".service" suffix in their names so adding it to the file name wasn't necessary.
Closes: #[OSPRH-11323](https://issues.redhat.com//browse/OSPRH-11323)

Fix removal of old tripleo services unit files

---

.github/workflows/molecule.yaml
roles/edpm_multipathd/molecule/default/prepare.yml
roles/edpm_telemetry/molecule/default/prepare.yml
scripts/molecule_venv.sh

Currently it fails with
`statfs /etc/localtime: no such file or directory`

Fix edpm_multipathd and other molecule tests

---

roles/edpm_tripleo_cleanup/defaults/main.yml
roles/edpm_tripleo_cleanup/tasks/main.yml

There is not a way to mask services which have service files in /etc/systemd/system without first removing the file from there. This is intentional design.

Mask tripleo services after removing unit files

---

roles/edpm_ovn/molecule/availability_zones/verify.yml
roles/edpm_ovn/molecule/default/verify.yml
roles/edpm_ovn/molecule/enable_chassis_extport/verify.yml
roles/edpm_ovn/molecule/enable_chassis_gw/verify.yml
roles/edpm_ovn/molecule/enable_chassis_gw_and_extport/verify.yml
roles/edpm_ovn/molecule/hwoffload/verify.yml
roles/edpm_ovn/molecule/noconfig/verify.yml
roles/edpm_pre_adoption_validation/molecule/hostname-adoption-positive/converge.yml
roles/edpm_pre_adoption_validation/molecule/hostname-adoption-positive/prepare.yml
roles/edpm_pre_adoption_validation/molecule/hostname-greenfield/converge.yml
roles/edpm_pre_adoption_validation/molecule/hostname-greenfield/prepare.yml
roles/edpm_pre_adoption_validation/molecule/hostname-service-config-canonical-mismatch/converge.yml
roles/edpm_pre_adoption_validation/molecule/hostname-service-config-canonical-mismatch/prepare.yml
roles/edpm_pre_adoption_validation/molecule/hostname-service-config-hostname-mismatch/converge.yml
roles/edpm_pre_adoption_validation/molecule/hostname-service-config-hostname-mismatch/prepare.yml
roles/edpm_pre_adoption_validation/molecule/kernel-args-existing-args/converge.yml
roles/edpm_pre_adoption_validation/molecule/kernel-args-existing-args/prepare.yml
roles/edpm_pre_adoption_validation/molecule/kernel-args-new-args/converge.yml
roles/edpm_pre_adoption_validation/molecule/kernel-args-new-args/prepare.yml
roles/edpm_pre_adoption_validation/molecule/kernel-args-new-hugepages/converge.yml
roles/edpm_pre_adoption_validation/molecule/kernel-args-new-hugepages/prepare.yml
roles/edpm_pre_adoption_validation/molecule/kernel-args-no-args/converge.yml
roles/edpm_pre_adoption_validation/molecule/kernel-args-no-args/prepare.yml
roles/edpm_pre_adoption_validation/molecule/machined-check-fail/converge.yml
roles/edpm_pre_adoption_validation/molecule/machined-check-fail/prepare.yml
roles/edpm_pre_adoption_validation/molecule/machined-check/converge.yml
roles/edpm_pre_adoption_validation/molecule/machined-check/prepare.yml

We seem to have either missed these or were added later. This is one of the reasons these molecule tests take eternity to run.

Don't gather facts by default - Part 2 

---

roles/edpm_ovn_bgp_agent/templates/kolla_config/nb_db_server.yaml.j2
roles/edpm_ovn_bgp_agent/templates/kolla_config/sb_db_server.yaml.j2

The options added to the ovn-ctl commands used to create local OVN NB and SB DBs when TLS was enabled were wrong.
With this PR, the correct options are used instead.
Jira: [OSPRH-11428](https://issues.redhat.com//browse/OSPRH-11428)

[BGP] Fix TLS options for local OVN DB creation

---

roles/edpm_network_config/tasks/main.yml

When installing packages, we need to escalate privileges. This change adds become: true to the block that is installing NetworkManager-ovs for use with nmstate.
Jira: https://issues.redhat.com/browse/OSPRH-11663

Escalate privs for NetworkManager-ovs install

---

roles/edpm_nftables/defaults/main.yml
roles/edpm_nftables/molecule/action/converge.yml
roles/edpm_nftables/tasks/configure.yml

This change ensures that user provided rules are injected into the edpm_nftables_src directory and loaded during rule generation.
The change adds a new variable to facilitate a user interface for rule injection edpm_nftables_user_rules.
Jira: https://issues.redhat.com/browse/OSPRH-11347

Inject user provided nft rules

---

roles/edpm_podman/tasks/install.yml

This change switches the Ansible module from template to copy for writing the disconnected registries.conf file. Since trying to use `src` in the `template` module looks for a path and not content.
Jira: https://issues.redhat.com/browse/OSPRH-11475

Use copy instead of template for disconnected registries.conf

---

roles/edpm_bootc/meta/argument_specs.yml
roles/edpm_bootc/meta/main.yml
roles/edpm_bootc/molecule/default/collections.yml
roles/edpm_bootc/molecule/default/converge.yml
roles/edpm_bootc/molecule/default/molecule.yml
roles/edpm_bootc/molecule/default/prepare.yml
roles/edpm_bootc/tasks/main.yml
roles/edpm_bootstrap/tasks/bootstrap-common-post-packages.yml
roles/edpm_bootstrap/tasks/bootstrap-common-pre-packages.yml
roles/edpm_bootstrap/tasks/bootstrap.yml
roles/edpm_bootstrap/tasks/main.yml

- **Add edpm_bootc role**
- **Update edpm_bootstrap for bootc**
Jira: [OSPRH-11433](https://issues.redhat.com//browse/OSPRH-11433)
Jira: [OSPRH-11505](https://issues.redhat.com//browse/OSPRH-11505)

Initial bootc support

---

roles/edpm_telemetry_power_monitoring/templates/kepler.json.j2

Kepler needs libvirt mount to fetch names assigned by Nova Also, remove a few flags of unwanted metrics.

Add missing libvirt mount to kepler

---

roles/edpm_telemetry_power_monitoring/templates/kepler.json.j2

Closes: [OSPRH-11890](https://issues.redhat.com/browse/OSPRH-11890)

Add missing mount required to capture GPU metrics

---

roles/edpm_sshd/tasks/configure.yml

This change switches the method we use to display the motd. Previously, we used PrintMotd in the sshd config. RHEL9 configures mod_motd.so in PAM, and as such the motd will be duplicated when using PrintMotd. To avoid this, we can configure the motd via PAM.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2329414

Use PAM for sshd Motd

---

roles/edpm_download_cache/tasks/container_images.yml

Fixing nova service name
closes [OSPRH-11908](https://issues.redhat.com//browse/OSPRH-11908)

Ensure edpm_iscsid and edpm_multipathd are cached

---

roles/edpm_sshd/defaults/main.yml
roles/edpm_sshd/meta/argument_specs.yml

This change explicitly sets PrintMotd to no in the sshd_config. PrintMotd defaults to yes, and we're now using PAM to manage our motd requirements in RHEL9:
https://www.man7.org/linux/man-pages/man8/pam_motd.8.html 
https://www.man7.org/linux/man-pages/man5/sshd_config.5.html

Explicitly set PrintMotd to no

---

roles/edpm_sshd/tasks/configure.yml

This partially reverts commit e032cf239ff7cf74912ec6308527846b69de4621. RHEL9 and greater will use PAM by default. We only need to ensure PrintMotd is set to "no" to avoid duplication of the motd message.
We changed the default for PrintMotd in:
https://github.com/openstack-k8s-operators/edpm-ansible/pull/838
This change ensures that we don't override the PrintMotd value and instead we allow users to be explicit about this, otherwise, we default to no.

Partial Revert "Use PAM for sshd Motd"

---

playbooks/redhat.yml

https://linux-system-roles.github.io/rhc/
closes [OSPRH-11938](https://issues.redhat.com//browse/OSPRH-11938)

Adding a playbook for managing RH subscription and Insights

---

roles/edpm_network_config/defaults/main.yml
roles/edpm_network_config/molecule/nmstate/converge.yml
roles/edpm_network_config/tasks/main.yml

"edpm_network_config_tool: nmstate" is experimental and officially
unsupported. This change will require users to explicitly opt-in to
using nmstate directly instead of using os-net-config+nmstate. It adds a
task that will fail unless edpm_network_config_tool_nmstate_override is
set to true (defaults to false).
Jira: https://issues.redhat.com/browse/OSPRH-12316

Document nmstate as experimental and require an override to use it

---

roles/edpm_iscsid/tasks/install.yml

When an EDPM node rebooted which runs a VM with iscsi-backed volume, 
it leaves node records under /var/lib/iscsi/nodes. 
While the records exist, iscsi-starter.service runs iscsi.service. 
Then it starts iscsid.service also.
To prevent this issue, we need to stop and disable iscsi-starter.service.
JIRA:[OSPRH-12372](https://issues.redhat.com/browse/OSPRH-12372)

Stop and disable iscsi-starter.service

---

.github/workflows/molecule.yaml

closes [OSPRH-11820](https://issues.redhat.com//browse/OSPRH-11820)

Only test modified roles

---

zuul.d/jobs.yaml

closes [OSPRH-11820](https://issues.redhat.com//browse/OSPRH-11820)

Skip molecule test for unmodified roles

---

roles/edpm_tripleo_cleanup/tasks/main.yml

In the role which cleans up old tripleo related systemd services this patch adds call for "systemctl daemon-reload" and "systemctl reset-failed <service_name>" for each tripleo service which was removed. This is done to make sure that those services aren't visible in the systemctl output with e.g. failure that unit file don't exists.
Closes: #[OSPRH-11323](https://issues.redhat.com//browse/OSPRH-11323)

[tripleo_cleanup] Add daemon-reload and reset-failed as last step

---

playbooks/configure_network.yml
roles/edpm_network_config/molecule/default/converge.yml
roles/edpm_network_config/molecule/default/prepare.yml
roles/edpm_network_config/tasks/main.yml

When edpm_network_config role uses os-net-config to perform host network configuration, duplicate DHCP requests from NM are causing connectivity issue. Eg.
https://issues.redhat.com/browse/OSPRH-9142
This fix prevents NM from configure DHCP by default
This PR replaces an older [PR](https://github.com/openstack-k8s-operators/edpm-ansible/pull/720)

Prevent NM from automatic (DHCP) configuration on ethernet devices

---

zuul.d/projects.yaml

In order to get proper feedback from the rdoproject.org/github-check, the noop job is added. This job should be kicked even if other jobs are not started as irrelevant-files are detected in change. Without noop job rdoproject.org/github-check is hanging with waiting for status to be reported message.

Add noop job to projects

---

playbooks/bootstrap.yml

When using `ansible.builtin.wait_for_connection`  `gather_facts` can't be true for the play.

Fix regression in check remote connections play

---

roles/edpm_update/tasks/containers.yml

When 'updates' service runs, it only calls install.yml from Nova service role, which is not sufficient to provide required configuration updates. Inlcude configure.yml as well to cover that for Nova service.
To properly address this for *all services* we should add migration/update tasks there, which can be called individually from the update playbook.
Jira: #[OSPRH-13415](https://issues.redhat.com/browse/OSPRH-13415)

Apply configuration tasks for Nova on updates

---

roles/edpm_network_config/defaults/main.yml
roles/edpm_network_config/meta/argument_specs.yml
roles/edpm_network_config/tasks/os_net_config.yml

This would allow to remove interfaces that exist but aren't specified in the provided nic config, if required.
jira: https://issues.redhat.com/browse/OSPRH-13433

Add ansible var to cleanup non configured interfaces

---

playbooks/configure_network.yml
playbooks/configure_os.yml
playbooks/download_cache.yml
playbooks/install_certs.yml
playbooks/install_os.yml
playbooks/libvirt.yml
playbooks/neutron_metadata.yml
playbooks/neutron_ovn.yaml
playbooks/nova.yml
playbooks/ovn.yml
playbooks/run_os.yml
playbooks/telemetry.yml
playbooks/validate_network.yml

We depend on a custom fact for bootc deployments. This change ensures we gather at least ansible_local facts at the beginning of each service.

Gather ansible_local facts at the start of each service

---

playbooks/bootstrap.yml
roles/edpm_bootstrap/defaults/main.yml
roles/edpm_bootstrap/tasks/bootstrap.yml
roles/edpm_bootstrap/tasks/swap.yml

The default path for a swapfile needs to be under a writeable location
for bootc. Use /var/swap. The value of the existing variable,
edpm_bootstrap_swap_path can't just be changed since there are already
existing deployments, so a new variable, edpm_bootstrap_swap_path_bootc
is added for bootc. An ansible task will select which variable to use
based on the type of system.

Re-enable swap for bootc

---

docs/source/roles/role-edpm_ovs_dpdk.rst
roles/edpm_ovs_dpdk/defaults/main.yml
roles/edpm_ovs_dpdk/meta/argument_specs.yml
roles/edpm_ovs_dpdk/tasks/configure.yml

This edpm_ovs_dpdk_lcore_list config is not
required now to enable ovs dpdk in EDPM
nodes.

Removing DPDK lcore list config

---

roles/edpm_telemetry/templates/node_exporter.json.j2

The dbus exclusive mount is preventing everything else to restart or to use it.
This solves the route cause for not being able to deploy an edpm twice.

node_exporter should not be mounting dbus

---

roles/edpm_podman/tasks/install.yml

Before this fix, the task name of writing registries.conf is the same between connected env and disconnected env. 
It requires to check the rendered registries.conf for identifying which is used.
To make it clear, this fix updates the name for disconnected ocp.

Update task name to clarify disconnected env

---

roles/edpm_download_cache/tasks/container_images.yml

Use the edpm_download_cache role for downloading the container images for the telemetry-power-monitoring service. This will fix container registry credential issues when running the edmp_telemetry_power_monitoring role.

[OSPRH-13840]use download role for powermonitoring

---

roles/edpm_download_cache/tasks/main.yml

Skip download_cache packages tasks with bootc

---

playbooks/configure_ovs_dpdk.yml
roles/edpm_bootstrap/meta/argument_specs.yml

This change is to fix the openvswitch package missing
issue during configure ovs dpdk for pre provisioned
EDPM nodes.
We already have ovs packages installation, ovs services
are enabled and running part in configure-network which
is common for all deployment.
To avoid issue in configure ovs dpdk, we are adding only
openvswitch package installation part and not using
existing edpm_ovs install.yml task to avoid complete
redundat like ovs services configuration, enable
and running part.

Openvswitch package install required

---

roles/edpm_frr/defaults/main.yml
roles/edpm_frr/molecule/default/converge.yml
roles/edpm_frr/tasks/configure.yml

This PR sets edpm_frr_bgp_uplinks default to empty list, sync'ing with
corresponding tripleo default value.
It also ensures that either edpm_frr_bgp_peers or edpm_frr_bgp_uplinks
have been configured.
If both are configured, only edpm_frr_bgp_peers is applied.
[OSPRH-14173](https://issues.redhat.com//browse/OSPRH-14173)

Use either edpm_frr_bgp_peers or edpm_frr_bgp_uplinks in frr.conf

---

roles/edpm_ceph_hci_pre/defaults/main.yml

Update edpm_ceph_hci_pre role since the default port for the dashboard was wrong as per the ceph docs.
https://docs.ceph.com/en/latest/mgr/dashboard/#host-name-and-port
Jira: https://issues.redhat.com/browse/OSPRH-14300

Change Ceph Dashboard port to 8443

---

roles/edpm_telemetry/templates/node_exporter.json.j2

Relabeling dbus socket introduced issues with systemd in the past. This patch reintroduces systemd collector for node_exporter without messing with selinux, but using root user instead.

Reintroduce systemd collector

---

docs/source/roles/role-edpm_network_config.rst
roles/edpm_network_config/defaults/main.yml
roles/edpm_network_config/meta/argument_specs.yml

We will switch this to cleanup the configurations not in `edpm_network_config_template` by default. This is required for provisioned nodes using vlan tagged ctlplane network. The ansible var could be set to false for cases where we want to keep the existing configuration.
This would also be useful when we want to change the initial configuration using `edpm_network_config_update` to cleanup whatever redundant interfaces created earlier.
Depends-On: https://github.com/openstack-k8s-operators/data-plane-adoption/pull/828
jira: https://issues.redhat.com/browse/OSPRH-13433

Flip the default for edpm_network_config_nonconfigured_cleanup

---

roles/edpm_nftables/tasks/configure.yml
roles/edpm_nftables/tasks/run.yml

This change ensures the custom nftables rules are always loaded by removing the conditional check and associated sential file. This is necessary since we're always loading the iptables compatibility rules and this sets the policy of the INPUT chain to accept. After our custom rules are configured, this policy should be reset to drop to ensure we're only allowing defined traffic and dropping anything that doesn't match a rule in the chain.
Jira: [OSPRH-14250](https://issues.redhat.com//browse/OSPRH-14250)

Always load custom nftables rules

---

roles/edpm_telemetry/defaults/main.yml
roles/edpm_telemetry/meta/argument_specs.yml
roles/edpm_telemetry/templates/firewall.yaml.j2
roles/edpm_telemetry/templates/openstack_network_exporter.json.j2
roles/edpm_telemetry/templates/openstack_network_exporter.yaml.j2

The telemetry role is used to install the openstack-network-exporter.
The upstream image is in place.  Can Merge.

telemetry-role: add support for the openstack-network-exporter

---

roles/edpm_network_config/defaults/main.yml
roles/edpm_network_config/meta/argument_specs.yml

While edpm_network_config_safe_defaults is true, os-net-config tries to configure DHCP to all physical interfaces and update resolv.conf. This behavior should not be default because a user cannot detect the failure by this.
To prevent the uninteded configuration, change the default to false.
Resolve: [OSPRH-14370](https://issues.redhat.com//browse/OSPRH-14370)

Change edpm_network_config_safe_defaults to false

---

roles/edpm_libvirt/molecule/default/prepare.yml
roles/edpm_nova/molecule/default/prepare.yml
roles/edpm_nova/tasks/update.yml
roles/edpm_ovs/molecule/common/prepare_base.yml
roles/edpm_update/tasks/containers.yml

Inlcuding configure tasks for nova role during updates doesn't work as there are no required data sources attached to osdpd calling the update service.
Introduce the update tasks which contents would be changing from release to release and include only tasks required to "migrate" the configuration and initialization logic of the nova EDPM service from A to B, then from B to C and so on.
When reproducing d/s, repo-setup fails on rhel during molecule
prepare because there is no RDO for rhel.
Specify centos9 distro for repo-setup explicitly.
Fix permissions to molecule CA public cert
Nova compute cannot start with the CA file created as 0600 and owned by
ansible user.
Change it to become world readable, so that nova stops failing to
access it in molecule tests. 
Related: …

Apply updates for edpm_nova role instead of config

---

roles/edpm_container_manage/templates/systemd-service.j2
roles/edpm_ovn_bgp_agent/templates/ovn_bgp_agent.yaml.j2

OVN BGP agent dynamically configures FRR daemon. In case the daemon is restarted the dynamic configuration is lost until the agent runs a periodic sync.
This can be prevented on systemd level that restarts the agent to perform the sync right after frr was restarted to minimize the downtime.
Resolves: [OSPRH-12363](https://issues.redhat.com//browse/OSPRH-12363)

Set OVN BGP agent as PartOf frr service

---

.github/workflows/molecule.yaml

github workflows molecule tests have not been run since https://github.com/openstack-k8s-operators/edpm-ansible/pull/853 was merged.

Run github workflows molecule when PR changes a role

---

roles/edpm_bootstrap/tasks/swap.yml

There was an extra newline at the end of the swap path value, causing
the path to be /var/swap\n instead of just /var/swap. Trim the newline
using |-.

Trim newline from end of swap path

---

roles/edpm_ovn_bgp_agent/molecule/default/prepare.yml
roles/edpm_ovn_bgp_agent/templates/ovn_bgp_agent.yaml.j2

Small correction was needed on:
https://github.com/openstack-k8s-operators/edpm-ansible/pull/887
[OSPRH-12363](https://issues.redhat.com//browse/OSPRH-12363)

Set OVN BGP agent as PartOf edpm_frr service

---

roles/edpm_tripleo_cleanup/tasks/main.yml

This patch removes masking old Tripleo services in systemd (makes them to be
symlinks to /dev/null). All those unit files are removed by the same
role so there should be no need to mask them before.
Closes-issue: #[OSPRH-11323](https://issues.redhat.com//browse/OSPRH-11323)

Don't mask old tripleo services in systemd during the cleanup

---

roles/edpm_frr/templates/frr.conf.j2

The frr version we use doesn't work well with "log syslog" configuration from a container.
However, when frr logs are sent to the frr container's stdout, they are written to the server's /var/log/messages and shown with journalctl.
This depends on an frr bug: [RHEL-83966](https://issues.redhat.com//browse/RHEL-83966)
[OSPRH-10204](https://issues.redhat.com//browse/OSPRH-10204)

[frr] Send logs to container's stdout

---

playbooks/nova_storage.yml
playbooks/reboot.yml

Adds the gathering of ansible local facts to the reboot.yml playbook.

Gather local facts for bootc

---

roles/edpm_telemetry/tasks/update.yml
roles/edpm_telemetry/templates/openstack_network_exporter.json.j2
roles/edpm_update/tasks/containers.yml

The openstack_network_exporter was not present in previous releases. Added code to check for the presence of the exporter and install if necessary before running through the update process.
[OSPRH-14841](https://issues.redhat.com//browse/OSPRH-14841)

update: Add update and install handling for openstack_network_exporter

---

.ansible-lint

We have decided as a project not to enforce handler usage, therefor we should add the no-handler filter to the ignore list, rather than having to noqa: no-handler throughout the codebase.

Ignore no-handler lint errors

---

roles/edpm_nftables/tasks/configure.yml
roles/edpm_nftables/tasks/run.yml

In cases where the iptables compatibility ruleset has already been added,
we can skip applying it again which will allow us to avoid reloading nftables
each deployment.
Jira: https://issues.redhat.com/browse/OSPRH-15473
Signed-off-by: Brendan Shephard <bshephar@redhat.com>

Nftables reload

---

plugins/modules/edpm_container_manage.py

Flake8 complains about how we're formatting the container volume string. This change ignores the following complaints:
flake8...................................................................Failed
- hook id: flake8
- exit code: 1
plugins/modules/edpm_container_manage.py:304:46: E231 missing whitespace after ':'
plugins/modules/edpm_container_manage.py:304:69: E231 missing whitespace after ':'
plugins/modules/edpm_container_manage.py:304:72: E231 missing whitespace after ','

Noqa on container volume formatting

---

roles/edpm_bootstrap/handlers/main.yml
roles/edpm_bootstrap/tasks/bootstrap.yml

Add CA cert to bootstrap service
We want to copy the combined-ca-cert-bundle to the compute nodes to
ensure that any third party certs are trusted.  Lets use the bootstrap
service to do this.  This change is paired with - but does not depend on
a change in openstack-operator that will ensure that the bootstrap service has the
cert bundle mounted to /var/lib/openstack/cacerts/bootstrap.
The relevant change is https://github.com/openstack-k8s-operators/openstack-operator/pull/1374
Jira: OSPRH-14205

Add CA cert to bootstrap service

---

playbooks/redhat.yml

A node can be running RHEL, but doesn't necessarly need to
register/subscribe.
This PR ensures the node is running RHEL (as before), but also checks we
have at least `rhc_auth` parameter defined, and not empty.
This should provide enough security to re-add the "redhat" service in
the default list.
Related-Issue: [OSPRH-15644](https://issues.redhat.com//browse/OSPRH-15644)

Consolidate "redhat" service conditions

---

roles/edpm_bootstrap/tasks/fips.yml

FIPS status can't be changed on a running bootc system. Add a warning if
a change is requesetd.
Jira: [OSPRH-11433](https://issues.redhat.com//browse/OSPRH-11433)

Do not change FIPS status for bootc and warn if requested

---

roles/edpm_telemetry_power_monitoring/tasks/configure.yml

Ansible lint was complaining about the jinja2 spacing used in the configure.yml playbook. This change fixes the spacing as per the suggestion from ansible-lint.

Make ansible-lint happy with telemetry_power_monititoring

---

playbooks/redhat.yml

In situations where we're unmarshaling data from json to form variables, it's possible that those values can be unmarshalled as floating point numbers. Which would be incompatible with the current org ID's. This change asserts that the type of number for rhc_organization should be an integer.
Jira: https://issues.redhat.com/browse/OSPRH-15097

Force rhc_organization variable to be interger

---

roles/edpm_update/defaults/main.yml
roles/edpm_update/tasks/bootc.yml

This PR adds the basic, preliminary handling for a bootc container upgrade. We simply perform a bootc switch to the image provided via the edpm_bootc_os_container_image variable. It's also necessary to skip other plays responsible for updating packages and kernels params.
Jira: https://issues.redhat.com/browse/OSPRH-14327

Preliminary bootc update handling

---

playbooks/configure_ovs_dpdk.yml

Also skip openvswitch package install when bootc. The package is already
installed in the base bootc image.
Jira: [OSPRH-11558](https://issues.redhat.com//browse/OSPRH-11558)

Gather local facts for configure_ovs_dpdk playbook

---

playbooks/update.yml

Needed by
https://github.com/openstack-k8s-operators/edpm-ansible/pull/905 which
uses the local fact in the edpm_update role.
Jira: [OSPRH-11584](https://issues.redhat.com//browse/OSPRH-11584)

Gather local facts for update.yml playbook

---

playbooks/telemetry_logging.yml
roles/edpm_telemetry_logging/tasks/configure.yml

Also skip package install of rsyslog-openssl when bootc. The package is
installed in the bootc image in
https://github.com/openstack-k8s-operators/edpm-image-builder/pull/70.
Jira: [OSPRH-11580](https://issues.redhat.com//browse/OSPRH-11580)
Jira: [OSPRH-11545](https://issues.redhat.com//browse/OSPRH-11545)

Gather local facts for playbooks/telemetry_logging.yml

---

roles/edpm_kernel/tasks/kernelargs.yml

Refactors tasks from kernelargs.yml into separate blocks of tasks, one
for package mode and one for image mode.
Jira: [OSPRH-11503](https://issues.redhat.com//browse/OSPRH-11503)

edpm_kernel bootc support

---

roles/edpm_network_config/tasks/download_cache.yml
roles/edpm_network_config/tasks/main.yml

This change is to fix the OVS NetworkManager plugin installation for os-net-config wnmstate provider.

OVS NetworkManager Plugin installation issue

---

roles/edpm_telemetry/templates/firewall.yaml.j2

This is required to enable Prom-Exporter in Ceilometer-IPMI 
https://github.com/openstack-k8s-operators/telemetry-operator/pull/678

Allow traffic for ceilometer-ipmi-prom-exporter

---

roles/edpm_bootstrap/tasks/fips_status.yml

Otherwise, it's considered a variable name.

fips_status: 'check' must be a string

---

playbooks/neutron_dhcp.yml

Needed to set the bootc fact so the ovs install is skipped since
edpm_ovs/tasks/install.yml gets included.
Jira: [OSPRH-11526](https://issues.redhat.com//browse/OSPRH-11526)
Jira: [OSPRH-11565](https://issues.redhat.com//browse/OSPRH-11565)

Gather local facts for neutron_dhcp playbook

---

roles/edpm_nodes_validation/defaults/main.yml
roles/edpm_nodes_validation/meta/argument_specs.yml
roles/edpm_nodes_validation/molecule/default/prepare.yml
roles/edpm_nodes_validation/molecule/default/test_vars.yml
roles/edpm_nodes_validation/tasks/main.yml

An FQDN should be set, and a validation is added to check. The
validation can be disabled with the edpm_nodes_validation_check_for_fqdn
variable.
Depends-On: https://github.com/openstack-k8s-operators/install_yamls/pull/797
Jira: https://issues.redhat.com/browse/OSPRH-6187
Jira: [OSPRH-16536](https://issues.redhat.com//browse/OSPRH-16536)

Check an FQDN is set

---

roles/edpm_telemetry/templates/firewall.yaml.j2
roles/edpm_telemetry_power_monitoring/templates/firewall.yaml.j2

This configuration should go into the edpm_telemetry_power_monitoring role, since that's what deploys the ipmi agent.

Allow traffic for the ceilometer_ipmi_prom_exporter in power_monitoring module

---

playbooks/update_services.yml
playbooks/update_system.yml
roles/edpm_update_services/defaults/main.yml
roles/edpm_update_services/meta/argument_specs.yml
roles/edpm_update_services/meta/main.yml
roles/edpm_update_services/molecule/default/converge.yml
roles/edpm_update_services/molecule/default/molecule.yml
roles/edpm_update_services/molecule/default/prepare.yml
roles/edpm_update_services/tasks/containers.yml
roles/edpm_update_services/tasks/main.yml
roles/edpm_update_services/tasks/packages.yml
roles/edpm_update_system/defaults/main.yml
roles/edpm_update_system/meta/argument_specs.yml
roles/edpm_update_system/meta/main.yml
roles/edpm_update_system/molecule/default/converge.yml
roles/edpm_update_system/molecule/default/molecule.yml
roles/edpm_update_system/molecule/default/prepare.yml
roles/edpm_update_system/molecule/kpatch/converge.yml
roles/edpm_update_system/molecule/kpatch/molecule.yml
roles/edpm_update_system/molecule/kpatch/prepare.yml
roles/edpm_update_system/tasks/kpatch.yml
roles/edpm_update_system/tasks/main.yml
roles/edpm_update_system/tasks/packages.yml

This splits edpm_update role into edpm_update_system and edpm_update_services.
The plan is that original edpm_update role and its dataplane service CRs will remain as-is for the time being to allow gradual rollout of the new procedure, and when we're happy with the new procedure, we'll drop the old one.
Resolves: https://issues.redhat.com/browse/OSPRH-16546

Add roles for separate update of services vs operating system

---

molecule/common/Containerfile.j2
molecule/common/test_deps/tasks/main.yml

In Podified land, we use https://github.com/openstack-k8s-operators/repo-setup to generate repos.
By using tripleo-repos for edpm-ansible molecule job testing causes dependency issue.
This pr
- Updates tripleo-repos instructions with repo-setup
- Fix ubi repos names
- replaces current-tripleo with current-podified

Replace tripleo-repos with repo-setup

---

playbooks/bootstrap.yml
roles/edpm_kernel/molecule/kernelargs-update-bootc/converge.yml
roles/edpm_kernel/molecule/kernelargs-update-bootc/molecule.yml
roles/edpm_kernel/molecule/kernelargs-update-bootc/test_kernelargs.yml
roles/edpm_kernel/molecule/kernelargs-update-bootc/verify.yml
roles/edpm_kernel/resources/molecule/prepare-bootc.yml
roles/edpm_kernel/tasks/kernelargs.yml

Additional fixes for bootc support for edpm_kernel module.
Jira: [OSPRH-11503](https://issues.redhat.com//browse/OSPRH-11503)

edpm_kernel: bootc support

---

roles/edpm_update_services/tasks/packages.yml
roles/edpm_update_system/tasks/kpatch.yml
roles/edpm_update_system/tasks/main.yml
roles/edpm_update_system/tasks/packages.yml

This implements three things requested in reviews of #962:
- Simpler and faster (fewer tasks executed) way of dealing with package exclusions.
- Reformulation of 'Apply package updates needed for service updates' into 'Apply essential package updates required by services'
- Making sure we have the latest kpatch package
Related: https://issues.redhat.com/browse/OSPRH-16546

Follow-ups from split update review

---

roles/edpm_update_services/defaults/main.yml
roles/edpm_update_services/meta/argument_specs.yml
roles/edpm_update_services/tasks/packages.yml
roles/edpm_update_system/defaults/main.yml
roles/edpm_update_system/meta/argument_specs.yml
roles/edpm_update_system/tasks/packages.yml

Add `edpm_update_system_include_packages` and `edpm_update_services_include_packages` variables.
Resolves: https://issues.redhat.com/browse/OSPRH-16543
Resolves: https://issues.redhat.com/browse/OSPRH-16544

Ability to customize the list of RPMs included in system and services update

---

roles/edpm_bootstrap/defaults/main.yml
roles/edpm_bootstrap/meta/argument_specs.yml
roles/edpm_bootstrap/tasks/bootstrap.yml
roles/edpm_network_config/defaults/main.yml
roles/edpm_network_config/meta/argument_specs.yml
roles/edpm_network_config/molecule/default/prepare.yml
roles/edpm_network_config/molecule/nmstate/prepare.yml
roles/edpm_network_config/tasks/dns_nm_configs.yml
roles/edpm_network_config/tasks/main.yml

This change is to update default os-net-config nmstate provider for network configuration.
jira: https://issues.redhat.com/browse/OSPRH-6809

Default nmstate provider changes

---

roles/edpm_bootstrap/defaults/main.yml
roles/edpm_frr/defaults/main.yml
roles/edpm_iscsid/defaults/main.yml
roles/edpm_kernel/defaults/main.yml
roles/edpm_libvirt/defaults/main.yml
roles/edpm_logrotate_crond/defaults/main.yml
roles/edpm_multipathd/defaults/main.yml
roles/edpm_network_config/defaults/main.yml
roles/edpm_neutron_dhcp/defaults/main.yml
roles/edpm_neutron_metadata/defaults/main.yml
roles/edpm_neutron_ovn/defaults/main.yml
roles/edpm_neutron_sriov/defaults/main.yml
roles/edpm_nova/defaults/main.yml
roles/edpm_ovn/defaults/main.yml
roles/edpm_ovn_bgp_agent/defaults/main.yml
roles/edpm_ovs/defaults/main.yml
roles/edpm_podman/defaults/main.yml
roles/edpm_sshd/defaults/main.yml
roles/edpm_swift/defaults/main.yml
roles/edpm_telemetry/defaults/main.yml
roles/edpm_telemetry_power_monitoring/defaults/main.yml
roles/edpm_tuned/defaults/main.yml

This pull request contains two changes proposed:
**Add variable to override all download retries**
> Currently each edpm_* role defines their own set of variables
> to control the number of retries and delay between retries
> when attempting to download and install the system packages.
> 
> There is over 20 such roles that involve it already, however
> there is no way to set those variables easily for all roles
> at once – the only option for someone is to set all about
> 40 variables in worst scenario.
> 
> This commit introduces two variables that would be used
> as first choice, if provided, by all the roles to allow
> the setting the download retries much easier.
**Increase default delay between download retries**
> From my experience on our testing environments,
> e.g. when there is …

Improvements to download retries in roles

---

docs/docs-requirements.txt
molecule-requirements.txt
openstack_ansibleee/requirements.txt

Ansible 2.19.0 has number of backward incompatible changes. Pin till we fix those.
jira: https://issues.redhat.com/browse/OSPRH-18609

Pin ansible-core to < 2.19.0

---

roles/edpm_ovs_dpdk/defaults/main.yml

Enable pmd auto lb by default for ovs-dpdk to ensure better load balancing across available CPU cores.
Depends-On: https://github.com/openstack-k8s-operators/edpm-ansible/pull/994
Jira: https://issues.redhat.com/browse/OSPRH-18437

Enable pmd auto lb by default for ovs-dpdk

---

docs/docs-requirements.txt
molecule-requirements.txt
openstack_ansibleee/requirements.txt
plugins/action/container_systemd.py
roles/edpm_kernel/tasks/hugepages.yml
roles/edpm_libvirt/tasks/virsh-secret.yml
roles/edpm_nftables/templates/dport.j2
roles/edpm_ovn/tasks/cleanup.yml
roles/edpm_ovs_dpdk/tasks/configure.yml
roles/edpm_pre_adoption_validation/tasks/kernel_args.yml
roles/edpm_ssh_known_hosts/tasks/main.yml

Ports edpm-ansible to ansible 2.19
Depends-On: https://github.com/openstack-k8s-operators/openstack-operator/pull/1547
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/3168
Depends-On: https://github.com/openstack-k8s-operators/data-plane-adoption/pull/1023
jira: https://issues.redhat.com/browse/OSPRH-18609

Make edpm-ansible ansible 2.19 compatible

---

roles/edpm_swift/templates/rsync.yaml.j2

rsync uses port 873 to replicate data between Swift storage nodes. Because it is running unprivileged it needs the NET_BIND_SERVICE cap to make this work by default without any customization.

Fix rsync permission issue for Swift

---

roles/edpm_network_config/tasks/package_management.yml

Some adoption jobs have issues when ensuring that network.service has been started possibly because of conflict with NetworkManager. We were not doing that earlier[1], so let's change that.
[1] https://github.com/openstack-k8s-operators/edpm-ansible/blob/18.0-fr2/roles/edpm_network_config/tasks/network_config.yml#L152C13-L159
jira: https://issues.redhat.com/browse/OSPCIX-1042
Related-Issue: https://issues.redhat.com/browse/OSPRH-19018

Don't try to ensure  network service is running

---

zuul.d/projects.yaml

Enable cifmw-crc-podified-edpm-baremetal-bootc job
Enables the podified-multinode-edpm-baremetal-bootc-pipeline on
edpm-ansible, which runs the new cifmw-crc-podified-edpm-baremetal-bootc
job.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/3311

Enable cifmw-crc-podified-edpm-baremetal-bootc job

---

roles/edpm_update/tasks/main.yml
roles/edpm_update_system/tasks/main.yml

The actual fact ansible_local.bootc needs to be defined, not just
ansible_local.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/3362
Jira: [OSPRH-20382](https://issues.redhat.com//browse/OSPRH-20382)

Check for ansible_local.bootc not just ansible_local
