openstack-k8s-operators/edpm-ansible

edpm_ansible/requirements.yml
requirements.yml

Signed-off-by: Roberto Alfieri <ralfieri@redhat.com>

added requirements.yml file

---

.github/workflows/documentation.yaml
edpm_ansible/playbooks/deploy-edpm-os-install.yml
edpm_ansible/roles/edpm_bootstrap/tasks/bootstrap.yml

following: https://github.com/openstack-k8s-operators/dataplane-operator/pull/36#discussion_r1113357435

Move OS install tasks into edpm_bootstrap

---

docs/source/roles/role-edpm_tuned.rst
edpm_ansible/playbooks/deploy-edpm-os-configure.yml
edpm_ansible/playbooks/deploy-edpm-os-install.yml
edpm_ansible/roles/edpm_tuned/defaults/main.yml
edpm_ansible/roles/edpm_tuned/meta/main.yml
edpm_ansible/roles/edpm_tuned/molecule/default/converge.yml
edpm_ansible/roles/edpm_tuned/molecule/default/molecule.yml
edpm_ansible/roles/edpm_tuned/molecule/default/prepare.yml
edpm_ansible/roles/edpm_tuned/molecule/isolated/converge.yml
edpm_ansible/roles/edpm_tuned/molecule/isolated/molecule.yml
edpm_ansible/roles/edpm_tuned/molecule/isolated/prepare.yml
edpm_ansible/roles/edpm_tuned/molecule/isolated/tests/test_isolated.py
edpm_ansible/roles/edpm_tuned/tasks/main.yml
edpm_ansible/roles/edpm_tuned/tasks/tuned_config.yml
edpm_ansible/roles/edpm_tuned/tasks/tuned_install.yml
edpm_ansible/roles/edpm_tuned/vars/redhat.yml

* Imported `tuned` role as `edpm_tuned`
* Fixed variables names according to new name
* Added documentation
* Added install and configure steps to playbooks.

added edpm_tuned role

---

edpm_ansible/roles/edpm_ssh_known_hosts/tasks/main.yml

dataplane-operator fails when trying to ssh into allovercloud

Replace allovercloud with all

---

edpm_ansible/roles/edpm_chrony/README.rst
edpm_ansible/roles/edpm_chrony/defaults/main.yml
edpm_ansible/roles/edpm_chrony/handlers/main.yml
edpm_ansible/roles/edpm_chrony/tasks/config.yml
edpm_ansible/roles/edpm_chrony/tasks/install.yml
edpm_ansible/roles/edpm_chrony/tasks/main.yml
edpm_ansible/roles/edpm_chrony/tasks/run.yml
edpm_ansible/roles/edpm_chrony/tasks/upgrade.yml
edpm_ansible/roles/edpm_chrony/templates/chrony.conf.j2
edpm_ansible/roles/edpm_chrony/tests/all.yml
edpm_ansible/roles/edpm_chrony/tests/config.yml
edpm_ansible/roles/edpm_chrony/tests/install.yml
edpm_ansible/roles/edpm_chrony/tests/upgrade.yml
edpm_ansible/roles/edpm_chrony/vars/RedHat.yml

Fix epdm -> edpm typos

---

docs/source/roles/role-edpm_growvols.rst

Added missing source documentation for `edpm_growvols` role

Added missing documentation for edpm_growvols role

---

playbooks/deploy_edpm_os_configure.yml
playbooks/deploy_edpm_os_install.yml
playbooks/deploy_edpm_os_run.yml
roles/edpm_frr/defaults/main.yml
roles/edpm_frr/meta/main.yml
roles/edpm_frr/tasks/configure.yml
roles/edpm_frr/tasks/install.yml
roles/edpm_frr/tasks/main.yml
roles/edpm_frr/tasks/run.yml
roles/edpm_frr/templates/daemons.j2
roles/edpm_frr/templates/frr.conf.j2
roles/edpm_frr/templates/frr.yaml.j2
roles/edpm_frr/templates/kolla_config/frr.yaml.j2
roles/edpm_network_config/templates/single_nic_vlans/single_nic_vlans_bgp.j2
roles/edpm_ovn_bgp_agent/defaults/main.yml
roles/edpm_ovn_bgp_agent/meta/main.yml
roles/edpm_ovn_bgp_agent/tasks/configure.yml
roles/edpm_ovn_bgp_agent/tasks/install.yml
roles/edpm_ovn_bgp_agent/tasks/main.yml
roles/edpm_ovn_bgp_agent/tasks/run.yml
roles/edpm_ovn_bgp_agent/templates/kolla_config/ovn_bgp_agent.yaml.j2
roles/edpm_ovn_bgp_agent/templates/ovn-bgp-agent.conf.j2
roles/edpm_ovn_bgp_agent/templates/ovn_bgp_agent.yaml.j2

This PR is adding the base support for deploying, configuring and running both FRR and OVN BGP Agent in the compute nodes

Initial support for frr and ovn_bgp-agent at EDPM

---

OWNERS_ALIASES

Add bshepar, kajinamit, rabi to edpm-approvers

---

roles/edpm_frr/defaults/main.yml
roles/edpm_ovn_bgp_agent/defaults/main.yml

... by TCIB frr image, because TripleO is being retired.

Replace TripleO frr image

---

roles/edpm_iscsid/tasks/configure.yml

This was missed in the last set of PRs.

Use root privileges to write to /etc/iscsi

---

roles/edpm_network_config/tasks/network_config.yml
zuul.d/jobs.yaml
zuul.d/projects.yaml

Also fixes privilege escalation for package installation.
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/292

Add epdm_baremetal job

---

.github/workflows/molecule.yaml
roles/edpm_ceph_client_files/molecule/default/converge.yml
roles/edpm_ceph_client_files/molecule/default/molecule.yml

Patch also introduces related job in github actions CI.

Fixing molecule tests of edpm_ceph_client_files so they can run locally

---

zuul.d/jobs.yaml
zuul.d/projects.yaml

It will help to test dataplane operator, nova operator and ansibleee-oeprator changes together.

Add edpm-ansible content provider job

---

README.md
docs/source/contributing_roles.rst
docs/source/testing_with_ansibleee.rst

- Add instructions for testing individual roles with molecule
- Add instructions to test local changes via ansibleee using NFS

Enhance instructions for testing local changes

---

roles/edpm_timezone/meta/argument_specs.yml
roles/edpm_timezone/molecule/default/molecule.yml
roles/edpm_timezone/molecule/default/verify.yml

Tests for the role were augmented with proper verification stage and example of usage.

Adding argument verification and documentation for edpm_timezone

---

OWNERS
OWNERS_ALIASES

Add compute-approvers

---

zuul.d/jobs.yaml

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/398

Disable running zuul edpm jobs when irrelevant files are modified

---

roles/edpm_sshd/meta/argument_specs.yml

This also provides documentation for the role.

Setting argspecs for the edpm_sshd role

---

roles/edpm_network_config/defaults/main.yml
roles/edpm_network_config/molecule/default/converge.yml
roles/edpm_network_config/tasks/os_net_config.yml

Reverts openstack-k8s-operators/edpm-ansible#225

Revert "Use edpm_network_config_override when defined"

---

roles/edpm_nova_libvirt/meta/argument_specs.yml

This is a tough one. Defaults contain lot of TODOs and I'm not exactly sure if/how were they resolved.
I'm also seeing lot of things that may no long er be necessary.

Argspecs for edpm_nova_libvirt role

---

scripts/test_roles.py

Test edpm_ovn when running execute_molecule_local

---

roles/edpm_telemetry/molecule/default/prepare.yml

... so that the content is consistent with the test files in telemetry-operator.

Update example kolla config file of ceilometer services in molecule

---

.github/workflows/molecule.yaml
roles/edpm_ovn/molecule/default/verify.yml
roles/edpm_ovn/tasks/firewall.yml
roles/edpm_ovn/tasks/install.yml
roles/edpm_ovn/tasks/main.yml

Without these genev/vxlan traffic across
edpm nodes is dropped.

[ovn] Add missing firewall rules

---

playbooks/select_kernel_ddp_package.yml
roles/edpm_ddp_package/tasks/main.yml

This change is to run DDP package selection only
when user provided dpm_ddp_package is different
than default value.

Select DDP package only when required

---

roles/edpm_container_manage/tasks/delete_orphan.yml

Context: https://github.com/openstack-k8s-operators/data-plane-adoption/pull/171#issuecomment-1745184297

Speed up Ceph exclude task

---

zuul.d/projects.yaml

Reverts openstack-k8s-operators/edpm-ansible#363

Revert "Drop baremetal job"

---

roles/edpm_ddp_package/meta/main.yml
roles/edpm_ddp_package/tasks/main.yml

Replaced a couple of shell commands with ansible native modules

Make `edpm_ddp_package` role compliant with ansible-lint `production` profile

---

.github/workflows/molecule.yaml
roles/edpm_ovn_bgp_agent/molecule/default/converge.yml
roles/edpm_ovn_bgp_agent/molecule/default/molecule.yml
roles/edpm_ovn_bgp_agent/molecule/default/prepare.yml
zuul.d/jobs.yaml
zuul.d/projects.yaml

This one has a lot of dependencies, so it calls other roles we have to set things up. 
Not an exactly isolated test, but it's about as close as I could get to one.

CI testing for edpm_ovn_bgp_agent role

---

playbooks/bootstrap.yml
playbooks/configure_network.yml

https://issues.redhat.com/browse/OSP-28971
Depends-On: https://github.com/openstack-k8s-operators/dataplane-operator/pull/476

Moved roles from `configure_network.yml` playbook to `bootstrap.yml` playbook

---

OWNERS_ALIASES
roles/edpm_neutron_dhcp/OWNERS
roles/edpm_neutron_metadata/OWNERS
roles/edpm_neutron_ovn/OWNERS
roles/edpm_neutron_sriov/OWNERS
roles/edpm_ovn/OWNERS

Slawek is knowledgeable enough to have wide access to everything other network-approvers group members have access to.

Add slawqo to network-approvers group

---

docs/source/testing_with_ansibleee.rst

- console code-block was escaping $ and # (copy/paste was breaking)
- add note about nfs-server and firewalld

Minor improvements on NFS docs

---

roles/edpm_ovn/molecule/default/verify-tasks.yml
roles/edpm_ovn/molecule/hwoffload/cleanup.yml
roles/edpm_ovn/molecule/hwoffload/collections.yml
roles/edpm_ovn/molecule/hwoffload/converge.yml
roles/edpm_ovn/molecule/hwoffload/molecule.yml
roles/edpm_ovn/molecule/hwoffload/prepare.yml
roles/edpm_ovn/molecule/hwoffload/test-data
roles/edpm_ovn/molecule/hwoffload/verify.yml
roles/edpm_ovn/tasks/configure.yml

The code was constructing a new dict but never applying it.

ovn: actually apply hw-offload setting

---

docs/source/roles/role-edpm_ovn_dpdk.rst
playbooks/configure_ovs_dpdk.yml
plugins/filter/cpu_mask.yml
plugins/filter/helpers.py
roles/edpm_ovs_dpdk/defaults/main.yml
roles/edpm_ovs_dpdk/meta/argument_specs.yml
roles/edpm_ovs_dpdk/meta/main.yaml
roles/edpm_ovs_dpdk/molecule/default/collections.yml
roles/edpm_ovs_dpdk/molecule/default/converge.yml
roles/edpm_ovs_dpdk/molecule/default/molecule.yml
roles/edpm_ovs_dpdk/molecule/default/prepare.yml
roles/edpm_ovs_dpdk/tasks/configure.yml
roles/edpm_ovs_dpdk/tasks/main.yml

This change is used to have custom ansible edpm
variables for OvS DPDK configurations.

NFV OvS DPDK Configuration Changes

---

roles/edpm_frr/molecule/default/converge.yml
roles/edpm_frr/molecule/default/molecule.yml
roles/edpm_frr/molecule/default/prepare.yml
roles/edpm_frr/molecule/default/verify.yml
roles/edpm_frr/tasks/configure.yml
roles/edpm_frr/tasks/install.yml
roles/edpm_frr/templates/kolla_config/frr.yaml.j2

Add molecule tests to frr component

Add molecule tests to frr component

---

openstack_ansibleee/edpm_entrypoint.sh

Depends-On: https://github.com/openstack-k8s-operators/openstack-ansibleee-operator/pull/246

Storing extra vars as a runner env file

---

roles/edpm_libvirt/molecule/default/test-helpers/verify_firewall.yaml
roles/edpm_libvirt/molecule/default/verify.yml
roles/edpm_libvirt/tasks/post-install.yml
roles/edpm_libvirt/templates/firewall.yaml
roles/edpm_libvirt/templates/qemu.conf

Parent PR: https://github.com/openstack-k8s-operators/edpm-ansible/pull/467
Implements: https://issues.redhat.com/browse/OSPRH-364

[edpm_libvirt]Open firewall for live migration traffic

---

roles/edpm_telemetry/molecule/default/prepare.yml
roles/edpm_telemetry/tasks/deploy_ceilometer.yml

Depends-On: https://github.com/openstack-k8s-operators/telemetry-operator/pull/244

Ceilometer will log to stdout, removing log dir creation

---

roles/edpm_telemetry/tasks/deploy_infra.yml

We need this collector to report state of running container and services.

Enable systemd collector for node_exporter

---

roles/edpm_libvirt/defaults/main.yml
roles/edpm_libvirt/meta/argument_specs.yml

unpin libvirt

---

roles/edpm_ddp_package/defaults/main.yml
roles/edpm_ddp_package/meta/argument_specs.yml
roles/edpm_ddp_package/molecule/default/converge.yml
roles/edpm_ddp_package/molecule/default/molecule.yml
roles/edpm_ddp_package/molecule/default/prepare.yml
roles/edpm_ddp_package/molecule/default/verify.yml
roles/edpm_ddp_package/tasks/main.yml

This change is to update the ddp package option role and also updating molecule tests.

Updated ddp package option role

---

roles/edpm_nova/molecule/default/prepare.yml
roles/edpm_nova/molecule/default/verify.yml
roles/edpm_nova/tasks/configure.yml

Fixes: [OSPRH-2369](https://issues.redhat.com/browse/OSPRH-2369)

Support removing custom nova-configs

---

roles/edpm_ovs_dpdk/defaults/main.yml
roles/edpm_ovs_dpdk/meta/argument_specs.yml
roles/edpm_ovs_dpdk/tasks/configure.yml

These updates have been taken from latest 17.1.z patches

Add support to configure ovs_dpdk shared_mem_pool and max_sleep_time

---

roles/edpm_neutron_ovn/defaults/main.yml
roles/edpm_neutron_ovn/meta/argument_specs.yml
roles/edpm_neutron_ovn/templates/ovn_agent.yaml.j2

Depends-On: https://github.com/openstack-k8s-operators/dataplane-operator/pull/851
Closes: [OSPRH-6499](https://issues.redhat.com//browse/OSPRH-6499)

[edpm_neutron_ovn] Add certs to container if tls enabled

---

roles/edpm_ovn_bgp_agent/defaults/main.yml
roles/edpm_ovn_bgp_agent/meta/argument_specs.yml
roles/edpm_ovn_bgp_agent/templates/kolla_config/bgp_ovn_controller.yaml.j2
roles/edpm_ovn_bgp_agent/templates/kolla_config/nb_db_server.yaml.j2
roles/edpm_ovn_bgp_agent/templates/kolla_config/northd.yaml.j2
roles/edpm_ovn_bgp_agent/templates/kolla_config/ovn_bgp_agent.yaml.j2
roles/edpm_ovn_bgp_agent/templates/kolla_config/sb_db_server.yaml.j2

Configure OVN DB client certs when enabled
Related: [OSPRH-6543](https://issues.redhat.com//browse/OSPRH-6543)

ovn_bgp_agent TLS

---

roles/edpm_nova/defaults/main.yml
roles/edpm_nova/templates/02-nova-host-specific.conf.j2

Related: [OSPRH-6173](https://issues.redhat.com//browse/OSPRH-6173)

Disable NBD TLS until libvirt/qemu issues are resolved

---

contribute/_skeleton_role_/defaults/main.yml.j2
contribute/_skeleton_role_/handlers/main.yml
contribute/_skeleton_role_/meta/main.yml.j2
contribute/_skeleton_role_/molecule/default/collections.yml
contribute/_skeleton_role_/molecule/default/converge.yml.j2
contribute/_skeleton_role_/molecule/default/molecule.yml
contribute/_skeleton_role_/molecule/default/prepare.yml
contribute/_skeleton_role_/tasks/main.yml.j2
contribute/_skeleton_role_/vars/main.yml.j2

- updated year in each file
- removed useless (auto)load of vars file based on OS
- fixed molecule files
- updated collection namespace in the metadata

[_skeleton_role_] year updated and fixes

---

roles/edpm_bootstrap/meta/argument_specs.yml
roles/edpm_bootstrap/tasks/packages.yml

Leftover from edpm_ovs role split[1].
[1] https://github.com/openstack-k8s-operators/edpm-ansible/pull/532

[edpm_bootstrap] Clear leftover from edpm_ovs split

---

.github/workflows/openstack-ansibleee-runner.yaml

https://github.com/openstack-k8s-operators/openstack-operator/pull/813#issuecomment-2134736006

Add current-podified tag

---

roles/edpm_install_certs/tasks/adoption.yml
roles/edpm_tripleo_cleanup/tasks/main.yml

Adopt (stop tracking) certs from tripleo
https://issues.redhat.com/browse/OSPRH-6619

Adopt (stop tracking) certs from tripleo

---

roles/edpm_libvirt/molecule/default/verify.yml
roles/edpm_libvirt/templates/qemu.conf.j2
roles/edpm_nova/defaults/main.yml

Closes: [OSPRH-6173](https://issues.redhat.com//browse/OSPRH-6173)

Re-enable live-migration NBD TLS

---

roles/edpm_nova/templates/nova_compute.json.j2

https://issues.redhat.com/browse/OSPCIX-194

Fixes mount issue when using NFS for nova

---

roles/edpm_ceph_client_files/tasks/main.yml
roles/edpm_frr/tasks/configure.yml
roles/edpm_ovn_bgp_agent/tasks/configure.yml
roles/edpm_telemetry/tasks/configure.yml

Minor alteration of existing code, normalizing the way we specify permissions.
Resolves: https://issues.redhat.com/browse/OSPRH-8981

Explicitly setting special permissions bits

---

roles/edpm_derive_pci_device_spec/tasks/derive_pci_device_spec.yml
roles/edpm_extra_mounts/tasks/extra_mounts.yml
roles/edpm_libvirt/tasks/configure.yml
roles/edpm_neutron_sriov/tasks/install.yml
roles/edpm_nova/tasks/configure.yml
roles/edpm_swift/tasks/configure.yml
roles/edpm_users/tasks/main.yml

Setting libvirt owner, resolving FIXME.
Resolves: [OSPRH-8904](https://issues.redhat.com//browse/OSPRH-8904)

Setting default ownership on file/dir creation

---

roles/edpm_neutron_dhcp/tasks/install.yml

Resolves: [OSPCIX-398](https://issues.redhat.com//browse/OSPCIX-398)

Elevating permissions for dir creation

---

roles/edpm_extra_mounts/defaults/main.yml
roles/edpm_extra_mounts/molecule/default/converge.yml

related: [OSPRH-9065](https://issues.redhat.com/browse/OSPRH-9065)

Fix default hugepages group

---

docs/source/testing_with_ansibleee.rst

Also adds insecure option in /etc/exports[1]
[1] https://access.redhat.com/solutions/3773891

Fix links for setting nfs server on dev system

---

roles/edpm_download_cache/defaults/main.yml
roles/edpm_download_cache/meta/argument_specs.yml
roles/edpm_download_cache/molecule/default/converge.yml
roles/edpm_frr/molecule/default/converge.yml
roles/edpm_frr/tasks/download_cache.yml
roles/edpm_iscsid/tasks/download_cache.yml
roles/edpm_logrotate_crond/tasks/download_cache_images.yml
roles/edpm_multipathd/tasks/download_cache.yml
roles/edpm_neutron_dhcp/tasks/download_cache.yml
roles/edpm_neutron_metadata/tasks/download_cache.yml
roles/edpm_neutron_ovn/tasks/download_cache.yml
roles/edpm_neutron_sriov/tasks/download_cache.yml
roles/edpm_nova/tasks/download_cache.yml
roles/edpm_ovn/tasks/download_cache.yml
roles/edpm_ovn_bgp_agent/molecule/default/prepare.yml
roles/edpm_ovn_bgp_agent/tasks/download_cache.yml
roles/edpm_podman/defaults/main.yml
roles/edpm_podman/meta/argument_specs.yml
roles/edpm_podman/tasks/buildah_login.yml
roles/edpm_podman/tasks/login-kube-registry.yml
roles/edpm_podman/tasks/login.yml
roles/edpm_swift/tasks/download_cache.yml

Signed-off-by: Jiri Podivin <jpodivin@gmail.com>
(cherry picked from commit 3fe1f39744a6da6ca4597382977deed4dcd3593a)
Conflicts: 
- roles/edpm_telemetry/tasks/download_cache.yml

Set explicit podman auth_file location

---

.github/workflows/molecule.yaml
docs/source/playbooks/telemetry.rst
roles/edpm_telemetry/defaults/main.yml
roles/edpm_telemetry/meta/argument_specs.yml
roles/edpm_telemetry/molecule/default/molecule.yml
roles/edpm_telemetry/molecule/default/prepare.yml
roles/edpm_telemetry/molecule/default/verify.yml
roles/edpm_telemetry/tasks/download_cache.yml
roles/edpm_telemetry/tasks/install.yml
zuul.d/jobs.yaml
zuul.d/projects.yaml

Depends-On: openstack-k8s-operators/openstack-operator#1034

Update telemetry role to deploy Kepler

---

roles/edpm_bootstrap/defaults/main.yml
roles/edpm_bootstrap/meta/argument_specs.yml
roles/edpm_bootstrap/molecule/default/molecule.yml
roles/edpm_bootstrap/tasks/bootstrap_command.yml

closes [OSPRH-8627](https://issues.redhat.com//browse/OSPRH-8627)

Execute edpm_bootstrap_command based on the hash

---

roles/edpm_frr/defaults/main.yml
roles/edpm_frr/meta/argument_specs.yml

We have to also do it in defaults/main.yml
Jira: https://issues.redhat.com/browse/OSPRH-10338

Don't fail in argument validation

---

.github/workflows/molecule.yaml
docs/source/playbooks/telemetry.rst
roles/edpm_telemetry/defaults/main.yml
roles/edpm_telemetry/meta/argument_specs.yml
roles/edpm_telemetry/molecule/default/molecule.yml
roles/edpm_telemetry/molecule/default/prepare.yml
roles/edpm_telemetry/molecule/default/verify.yml
roles/edpm_telemetry/tasks/download_cache.yml
roles/edpm_telemetry/tasks/install.yml
zuul.d/projects.yaml

This reverts commit 0859e4e7455a5054c12a00c6a79386985ea90127.
Related-Issue: [OSPCIX-502](https://issues.redhat.com//browse/OSPCIX-502)
Related-Issue: [OSPCIX-503](https://issues.redhat.com//browse/OSPCIX-503)

Revert "Update telemetry role to deploy Kepler"

---

roles/edpm_libvirt/tasks/install.yml
roles/edpm_ovs/tasks/install.yml

closes [OSPRH-10511](https://issues.redhat.com//browse/OSPRH-10511)

Retry dnf download tasks

---

roles/edpm_extra_mounts/meta/argument_specs.yml

doc update for edpm-extra-specs roles

Doc-Update: replace hugepages1g to hugepages1G

---

roles/edpm_nova/tasks/main.yml

closes [OSPRH-8412](https://issues.redhat.com//browse/OSPRH-8412)

Ensure ssh_known_hosts file exists

---

OWNERS_ALIASES

Since i left the edpm core team, i guess it's time to remove myself from approvers list. :(

Remove `rebtoor` from approvers

---

.github/workflows/openstack-ansibleee-runner.yaml

We changed the file but did not update the workflow.

Fix github workflow to use Containerfile

---

roles/edpm_podman/molecule/disconnected/converge.yml
roles/edpm_podman/molecule/disconnected/molecule.yml
roles/edpm_podman/molecule/disconnected/prepare.yml
roles/edpm_podman/tasks/install.yml

Jira: https://issues.redhat.com/browse/OSPRH-11630

Disconnected molecule

---

roles/edpm_telemetry_power_monitoring/molecule/default/prepare.yml
roles/edpm_telemetry_power_monitoring/molecule/default/test-helpers/kepler.yaml
roles/edpm_telemetry_power_monitoring/molecule/default/verify.yml
roles/edpm_telemetry_power_monitoring/tasks/main.yml
roles/edpm_telemetry_power_monitoring/tasks/post-install.yml
roles/edpm_telemetry_power_monitoring/templates/firewall.yaml.j2

Without this rule prometheus cannot scrape kepler metrics.

Add firewall rule to include Kepler port

---

roles/edpm_frr/defaults/main.yml
roles/edpm_frr/meta/argument_specs.yml
roles/edpm_frr/molecule/default/verify.yml
roles/edpm_frr/tasks/install.yml
roles/edpm_frr/templates/frr.conf.j2
roles/edpm_frr/templates/kolla_config/frr.yaml.j2

All containerized services should log to the journal.

Don't log frr on EDPM nodes to files

---

roles/edpm_extra_mounts/molecule/default/verify.yml
roles/edpm_neutron_dhcp/tasks/configure.yml
roles/edpm_neutron_metadata/tasks/install.yml

We have largely tried to avoid using with_items in this repo in favor of loop. This change removes a couple of with_items that have snuck in.

Use loop instead of with_items

---

roles/edpm_frr/molecule/default/prepare.yml
roles/edpm_frr/molecule/default/verify.yml
roles/edpm_frr/tasks/firewall.yml
roles/edpm_frr/tasks/install.yml
roles/edpm_frr/tasks/main.yml
roles/edpm_nftables/templates/dport.j2

Open bgp and bfd ports.
Resolve: [OSPRH-14536](https://issues.redhat.com//browse/OSPRH-14536)

[ovn-bgp] Add missing firewall rules

---

docs/source/playbooks/update.rst
docs/source/roles/role-edpm_update.rst

Signed-off-by: James Slagle <james.slagle@gmail.com>

Add docs for update role and playbook

---

OWNERS_ALIASES

Remove bshephard

---

plugins/modules/edpm_container_manage.py
roles/edpm_container_manage/defaults/main.yml
roles/edpm_container_manage/meta/argument_specs.yml
roles/edpm_container_manage/tasks/main.yml
roles/edpm_nova/molecule/default/test-data/nova-cell1/02-nova-log.conf
roles/edpm_nova/molecule/default/verify.yml
roles/edpm_nova/tasks/configure.yml
roles/edpm_nova/templates/config.json.j2
roles/edpm_nova/templates/nova_compute.json.j2
roles/edpm_swift/defaults/main.yml
roles/edpm_swift/tasks/configure.yml

All services log to journald and /var/log/containers is not used at all. Remove it from roles.

Remove all /var/log/containers/* mounts

---

roles/edpm_nova/molecule/default/verify.yml

Related: [OSPRH-20052](https://issues.redhat.com//browse/OSPRH-20052)

Adds molecule test to disable nova_nvme_cleaner container
